packages/tools/examples/petCt/index.ts

My first PR on public repo! ^_^
PET-CT example/demo
- Fit view to screen size
- Add resize handlers
- Add instructions.
- Fix the fusion viewport overlay which was using MIP for some reason.
- Added a select for window/level or crosshairs.

Cleanup PET-CT example

---

utils/demo/helpers/initCornerstoneWADOImageLoader.js

set initializeCodecsOnStartup false

---

utils/ExampleRunner/build-all-examples-cli.js
utils/ExampleRunner/example-runner-cli.js

Just replace the replaceAll with replace with a /g in the regular expression

Fixing the replaceAll with replace /g

---

.eslintrc.json
common/reviews/api/core.api.md
common/reviews/api/streaming-image-volume-loader.api.md
common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/RenderingEngine.ts
packages/core/src/RenderingEngine/getRenderingEngine.ts
packages/core/src/RenderingEngine/renderingEngineCache.ts
packages/core/src/types/IEnabledElement.ts
packages/core/src/types/IRenderingEngine.ts
packages/core/src/types/index.ts
packages/docs/docusaurus.config.js
yarn.lock

- Extracts the IRenderingEngine type
- Add documentation search via algolia

feat: extract more types and add documentation search

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/getDefaultViewport.ts
packages/core/src/RenderingEngine/helpers/index.ts
packages/core/src/RenderingEngine/helpers/renderToCanvas.ts
packages/core/src/RenderingEngine/index.ts
packages/core/src/index.ts
packages/core/src/utilities/index.ts
packages/core/src/utilities/loadImageToCanvas.ts
packages/core/src/utilities/prefetchStack.ts
packages/core/src/utilities/renderToCanvas.ts

- Fix the renderToCanvas to use the CPU rendering pipeline
- Add stackPrefetch utility function

fix: renderToCanvas to use CPU rendering

---

common/reviews/api/tools.api.md
packages/core/src/cache/cache.ts
packages/tools/examples/magnifyTool/index.ts
packages/tools/src/enums/ToolBindings.ts
packages/tools/src/index.ts
packages/tools/src/tools/MagnifyTool.ts
packages/tools/src/tools/annotation/AngleTool.ts
packages/tools/src/tools/index.ts
packages/tools/src/types/ToolSpecificAnnotationTypes.ts
packages/tools/src/utilities/math/angle/angleBetweenLines.ts
packages/tools/src/utilities/viewportFilters/filterViewportsWithToolEnabled.ts

- Add MagnifyTool
- Add AngleTool
- Fix a bug in cache

feat: Add AngleTool and MagnifyTool

---

utils/ExampleRunner/template-multiexample-config.js

Modifying the webpack configuration file helps to debug all examples on windows

chore: Increase compatibility with Windows development environment

---

packages/core/src/RenderingEngine/StackViewport.ts

With this change the file in https://github.com/cornerstonejs/cornerstone3D-beta/issues/137 works

fix: Handle cases where row and column cosines are missing

---

packages/tools/package.json

Includes
- Ensure used d3 packages are present on package.json dependecies

ref ensure used d3 packages are also listed on dependencies

---

packages/docs/docs/concepts/cornerstone-core/volumes.md
packages/docs/docs/concepts/cornerstone-tools/annotation/locking.md
packages/docs/docs/concepts/cornerstone-tools/annotation/selection.md
packages/docs/docs/concepts/cornerstone-tools/annotation/state.md
packages/docs/docs/concepts/cornerstone-tools/segmentation/active.md
packages/docs/docs/concepts/cornerstone-tools/segmentation/segmentIndex.md
packages/docs/docs/concepts/cornerstone-tools/segmentation/segmentation-tools.md
packages/docs/docs/concepts/cornerstone-tools/synchronizers.md
packages/docs/docs/concepts/cornerstone-tools/tools.md
packages/docs/docs/concepts/streaming-image-volume/streaming.md

- Improving docs readability
- Typo fixes (including sentence duplication)
- Additional code highlighting

[fix] Documentation "Concepts"

---

common/reviews/api/core.api.md
common/reviews/api/streaming-image-volume-loader.api.md
common/reviews/api/tools.api.md
packages/core/examples/stackEvents/index.ts
packages/core/examples/volumeEvents/index.ts
packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/renderColorImage.ts
packages/core/src/requestPool/requestPoolManager.ts
packages/core/src/types/CPUFallbackRenderingTools.ts
packages/core/src/utilities/loadImageToCanvas.ts
packages/tools/src/eventDispatchers/imageRenderedEventDispatcher.ts
packages/tools/src/eventDispatchers/imageSpacingCalibratedEventDispatcher.ts
packages/tools/src/eventDispatchers/keyboardToolEventDispatcher.ts
packages/tools/src/eventDispatchers/mouseToolEventDispatcher.ts
packages/tools/src/tools/MagnifyTool.ts
packages/tools/src/tools/PanTool.ts
packages/tools/src/tools/StackScrollTool.ts
packages/tools/src/tools/TrackballRotateTool.ts
packages/tools/src/tools/WindowLevelTool.ts
packages/tools/src/tools/ZoomTool.ts
packages/tools/src/tools/annotation/AngleTool.ts
packages/tools/src/tools/annotation/ArrowAnnotateTool.ts
packages/tools/src/tools/annotation/LengthTool.ts
packages/tools/src/tools/annotation/planarFreehandROITool/findOpenUShapedContourVectorToPeak.ts
packages/tools/src/tools/segmentation/BrushTool.ts
packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts
packages/tools/src/utilities/triggerSegmentationRender.ts
tsconfig.base.json

https://github.com/cornerstonejs/cornerstone3D-beta/issues/158

fix: make typescript strict true

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/vtkClasses/vtkSlabCamera.d.ts
packages/docs/netlify.toml

Update import of vtkObject to match the new vtk.js types

Update type definition for vtkObject

---

common/reviews/api/tools.api.md
packages/tools/src/enums/ToolBindings.ts

ref. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#non-printable_keys_function_keys

fix: invalid keybindings Alt and Ctrl

---

packages/tools/src/tools/StackScrollTool.ts

fixes https://github.com/cornerstonejs/cornerstone3D-beta/issues/215

fix: stackScroll should honor invert configuration

---

packages/core/src/RenderingEngine/StackViewport.ts

https://github.com/cornerstonejs/cornerstone3D-beta/issues/218

fix: resetCamera should reset the rotation as well

---

packages/docs/docs/tutorials/basic-annotation-tool.md
packages/docs/docs/tutorials/basic-volume.md

Fixed some typos in documentations

fix(docs): typo cornerStreaming --> cornerstoneStreaming

---

packages/streaming-image-volume-loader/src/StreamingImageVolume.ts

fix: typo imageLodObject --> imageLoadObject

---

common/reviews/api/tools.api.md
packages/tools/examples/sharedToolState/index.ts
packages/tools/examples/volumeAnnotationTools/index.ts
packages/tools/examples/volumeViewportSynchronization/index.ts
packages/tools/src/store/state.ts
packages/tools/src/tools/base/AnnotationDisplayTool.ts
packages/tools/src/tools/base/AnnotationTool.ts

- AnnotationTool base class has limitations as in the tool needs to implement `addNewAnnotation` and also it runs with any mouse click. AnnotationDisplayTool tries to solves this

feat: add annotation display Tool

---

packages/tools/src/store/removeEnabledElement.ts
packages/tools/src/utilities/triggerAnnotationRender.ts

to resolve annotation render problem mention in #184

limit disabled element not need to render

---

common/reviews/api/core.api.md
common/reviews/api/tools.api.md
package.json
packages/core/src/utilities/getViewportImageCornersInWorld.ts
packages/core/src/utilities/index.ts
packages/tools/examples/referenceLines/index.ts
packages/tools/src/index.ts
packages/tools/src/store/state.ts
packages/tools/src/tools/ReferenceLinesTool.ts
packages/tools/src/tools/index.ts
packages/tools/src/types/ToolSpecificAnnotationTypes.ts
utils/ExampleRunner/example-info.json

https://deploy-preview-292--cornerstone-3d-docs.netlify.app/live-examples/referencelines

feat: add reference lines tool

---

packages/core/src/RenderingEngine/RenderingEngine.ts

Fix for [#2947 ](https://github.com/OHIF/Viewers/issues/2947)

fix: adjust canvas, not only off screen renderer on resize

---

packages/streaming-image-volume-loader/package.json

fix: streaming loader package json for entries

---

common/reviews/api/tools.api.md
packages/tools/src/tools/segmentation/PaintFillTool.ts
packages/tools/src/utilities/segmentation/floodFill.ts

fix: floodFill export in tools

---

packages/core/src/RenderingEngine/StackViewport.ts

https://github.com/OHIF/Viewers/issues/3121#issuecomment-1396647514

fix: monochrome1 bug for stackviewport

---

packages/adapters/package.json
packages/adapters/rollup.config.js

Just update the rollup and package.json file to include the build files.

fix(build): Adding exports and files

---

packages/adapters/package.json

Attempt 3 to try to get build to include the right files.

fix(build): adapters build missing files

---

.circleci/config.yml
packages/adapters/package.json
packages/adapters/rollup.config.js

Added adapters to circleci build

fix(build): Include adapters in circleci config

---

packages/core/src/utilities/getSliceRange.ts

fix(SliceRange): slice range for oblique image

---

packages/docs/docs/tutorials/intro.md

yarn run example tutorial
This command should be run in the root directory.

docs: update intro for running tutorials

---

common/reviews/api/tools.api.md
packages/tools/src/stateManagement/segmentation/helpers/normalizeSegmentationInput.ts
packages/tools/src/types/SegmentationStateTypes.ts

This PR includes the segment label information in the segmetnation State type

feat: include segment labels in segmentation state

---

packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts
packages/adapters/src/adapters/Cornerstone3D/RectangleROI.ts

Just re-order hte output and input so it renders correctly as a polyline, but also renders correctly once converted to RectangleROI

fix(adapter): The rectangle encoding of SR

---

packages/tools/src/tools/segmentation/strategies/fillSphere.ts
packages/tools/src/utilities/math/sphere/pointInSphere.ts

**Summary**
This fix optimizes the sphere tool for creating segmentations, reducing the time it takes for the texture to update. 
- "fillSphere.ts" now passes an array of modified slices to be rendered rather than rendering every slice in the volume
- "pointInSphere.ts" is now able to be optimized by the browser

perf(sphereBrush): tool optimization

---

packages/dicomImageLoader/src/imageLoader/createImage.ts
packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts

bring the rest of remaining code here from
- https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/509
- https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/516
Thanks @Ouwen and @lscoder

fix(dicomLoader): data type view after scaling

---

packages/tools/src/tools/WindowLevelTool.ts

Burned in Pixels often use pixel values above the BitsStored. This results in a multiplier which is way higher than what you would want in practice.

fix(windowLevelTool): WWWL multipler too high when burned in pixels are present

---

packages/core/src/RenderingEngine/StackViewport.ts

when not using the 16 bit texture, we shouldn't check data type

fix(stackViewport): check same image was broken after 16 bit texture

---

common/reviews/api/tools.api.md
packages/tools/examples/stackManipulationTools/index.ts
packages/tools/src/tools/StackScrollTool.ts
packages/tools/src/tools/StackScrollToolMouseWheelTool.ts
packages/tools/src/types/ScrollOptions.ts
packages/tools/src/utilities/scroll.ts

Allow the scroll tools StackScrollToolMouseWheelTool and StackScrollTool to configure the loop option. 
PS: this is my first PR and i read the contributing guide and wish i did it right.

feat(loop): option to scroll tools

---

packages/tools/src/tools/CrosshairsTool.ts

- My idea here is to increase the annotation stroke to a better experience on mobile screens.

fix(mobile): Crosshairs highlighted for mobile

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/VolumeViewport3D.ts

Added the unimplemented method.

fix(VolumeViewport3D) - implement  VolumeViewport3D.getCurrentImageIdIndex

---

packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
packages/streaming-image-volume-loader/test/StreamingImageVolume_test.js

strange binding issue when processing loading failure

fix(binding): fix this binding

---

packages/tools/src/store/SynchronizerManager/Synchronizer.ts

The one line description says it all.

fix(Synchronizer): Check for null rendering engine when handling disabling of elements.

---

common/reviews/api/tools.api.md
packages/tools/src/types/AnnotationStyle.ts

Fixed ToolStyleConfig type error for projects with strictNullChecks

---

packages/tools/examples/crossHairs/index.ts
packages/tools/src/drawingSvg/drawHandles.ts
packages/tools/src/tools/CrosshairsTool.ts

Adds a mobile configuration to be touch friendly.
- Larger handles
- Handles always show since there is no mouse hover
- Fix interaction locking

feat(mobile): modify config for crosshair tool

---

packages/core/src/RenderingEngine/RenderingEngine.ts
packages/dicomImageLoader/package.json

Just a one line fix to avoid trying to render a too small canvas.

fix(viewport): Exception on resize to very small window

---

packages/core/src/RenderingEngine/StackViewport.ts

https://github.com/cornerstonejs/cornerstone3D-beta/issues/558

feat(cpu event): added event pre stack new image for cpu

---

packages/tools/src/stateManagement/annotation/annotationState.ts

Fix triggering of 'ANNOTATION_ADDED' event multiple times (#570)

fix triggering of 'ANNOTATION_ADDED' event multiple times (#570)

---

packages/tools/src/utilities/math/polyline/getSubPixelSpacingAndXYDirections.ts

fixes #589   
@JamesAPetts FYI you changed these lines the last time in https://github.com/cornerstonejs/cornerstone3D-beta/commit/7c33fcc529a20fd5cbf2e35e0ad995ba79acd834

fix(planarFreehandROITool): proper handling of pure movements on y-axis

---

packages/tools/src/utilities/viewport/isViewportPreScaled.ts

No new feature added. Just adding some safe programming to prevent unwanted exception

fix js exception. safe programming only

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/VolumeViewport.ts
packages/core/src/utilities/getClosestImageId.ts
packages/tools/src/drawingSvg/drawCircle.ts
packages/tools/src/tools/base/AnnotationDisplayTool.ts
packages/tools/src/tools/segmentation/RectangleROIStartEndThresholdTool.ts
packages/tools/src/tools/segmentation/RectangleROIThresholdTool.ts

Applied dashing to drawCircle.
Refactored VolumeViewport.getCurrentImageId to use the utilities getClosestImageId.

fix(Circle and VolumeViewport): fixes to ensure measurements are rendered properly

---

packages/tools/src/tools/annotation/ArrowAnnotateTool.ts

Trigger ANNOTATION_MODIFIED event when edit `ArrowAnnotate` measurements,

trigger ANNOTATION_MODIFIED event on ArrowAnnotate Tool

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md
.github/stale.yml

etc.)
- [] "OS: 
- [] "Browser:

chore(github): issues template for github

---

packages/core/src/RenderingEngine/RenderingEngine.ts

feat(version1)!: publish version 1.0

---

lerna.json
packages/core/src/RenderingEngine/RenderingEngine.ts

etc.)
- [] "OS: 
- [] "Browser:

feat: cornerstone3D

---

package.json
packages/adapters/package.json
packages/core/package.json
packages/dicomImageLoader/examples/dicomImageLoaderWADOURI/index.ts
packages/dicomImageLoader/package.json
packages/docs/docs/concepts/cornerstone-tools/touch.md
packages/docs/docs/help.md
packages/docs/docusaurus.config.js
packages/docs/package.json
packages/docs/src/pages/index.js
packages/streaming-image-volume-loader/package.json
packages/tools/package.json

etc.)
- [] "OS: 
- [] "Browser:

chore(readme): update readme and google 

---

packages/dicomImageLoader/package.json

chore(package): update package.json module for dicomImageLoader

---

common/reviews/api/core.api.md
common/reviews/api/streaming-image-volume-loader.api.md
common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/RenderingEngine/VolumeViewport.ts
packages/core/src/cache/classes/ImageVolume.ts
packages/core/src/types/IImage.ts
packages/core/src/types/IImageVolume.ts
packages/core/src/types/IVolume.ts
packages/core/src/types/ScalingParameters.ts
packages/core/test/stackViewport_gpu_render_test.js
packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
packages/tools/src/tools/annotation/ProbeTool.ts
packages/tools/src/tools/base/AnnotationTool.ts

This Pull Request addresses an issue of inconsistency in the naming convention used in the codebase. The problem was between using "PET" and "PT" terms. To ensure consistency across the project, all instances of "PET" have been changed to "PT"​[1](https://github.com/cornerstonejs/cornerstone3D/pull/676/files)​.
Also isPrescaled was wrong and it should be isPreScaled
Change PET -> PT 
and isPrescaled -> isPreScaled
OHIF MPR for PT does not work because of this [check](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/RenderingEngine/helpers/setDefaultVolumeVOI.ts#L228) but the volume has isPrescaled :( 
- [] My code has been well-documented (function …

fix(PET vs PT): Change all to PT for consistency

---

packages/core/examples/dynamicVolume/index.ts
packages/tools/examples/dynamicCINETool/index.ts
packages/tools/examples/dynamicPetCt/index.ts
packages/tools/examples/generateImageFromTimeData/index.ts

etc.)
- [] "OS: 
- [] "Browser:

chore(examples): update links for the dynamic volume example

---

packages/core/src/RenderingEngine/StackViewport.ts
packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
packages/tools/examples/stackToVolumeWithAnnotations/index.ts

fixes #701 & fixes #684 & fixes #695
When the stack is composed of different image orientations, we want to apply/carry over the `voi` and `invert` if previously applied. (#701)
In addition the volumes should be able to use already cached pixelData from another volume (#695)
Finally the stack viewport when image is retrieved from a converted volume should handle array like windowlevel (#684)
Change the stack viewport to force application of the `voiRange` and `invert` if already applied. 
Try the `yarn run example stackAPI` with the following stack 
```js
const imageIds = await createImageIdsAndCacheMetaData({
StudyInstanceUID:
'1.3.6.1.4.1.14519.5.2.1.99.1071.26968527900428638961173806140069',
SeriesInstanceUID:
'1.3.6.1.4.1.14519.5.2.1.99.1071.55709921708100920670088158023720', …
```

fix(voi): fix the voi setting when the stack is composed of different orientations

---

common/reviews/api/core.api.md
common/reviews/api/streaming-image-volume-loader.api.md
common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/types/IImage.ts
packages/docs/docs/tutorials/basic-annotation-tool.md
packages/docs/docs/tutorials/basic-segmentation-tools.md
packages/docs/docs/tutorials/basic-volume.md
packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts

fixes https://github.com/cornerstonejs/cornerstone3D/issues/669
etc.)
- [] "OS: 
- [] "Browser:

fix(volumeloader): should work when images are cached

---

packages/docs/docs/concepts/cornerstone-tools/annotation/index.md

According to the context, it should be unlocking
Change the word locking to unlocking.
Before:
After:
etc.)

fix: change the word "locking" to "unlocking"

---

packages/core/src/RenderingEngine/BaseVolumeViewport.ts

Addresses [OHIF issue 3485](https://github.com/OHIF/Viewers/issues/3485)
When the `BaseVolume` actors are explicitly set, reset the inverted flag too.
Once this PR is merged and CS3D is released and OHIF is (re)linked to the CS3D release test [OHIF issue 3485](https://github.com/OHIF/Viewers/issues/3485) 
etc.)

fix(BaseVolumeViewport): when the volume actors are explicitly set, reset the inverted flag too

---

common/reviews/api/tools.api.md
packages/tools/src/drawingSvg/drawCircle.ts
packages/tools/src/drawingSvg/drawEllipse.ts
packages/tools/src/drawingSvg/drawHandles.ts
packages/tools/src/drawingSvg/drawLine.ts
packages/tools/src/drawingSvg/drawPolyline.ts
packages/tools/src/drawingSvg/drawRect.ts
packages/tools/src/drawingSvg/drawTextBox.ts
packages/tools/src/drawingSvg/index.ts
packages/tools/src/drawingSvg/setAttributesIfNecessary.ts
packages/tools/src/drawingSvg/setNewAttributesIfValid.ts
packages/tools/src/index.ts
packages/tools/src/tools/base/index.ts
packages/tools/src/tools/index.ts

Exported some classes and functions so they are more widely available.
etc.)

feat(api): Exported AnnotationDisplayTool, setAttributesIfNecessary, setNewAttributesIfValid

---

packages/core/src/RenderingEngine/RenderingEngine.ts
packages/nifti-volume-loader/package.json
utils/ExampleRunner/example-info.json
utils/ExampleRunner/template-multiexample-config.js

etc.)
- [] "OS: 
- [] "Browser:

fix(release): try to release nifti loader

---

packages/docs/docs/concepts/cornerstone-tools/annotation/config.md
packages/tools/src/stateManagement/annotation/config/ToolStyle.ts
packages/tools/src/tools/annotation/AngleTool.ts
packages/tools/src/tools/annotation/ArrowAnnotateTool.ts
packages/tools/src/tools/annotation/BidirectionalTool.ts
packages/tools/src/tools/annotation/CircleROITool.ts
packages/tools/src/tools/annotation/CobbAngleTool.ts
packages/tools/src/tools/annotation/EllipticalROITool.ts
packages/tools/src/tools/annotation/LengthTool.ts
packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
packages/tools/src/tools/annotation/ProbeTool.ts
packages/tools/src/tools/annotation/RectangleROITool.ts
packages/tools/src/tools/base/AnnotationTool.ts

Supersedes https://github.com/cornerstonejs/cornerstone3D/pull/760
Supersedes https://github.com/cornerstonejs/cornerstone3D/pull/760
https://www.cornerstonejs.org/live-examples/stackannotationtools
```javascript
const style = cornerstoneTools.annotation.config.style.getDefaultToolStyles()
style.global.textBoxVisibility = false;
cornerstoneTools.annotation.config.style.setDefaultToolStyles(style);
```
etc.)
- [] …

feat(Annotation): Add textBoxVisibility

---

common/reviews/api/core.api.md
packages/core/src/init.ts

Someone might think if they edit the config file in the init it would affect the flags, but in fact we were overriding it with {} 
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(config): confusing initial config on init

---

packages/tools/src/synchronizers/callbacks/stackImageSyncCallback.ts

The stack image sync changes added a reference to options that didn't use ?. so it was throwing a NPE if options wasn't set.
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(stackSync): Don't throw NPE if options is empty #795

---

packages/tools/src/tools/displayTools/Labelmap/labelmapDisplay.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(segmentation): should be able to change color

---

common/reviews/api/tools.api.md
packages/tools/src/tools/annotation/CircleROITool.ts
packages/tools/src/tools/annotation/DragProbeTool.ts
packages/tools/src/tools/annotation/EllipticalROITool.ts
packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
packages/tools/src/tools/annotation/ProbeTool.ts
packages/tools/src/tools/annotation/RectangleROITool.ts
packages/tools/src/utilities/getModalityUnit.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(modality unit): fix the modality unit per target

---

packages/core/src/RenderingEngine/VolumeViewport.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(voi): should publish voi change event on reset

---

packages/tools/examples/advancedMagnifyTool/index.ts

Advanced Magnify Tool example was pointing to localhost making it impossible to test for those that do not have any server running locally
- Image ids are now loaded from https://d3t6nz73ql33tx.cloudfront.net/dicomweb and anyone can test it.
- Added some information about the viewports right below them
- The way a fake segmentation is created also changed and it is now an oval instead of cylindrical shape making it better to visualize in any orientation.
**Before**
**After**

fix(advancedMagnifyTool): fixed advanced magnify tool example (imageIds)

---

packages/core/src/cache/classes/ImageVolume.ts
packages/tools/src/utilities/dynamicVolume/generateImageFromTimeData.ts
packages/tools/src/utilities/dynamicVolume/getDataInTime.ts
packages/tools/src/utilities/segmentation/utilities.ts

when we use the mask to grab the information from a reference volume, if they are not the same properties (spacing, direction, etc.) we should consider the voxel overlaps and average (maybe we re-configure this later or maybe do weighted average based on the overlap percentage)
calculates the voxel overlaps
etc.)
- …

fix(getDataInTime): to consider different image spacing for reference

---

packages/tools/examples/advancedColorbar/index.ts
packages/tools/examples/colorbar/index.ts
packages/tools/src/utilities/voi/colorbar/Colorbar.ts
packages/tools/src/utilities/voi/colorbar/ColorbarCanvas.ts
utils/ExampleRunner/example-info.json

Issue fixed
https://github.com/cornerstonejs/cornerstone3D/assets/931820/cfbf133c-d2e0-406a-a7b0-2bdd7226d7d8
Colorbar example improved
https://github.com/cornerstonejs/cornerstone3D/assets/931820/8ae326a6-e09b-48ca-b3fd-cc2f96e608d8

feat(colorbar) fixed ticks position and improved example

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/VideoViewport.ts
packages/core/src/RenderingEngine/Viewport.ts
packages/docs/docs/tutorials/basic-video.md
packages/tools/examples/orientationMarker/index.ts
packages/tools/src/tools/OrientationMarkerTool.ts

should fix https://github.com/cornerstonejs/cornerstone3D/issues/854
The orientation widget should not reset camera
@jmhmd 
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(crosshairs): and orientation markers and publish

---

packages/core/src/RenderingEngine/StackViewport.ts

Fixes #786
Call setInvertColor after setTransferFunction in StackViewport._resetProperties.
Follow the steps in #764
etc.)

fix(invert): Call setInvertColor after setTransferFunction in StackViewport._resetProperties.

---

common/reviews/api/tools.api.md
packages/tools/src/utilities/index.ts

This is a simple PR to just expose two calibration functions in order to develop length based tools outside cornerstone
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

exports(tools): Expose calibration functions

---

packages/tools/examples/overlayGrid/index.ts
packages/tools/src/utilities/dynamicVolume/getDataInTime.ts

etc.)
- [] "OS: 
- [] "Browser:

feat(getDataInTime): to export ijk as well for masks

---

packages/tools/src/stateManagement/annotation/config/ToolStyle.ts

Fixes https://github.com/cornerstonejs/cornerstone3D/issues/864
Example [Annotation Tool Modes](https://deploy-preview-874--cornerstone-3d-docs.netlify.app/live-examples/annotationtoolmodes)
```
const toolGroupId = "STACK_TOOL_GROUP_ID";
const styles = {
Length: {
colorHighlighted: 'rgb(0, 4, 255)',
textBoxVisibility: false,
},
global: {
lineWidth: '2',
textBoxVisibility: false,
textBoxFontSize: '20px',
textBoxLinkLineWidth: '5',
textBoxBackground: 'rgb(0, 4, 255)',
},
};
cornerstoneTools.annotation.config.style.setToolGroupToolStyles(toolGroupId, styles);
```
etc.) …

fix(Tools): Tool Styles Check Property

---

common/reviews/api/tools.api.md
packages/core/src/Settings.ts
packages/tools/src/store/SynchronizerManager/Synchronizer.ts
packages/tools/src/tools/CrosshairsTool.ts
packages/tools/src/types/ISynchronizerEventHandler.ts
packages/tools/test/CrosshairsTool_test.js

- Fixes some weird crosshairs behaviour when synchronizers where used (tmtv mode)
- Fixes this issue https://github.com/OHIF/Viewers/issues/3758
- 
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(synchronizers): support for async event handlers in Synchronizer class.

---

packages/tools/src/tools/annotation/SplineROITool.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: Spline tool import

---

packages/dicomImageLoader/src/imageLoader/internal/options.ts

fix(dicomImageLoader): Restore accidentally deleted options (#916)

---

packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts

It may be useful to be able to map back to the measurements with the tracking unique identifier, for example, in a situation where you need to load some custom data to the measurement.
The Tracking Unique Identifier is a random number added by the dcmjs library [here](https://github.com/dcmjs-org/dcmjs/blob/4252063433a35da2260c3eb0759179ee33972cdf/src/utilities/TID300/TID300Measurement.js#L41).
Manually tested.
etc.)

feat: add tracking unique measurement

---

.vscode/settings.json
packages/tools/src/stateManagement/segmentation/addSegmentationRepresentation.ts
packages/tools/src/tools/annotation/LivewireContourTool.ts
packages/tools/src/tools/annotation/SplineROITool.ts
packages/tools/src/tools/segmentation/strategies/utils/stackVolumeCheck.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: import from the viewportFilters again

---

packages/tools/test/stackSegmentation_test.js

etc.)
- [] "OS: 
- [] "Browser:

feat(release): remove the test to release

---

packages/core/src/init.ts

```
init.ts:127 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tier')
at init (init.ts:127:1)
at async initDemo (initDemo.js:11:1)
at async initializeDicomViewer (cornerstone3D.tsx:13:1)
```
Added optional chaining to resolve the issue of access to property of undefined object. 
etc.) …

fix: Prevent errors during access to property of undefined object.

---

packages/docs/docs/concepts/cornerstone-tools/tools.md

Extra code block in docs
Delete the extra code block
None
etc.)

docs: remove extra code block

---

packages/docs/docs/contribute/documentation.md

The `cs packages/docs/` should be `cd packages/docs/`
```diff
- cs packages/docs/
+ cd packages/docs/ 
```
None
etc.)

docs: fix development instruction

---

packages/dicomImageLoader/src/imageLoader/wadors/getPixelData.ts

For example, if streaming set false/0/null/'', false !== undefined is  true.
I think this line of code should be changed to `if (retrieveOptions.streaming) `whether it is load or prefetch scenario.
```diff
- if (retrieveOptions.streaming !== undefined) 
+ if (retrieveOptions.streaming) 
```
None
etc.)

fix: condition default streaming value

---

common/reviews/api/tools.api.md
packages/tools/src/stateManagement/annotation/FrameOfReferenceSpecificAnnotationManager.ts
packages/tools/src/stateManagement/annotation/annotationState.ts
packages/tools/src/stateManagement/annotation/helpers/state.ts
packages/tools/src/types/EventTypes.ts

- The event was not being triggered by the FOR state manager
- The annotation event is being used by the measurement service [here](https://github.com/OHIF/Viewers/blob/eb7c950d7e0dee35c0c51ac77e549798278ddcc4/extensions/cornerstone/src/initMeasurementService.js#L149) and it's not required to have viewport-related data since it's being consumed without it. This change makes it optional.
- Related PR: https://github.com/OHIF/Viewers/pull/3857
etc.) …

fix(state manager): Make viewport-related data optional for annotation event

---

packages/tools/src/tools/ReferenceLinesTool.ts

etc.)
- [] "OS: 
- [] "Browser:

fix ReferenceLines with showFullDimension empty array case.

---

packages/tools/src/store/SynchronizerManager/Synchronizer.ts

`renderingEngine` is not renderingEngine, it is viewport. And how can we use getViewport method before if statement?
If renderingEngine will be undefined there will be error 'Cannot read properties of undefined'.
Pull request will fix it.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …

fix: synchronizer wrong logic if renderingEnigne is not exist

---

packages/tools/src/stateManagement/segmentation/config/segmentationVisibility.ts

https://deploy-preview-1014--cornerstone-3d-docs.netlify.app/live-examples/stacksegmentation
```javascript
var { segmentationRepresentationUID } = cornerstoneTools.segmentation.activeSegmentation.getActiveSegmentationRepresentation("TOOL_GROUP_ID")
cornerstoneTools.segmentation.config.visibility.setSegmentationVisibility('TOOL_GROUP_ID', segmentationRepresentationUID, false)
```
etc.)
- [] The documentation page …

feat(Segmentation): Add stack to segmentation visibility

---

packages/core/examples/volumeAPI/index.ts
packages/core/src/RenderingEngine/BaseVolumeViewport.ts

Fixes https://github.com/cornerstonejs/cornerstone3D/issues/975
https://deploy-preview-1015--cornerstone-3d-docs.netlify.app/live-examples/volumeapi
etc.)
- [] "OS: 
- [] "Browser:

fix(VolumeViewport): Set properties invert

---

packages/streaming-image-volume-loader/src/helpers/splitImageIdsBy4DTags.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: Refactor image splitting logic to support additional metadata

---

packages/tools/examples/videoContourSegmentation/index.ts
utils/ExampleRunner/example-info.json
utils/demo/helpers/addManipulationBindings.ts

etc.)
- [] "OS: 
- [] "Browser:

chore(demo): fix imports and renames

---

packages/tools/src/tools/annotation/CobbAngleTool.ts

Make arc lines visibility configurable.
added showArcLines option for the tool, default is false.

fix(cobbAngle): make arc lines configurable

---

packages/tools/src/stateManagement/annotation/FrameOfReferenceSpecificAnnotationManager.ts

if annotation  for a tool did not exist was returning undefined instead of an empty array.
consistent with return type of function
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(annotation): return empty array instead of undefined when no annotation object

---

packages/tools/src/utilities/getCalibratedUnits.ts

Fixes calibration types not rendering
add types

fix(calibration tool): fix calibration type not being rendered on measurements 

---

packages/tools/src/synchronizers/callbacks/voiSyncCallback.ts
packages/tools/src/synchronizers/synchronizers/createVOISynchronizer.ts

This makes the VOI synchronizer watch for colormap changes and sync the viewports when it changes.
Added an auxiliaryEvent for the synchronizer

feat(colormap): add colormap to VOI synchronizer

---

packages/tools/src/stateManagement/annotation/annotationSelection.ts
packages/tools/src/tools/MIPJumpToClickTool.ts
packages/tools/src/tools/StackScrollToolMouseWheelTool.ts
packages/tools/src/tools/base/AnnotationDisplayTool.ts
packages/tools/src/tools/base/AnnotationTool.ts
packages/tools/src/tools/base/BaseTool.ts
packages/tools/src/utilities/getVolumeId.ts
packages/tools/test/getVolumeId_test.js

Impossible to scroll and use annotation with niftis because of a delta of the volumeId. This PR fixes it.
etc.)
- [] "OS: 
- [] "Browser:

fix nifti issues

---

packages/dicomImageLoader/src/imageLoader/wadouri/metaData/extractPositioningFromDataset.ts

Fixes #1146 
etc.)
- [] "OS: 
- [] "Browser:
https://github.com/cornerstonejs/cornerstone3D/pull/1145#issue-2174860610

fix: modality reference error

---

common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/core/src/utilities/getTargetVolumeAndSpacingInNormalDir.ts
packages/tools/package.json
packages/tools/src/tools/WindowLevelTool.ts
packages/tools/src/tools/segmentation/CircleROIStartEndThresholdTool.ts
packages/tools/src/tools/segmentation/RectangleROIStartEndThresholdTool.ts
packages/tools/src/tools/segmentation/RectangleROIThresholdTool.ts
packages/tools/src/utilities/index.ts

Impossible to scroll and use any tool in a nifti...
It's getting boring right now!
It started to fail since version 1.46.0
etc.)

Try another fix for nifti scroll

---

packages/core/src/RenderingEngine/Viewport.ts
packages/tools/src/drawingSvg/drawArrow.ts
packages/tools/src/drawingSvg/drawCircle.ts
packages/tools/src/drawingSvg/drawEllipseByCoordinates.ts
packages/tools/src/drawingSvg/drawHandle.ts
packages/tools/src/drawingSvg/drawLine.ts
packages/tools/src/drawingSvg/drawPath.ts
packages/tools/src/drawingSvg/drawPolyline.ts
packages/tools/src/drawingSvg/drawRect.ts
packages/tools/src/drawingSvg/drawRedactionRect.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: render annotations without plane normal on viewports and update default svg colors

---

packages/docs/docs/concepts/cornerstone-tools/annotation/state.md

annotations' S word should be removed and getAnnotations method parameters are written in reverse order
etc.)
- [] "OS: 
- [] "Browser:

docs: Update getAnnotation Api

---

common/reviews/api/tools.api.md
packages/tools/src/tools/TrackballRotateTool.ts
packages/tools/src/utilities/segmentation/brushSizeForToolGroup.ts
packages/tools/src/utilities/segmentation/brushThresholdForToolGroup.ts
packages/tools/src/utilities/segmentation/index.ts
packages/tools/src/utilities/segmentation/invalidateBrushCursor.ts
packages/tools/src/utilities/segmentation/utilities.ts

- **export getbrushinstance**
- **track ball rotate temp state**
- **api**
etc.)
- [] "OS: 
- [] "Browser:

feat(trackballrotate): temporarily reduce resolution during rotation for quicker interaction.

---

utils/ExampleRunner/example-info.json

A small spelling mistake
There are two "Labelmap Segmentation Swapping"
One of which should be "Labelmap Segmentation Locking"
etc.)

docs(examples): spelling Labelmap Segmentation Locking

---

common/reviews/api/tools.api.md
packages/core/package.json
packages/docs/package.json
packages/tools/package.json
packages/tools/src/tools/displayTools/Surface/addOrUpdateSurfaceToElement.ts
packages/tools/src/tools/segmentation/BrushTool.ts
yarn.lock

- **upgrade vtk js**
- **Fix referencedVolumeId assignment in BrushTool.ts**
- **Fix actor type casting in addOrUpdateSurfaceToElement.ts**
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

feat: upgrade vtk to 30p3p1

---

packages/core/src/RenderingEngine/RenderingEngine.ts

etc.)
- [] "OS: 
- [] "Browser:

feat(rendering): Correct the positioning for the viewport publish

---

utils/ExampleRunner/example-info.json

It's not in the list of examples, so I added it labelmapSegmentColorChange.
Example Labelmap Segment Color Change
https://deploy-preview-1198--cornerstone-3d-docs.netlify.app/live-examples/labelmapsegmentcolorchange.html
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …

docs(Example): missing labelmapSegmentColorChange

---

common/reviews/api/core.api.md
common/reviews/api/tools.api.md
packages/core/package.json
packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/core/src/RenderingEngine/RenderingEngine.ts
packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/RenderingEngine/Viewport.ts
packages/core/src/enums/Events.ts
packages/core/src/loaders/imageLoader.ts
packages/core/src/types/IImage.ts
packages/core/src/types/IStackViewport.ts
packages/core/src/types/IViewport.ts
packages/core/src/utilities/getViewportImageCornersInWorld.ts
packages/docs/package.json
packages/tools/package.json
packages/tools/src/tools/AdvancedMagnifyTool.ts
packages/tools/src/tools/AdvancedMagnifyViewport.ts
packages/tools/src/tools/AdvancedMagnifyViewportManager.ts
packages/tools/src/tools/OrientationMarkerTool.ts
packages/tools/src/tools/base/AnnotationDisplayTool.ts
packages/tools/src/tools/base/AnnotationTool.ts
packages/tools/src/tools/displayTools/Labelmap/labelmapDisplay.ts
packages/tools/src/tools/segmentation/BrushTool.ts
packages/tools/src/tools/segmentation/strategies/compositions/dynamicThreshold.ts
packages/tools/src/tools/segmentation/strategies/compositions/preview.ts
packages/tools/src/types/ToolSpecificAnnotationTypes.ts
packages/tools/src/utilities/cine/playClip.ts
packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
yarn.lock

**Fix memory leaks for widgets**: 
Where the added widgets were not removed when the viewport was disabled
----
**ERROR_EVENT**
New type of events designed to publish informative information to the consuming apps so that their UI can get updated accordingly
---
**Fixed reference lines issue in high dpi monitors**
--- 
**Update vtk**
To address segment hide issues
----
**Fix Advanced Magnify tool**
- to reset its state on new stack and new volume
- Moved the whole things to be a canvas annotation to show on all slices
etc.)
- [] I have run the `yarn build:update-api` to update the API documentation, and …

fix(misc): Resolve memory leaks and reference lines issue, update vtk, and improve Advanced Magnify tool

---

common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/helpers/setDefaultVolumeVOI.ts
packages/tools/src/enums/Events.ts
packages/tools/src/store/ToolGroupManager/ToolGroup.ts
packages/tools/src/tools/OrientationMarkerTool.ts
packages/tools/src/tools/annotation/BidirectionalTool.ts
packages/tools/src/tools/annotation/CircleROITool.ts
packages/tools/src/tools/annotation/EllipticalROITool.ts
packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
packages/tools/src/tools/annotation/RectangleROITool.ts
packages/tools/src/tools/annotation/SplineROITool.ts
packages/tools/src/utilities/getCalibratedUnits.ts
packages/tools/src/utilities/index.ts

**Fix ultrasound enhanced regions scaling**
Wrong scaling factor was applied
Additional tools use now the calibrated spacing: bidirectional, other ROIs
---
**Fix the issue where the VOI was getting loaded from cached images preventing consumer apps to invlaidate data** 
etc.)
- [] "OS: 
- [] …

fix(ultrasound-enhancement): Correct scaling factor and VOI loading issue

---

packages/core/src/eventTarget.ts
packages/dicomImageLoader/src/imageLoader/wadouri/loadImage.ts
packages/docs/docs/concepts/cornerstone-core/web-worker.md
packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
packages/tools/examples/webWorker/index.ts
packages/tools/src/store/SynchronizerManager/Synchronizer.ts

We are reverting changes here https://github.com/cornerstonejs/cornerstone3D/pull/1154/files since it is causing troubles. 
Since it is wrong after further consideration with Bill Wallace, for your custom loader, you should register the scheme with it and use your custom scheme in your URLs.
CC: @jlopes90 
etc.)
- …

fix(wadouri): custom loaders should register their schema, and add new debounce listener to event target

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/VideoViewport.ts
packages/tools/examples/videoSegmentation/index.ts

Due to changes in the canvas positioning to fix pixel positioning, the transform in the video viewport got broken.  This PR adjusts the transform so that it works correctly now.
Updated the transform in VideoViewport to be correct for the updated canvas size/scaling.
Fixed the videoSegmentation example (had gotten overwritten with the wrong example).
Run examples:
videoSegmentation
videoContourSegmentation
videoTools
pan/zoom
etc.) …

fix(video): video viewport annotation position

---

common/reviews/api/core.api.md
common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/core/src/RenderingEngine/RenderingEngine.ts
packages/core/src/RenderingEngine/Viewport.ts
packages/core/src/RenderingEngine/VolumeViewport.ts
packages/core/src/RenderingEngine/VolumeViewport3D.ts
packages/core/src/types/EventTypes.ts
packages/core/src/types/IVolumeViewport.ts
packages/tools/examples/crossHairs/index.ts
packages/tools/src/eventDispatchers/cameraResetEventDispatcher.ts
packages/tools/src/eventDispatchers/index.js
packages/tools/src/store/addEnabledElement.ts
packages/tools/src/store/removeEnabledElement.ts
packages/tools/src/tools/CrosshairsTool.ts

Reset angle, position and MIP on all viewports linked to the crosshairs
https://github.com/cornerstonejs/cornerstone3D/assets/93064150/62f8bd4f-bf22-474d-bc6b-8535d0f9001a

fix(crosshairs): reset crosshair angle and position on camera reset event

---

packages/core/src/utilities/convertStackToVolumeViewport.ts
packages/tools/examples/stackToVolumeWithAnnotations/index.ts

Example Stack to Volume Viewport With Annotations
https://deploy-preview-1207--cornerstone-3d-docs.netlify.app/live-examples/stacktovolumewithannotations.html
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

docs(Example): Update Stack to Volume Viewport With Annotations

---

packages/adapters/examples/segmentationStack/demo.ts
packages/adapters/examples/segmentationStack/index.ts

Example Segmentation Stack
https://deploy-preview-1205--cornerstone-3d-docs.netlify.app/live-examples/segmentationStack.html
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

docs(Example): Update Segmentation Stack

---

packages/streaming-image-volume-loader/src/helpers/splitImageIdsBy4DTags.ts

When dcmjs normalizes the dataset, the element and group are formatted in upper case, so a case check needs to be added.
let value = metaData.get('0019100c', imageId) || metaData.get('0019100C', imageId);
the value could be read correctly.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …

fix(dicom-normalization): Handle case sensitivity in element and group formatting

---

common/reviews/api/tools.api.md
packages/tools/src/utilities/getViewportForAnnotation.ts
packages/tools/src/utilities/getViewportsForAnnotation.ts

- Fix to #1203 
- Changes made to `/packages/tools/src/utilities/getViewportForAnnotation.ts` and `/packages/tools/src/utilities/getViewportsForAnnotation.ts`
- Added explicit return types to each default function
- Rectifies issue in 1203 that causes files to refer to an internal packages
- clone `https://github.com/simonbertoli/cornerstone3D.git` fix/get_viewport_for_annotation branch
- run `npm run build`
- issues in `/@cornerstonejs/tools/dist/types/utilities/getViewportForAnnotation.d.ts` and  `/@cornerstonejs/tools/dist/types/utilities/getViewportsForAnnotation.d.ts` are no longer present
etc.)
[blog]: …

fix(types): getViewport(s)ForAnnotation

---

packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts

related to https://github.com/OHIF/Viewers/issues/4081
etc.)
- [] "OS: 
- [] "Browser:

fix: Improve pre-scaling detection in BaseStreamingImageVolume

---

common/reviews/api/tools.api.md
packages/tools/src/types/CalculatorTypes.ts
packages/tools/src/utilities/math/basic/BasicStatsCalculator.ts
packages/tools/test/utilities/calculator.jest.js

The old implementation of the standard deviation calculation was slow and wrong.  Use Welford's algorithm isntead.
yarn test:unit 
has a hand calculated comaprison for standard deviation values.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrus …

fix(BasicCalculator): Use Welford's algorithm for the standard deviation calculation

---

packages/adapters/src/adapters/Cornerstone/MeasurementReport.js
packages/adapters/src/adapters/Cornerstone/Segmentation_4X.js
packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts
packages/adapters/src/adapters/Cornerstone3D/RTStruct/RTSS.ts
packages/core/src/RenderingEngine/Viewport.ts

related to https://github.com/OHIF/Viewers/issues/3915
etc.)
- [] "OS: 
- [] "Browser:

fix(adapters-export): Set SpecificCharacterSet to "ISO_IR 192" in Cornerstone and Cornerstone3D adapters

---

packages/docs/docs/concepts/cornerstone-tools/annotation/config.md
packages/docs/docs/concepts/cornerstone-tools/annotation/index.md
packages/docs/docs/concepts/cornerstone-tools/annotation/locking.md
packages/docs/docs/concepts/cornerstone-tools/annotation/selection.md
packages/docs/docs/concepts/cornerstone-tools/annotation/state.md
packages/docs/docs/concepts/cornerstone-tools/annotation/visibility.md

Documentation was wrong in many parts, using the variable `annotations` which does not exist in the `@cornerstonejs/tools` lib. Fixing docs to use the correct variation `annotation`.
Also the property `styles` was fixed to the correct one `style` in some parts and the `setToolGroupToolStyle` function was correct to `setToolGroupToolStyles`.
etc.)
- [] The documentation page has been updated as necessary for any …

docs: fix annotation variable spelling

---

common/reviews/api/tools.api.md
packages/tools/src/tools/CrosshairsTool.ts
packages/tools/src/tools/displayTools/Contour/contourDisplay.ts
packages/tools/src/tools/displayTools/Contour/contourHandler/handleContourSegmentation.ts
packages/tools/src/utilities/annotationHydration.ts
packages/tools/src/utilities/index.ts

Assign the correct imageId for annotations on stackviewport when loading an RT

fix(rt): assign correct imageId for Stack

---

packages/core/src/loaders/volumeLoader.ts

if `useSharedArrayBuffer` is not provided use the cornerstone configuration for it.
etc.)
- [] "OS: 
- [] "Browser:

fix(seg): Handle useSharedArrayBuffer configuration properly in volume creation

---

packages/tools/src/tools/CrosshairsTool.ts
packages/tools/src/tools/base/AnnotationTool.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: Disable viewport indicators in CrosshairsTool by default

---

packages/dicomImageLoader/src/externalModules.ts
packages/tools/examples/webWorker/index.ts
packages/tools/src/stateManagement/segmentation/polySeg/registerPolySegWorker.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: Add type: 'module' to web worker imports

---

packages/dicomImageLoader/src/decodeImageFrameWorker.js
packages/dicomImageLoader/src/externalModules.ts
packages/dicomImageLoader/src/shared/decoders/decodeHTJ2K.ts
packages/dicomImageLoader/src/shared/decoders/decodeJPEG2000.ts
packages/dicomImageLoader/src/shared/decoders/decodeJPEGBaseline8Bit.ts
packages/dicomImageLoader/src/shared/decoders/decodeJPEGLS.ts

etc.)
- [] "OS: 
- [] "Browser:

chore: use import meta url for decoder wasms

---

packages/adapters/examples/segmentationStack/index.ts
packages/adapters/examples/segmentationVolume/index.ts
utils/demo/helpers/createElement.ts

- Import or export in stack segmentation only supports one frame (beta)
- New "add active segmentation"
- New "active segment" in stack and volume
Example Segmentation Stack
https://deploy-preview-1336--cornerstone-3d-docs.netlify.app/live-examples/segmentationStack.html
Example Segmentation Volume
https://deploy-preview-1336--cornerstone-3d-docs.netlify.app/live-examples/segmentationVolume.html
etc.)
- [] The …

docs(Example): Update segmentation stack/volume

---

common/reviews/api/core.api.md
common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/VideoViewport.ts
packages/tools/src/types/CINETypes.ts
packages/tools/src/utilities/cine/playClip.ts
packages/tools/src/utilities/stackPrefetch/stackContextPrefetch.ts
packages/tools/src/utilities/stackPrefetch/stackPrefetchUtils.ts
packages/tools/src/utilities/viewport/jumpToSlice.ts

Fix the video play clip so it starts/stops the video.
As part of that, added support for some more tags on image rendered event for video so that a scrollbar can be kept up to date.
etc.)
- [] "OS: 
- [] "Browser: …

fix(video): Video play clip wasn't working

---

packages/core/src/utilities/uuidv4.ts

crypto.randomUUID requires https
Fix http environment crypto.randomUUID is undefined
export default function uuidv4(): string {
//return crypto.randomUUID()；
return crypto.randomUUID?.() || ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c => (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16));
}
etc.) …

fix(uuidv4): Fix http environment crypto.randomUUID is undefined

---

packages/tools/examples/scaleOverlayTool/index.ts

Just adding an additional viewport to the example.

examples(scale-overlay): update scale overlay example to contain 2 stack viewports

---

common/reviews/api/tools.api.md
packages/core/src/utilities/getVolumeId.ts
packages/tools/src/tools/MIPJumpToClickTool.ts
packages/tools/src/tools/StackScrollToolMouseWheelTool.ts
packages/tools/src/tools/WindowLevelTool.ts
packages/tools/src/tools/base/BaseTool.ts
yarn.lock

Scrolling nifti volumes with ? in the id is broken
Fixed the utility to get the volume id when the id is a nifti id containing slice index information, and added direct access to the getVolumeId method on BaseTool so that one can avoid going through targetIds when not needed.
Fixes https://github.com/cornerstonejs/cornerstone3D/issues/1365
etc.)
- [] The documentation page has been updated as necessary for any …

fix: Nifti volume id extraction from targetId

---

common/reviews/api/tools.api.md
packages/core/src/RenderingEngine/StackViewport.ts
packages/docs/netlify.toml
packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
packages/tools/src/utilities/getCalibratedUnits.ts

Use length for open planar freehand statistics, as area/perimeter aren't actually valid.
Use cm instead of 10*mm for US region that are specified in cm, and handle the scale correctly.
etc.)
- [] "OS: 
- [] "Browser: …

fix: Use the right type of measurements for non-closed freehand

---

packages/core/src/cache/cache.ts

- fix: check is possibly undefined
- fix: lack of undefined return
`tsconfig.base.json` -> `strictNullChecks` is `true`
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(Cache): Fix typescript cache

---

packages/tools/src/tools/WindowLevelTool.ts

fix volume3d use WindowLevelTool scalarData error
etc.)
- [] "OS: 
- [] "Browser:

fix(WindowLevelTool): scalarData volume3d

---

packages/core/src/eventTarget.ts

`dispatchEvent` return is `boolean`
`return;` is undefined to `return false;` is boolean
tsconfig.base.json -> `strictNullChecks` is true
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(EventTarget): dispatchEvent return is boolean

---

packages/adapters/src/adapters/Cornerstone/ParametricMap.ts
packages/adapters/src/adapters/Cornerstone/Segmentation_3X.js
packages/adapters/src/adapters/Cornerstone/Segmentation_4X.js
packages/adapters/src/adapters/Cornerstone/index.ts
packages/adapters/src/adapters/Cornerstone3D/ParametricMap/generateToolState.js
packages/adapters/src/adapters/Cornerstone3D/ParametricMap/index.js
packages/adapters/src/adapters/Cornerstone3D/index.ts
packages/adapters/src/adapters/helpers/checkIfPerpendicular.ts
packages/adapters/src/adapters/helpers/checkOrientation.ts
packages/adapters/src/adapters/helpers/compareArrays.ts
packages/adapters/src/adapters/helpers/getDatasetsFromImages.ts
packages/adapters/src/adapters/index.ts
packages/adapters/src/index.ts

feat(pmap): added parametric map adapter

---

packages/tools/src/tools/ScaleOverlayTool.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(scale overlay tool): race condition for viewports

---

.github/workflows/playwright.yml

Updating the workflow to use a stable version of ubuntu.

fix(workflow): use a fixed ubuntu version for the runner

---

common/reviews/api/core.api.md
packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/types/IViewport.ts

etc.)
- [] "OS: 
- [] "Browser:

feat(viewReference): add as nearby projection

---

common/reviews/api/core.api.md
common/reviews/api/dicom-image-loader.api.md
common/reviews/api/tools.api.md
packages/core/examples/wsi/index.ts
packages/core/src/RenderingEngine/WSIViewport.ts
packages/core/src/constants/microscopyViewportCss.ts
packages/core/src/types/IViewport.ts
packages/dicomImageLoader/src/imageLoader/internal/streamRequest.ts
packages/dicomImageLoader/src/imageLoader/isColorConversionRequired.ts
packages/tools/examples/wsiAnnotationTools/index.ts
packages/tools/src/init.ts
packages/tools/src/tools/VolumeRotateMouseWheelTool.ts

The miniview was in the wrong position/didn't show the borders.
Added CSS from OHIF microscopy viewport to enable showing the miniviewport in the right spot.
Added a disable widget handler to remove the old display when it is completed.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …

fix: Remove old display data on disable WSI viewport and move mini view

---

.circleci/config.yml
packages/adapters/package.json
packages/dicomImageLoader/package.json
packages/nifti-volume-loader/package.json
packages/tools/package.json
yarn.lock

etc.)
- [] "OS: 
- [] "Browser:

fix: peer dependency issues

---

packages/tools/src/tools/segmentation/CircleROIStartEndThresholdTool.ts

cornerstone3D 2.0 makes further steps to move towards the standards-based structuredClone function (via `csUtils.deepClone` which wraps it).
`lodash.clonedeep` is still used in the CircleROIStartEndThresholdTool, this PR reduces its usage.
This should fix the following error as well:
```
✘ [ERROR] Could not resolve "lodash.clonedeep"
../node_modules/@cornerstonejs/tools/dist/esm/tools/segmentation/CircleROIStartEndThresholdTool.js:20:22:
20 │ import cloneDeep from 'lodash.clonedeep';
╵                       ~~~~~~~~~~~~~~~~~~
You can mark the path "lodash.clonedeep" as external to exclude it from the bundle, which will
remove this error.
1:45:19 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../node_modules/@cornerstonejs/tools/dist/esm/tools/segmentation/Ci …
```

feat(structuredClone): further move from lodash.clonedeep to structuredClone

---

packages/core/src/RenderingEngine/Viewport.ts

change structuredClone to JSON.parse(JSON.stringify()) for deep copy!
The reason is that native deep copies cannot copy objects encapsulated by proxies.
fix: issue#1527 change structuredClone to JSON way
etc.)

fix: change structuredClone to the lib deep clone

---

.circleci/config.yml
common/reviews/api/tools.api.md
packages/tools/src/enums/Events.ts
packages/tools/src/stateManagement/segmentation/SegmentationStateManager.ts
packages/tools/src/stateManagement/segmentation/config/segmentationColor.ts
packages/tools/src/stateManagement/segmentation/events/triggerSegmentationAdded.ts
packages/tools/src/stateManagement/segmentation/helpers/normalizeSegmentationInput.ts
packages/tools/src/types/EventTypes.ts

This pull request includes several changes to the build configuration and the addition of a new event type for segmentation in the codebase. The most important changes are the transition from using Yarn to Bun for package management and build processes, and the introduction of the `SEGMENTATION_ADDED` event.
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L18-R24): Replaced Yarn commands with Bun commands for installing dependencies, building the project, and running various checks. [[1]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L18-R24) [[2]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L43-R37) …

feat(seg): add segmentation event tracking and migrate to Bun for CI

---

.circleci/config.yml

etc.)
- [] "OS: 
- [] "Browser:

fix(ci): use bun instead of node

---

packages/core/examples/multiVolumeCanvasToWorld/index.ts
packages/dicomImageLoader/src/imageLoader/isColorConversionRequired.ts
packages/tools/examples/crossHairs/index.ts

fixes https://github.com/cornerstonejs/cornerstone3D/issues/1561 and https://github.com/OHIF/Viewers/issues/4218
This pull request includes several changes across multiple files to improve functionality and code quality. The most important changes focus on refactoring code for better performance, updating tool usage, and adding new functionality.
* Removed unused `scalarData` and updated the method to retrieve voxel values using `voxelManager.getAtIJK` in `multiVolumeCanvasToWorld/index.ts` (`[[1]](diffhunk://#diff-8c6713f09d8f9ff0e1cbd64bae6950262a0e78864c2ca025f213e37b9276c020L145-R145)`, `[[2]](diffhunk://#diff-8c6713f09d8f9ff0e1cbd64bae6950262a0e78864c2ca025f213e37b9276c020L157-R157)`).
* Replaced `StackScrollTool` with `CrosshairsTool` in `crossHairs/index.ts` and updated related …

fix(color): pallet color photometric should not convert color space

---

packages/core/src/RenderingEngine/Viewport.ts

Currently, if the interpolation-type is NEAREST, then it's not preserved when calling `setDisplayArea`.
This is because `0 || 1` is `1`. This PR fixes it to use `??`: `0 ?? 1` which will preserve the 0.
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(interpolation): Preserve NEAREST (0) interpolation type

---

packages/core/src/utilities/generateVolumePropsFromImageIds.ts
packages/tools/src/utilities/cine/playClip.ts
utils/ExampleRunner/example-runner-cli.js

fixes https://github.com/cornerstonejs/cornerstone3D/issues/1569
This pull request includes several changes to improve the handling of image scaling parameters, add validation checks, and ensure safer string operations. The most important changes are grouped by theme below:
* [`packages/core/src/utilities/generateVolumePropsFromImageIds.ts`](diffhunk://#diff-116f591cd317bc0b3fab26c55da4841886f8a2b237f03773ad7a62f1375d0efbL90-L103): Refactored the `_determineDataType` function to check scaling parameters for the first, middle, and last images in the `imageIds` array. This includes checking for negative rescale values and float scaling parameters across these images.
* [`packages/tools/src/utilities/cine/playClip.ts`](diffhunk://#diff-7d179e40cf3e8d173095cb00390ee226e659dc9b71e006987d2bc49b8 …

fix(core): Improve image scaling and validation checks

---

packages/docs/docs/concepts/progressive-loading/requirements.md

This change fixes a typo in the Cornerstone docs found here: https://www.cornerstonejs.org/docs/concepts/progressive-loading/requirements#server-requirements-1
etc.)
- [] "OS: 
- [] "Browser:

docs: Fix typo in Progressive Loading docs

---

common/reviews/api/tools.api.md
packages/tools/src/cursors/SVGCursorDescriptor.ts
packages/tools/src/cursors/SVGMouseCursor.ts
packages/tools/src/eventDispatchers/mouseEventHandlers/mouseMove.ts
packages/tools/src/types/CursorTypes.ts
tests/multipleToolGroups.spec.ts

fixes https://github.com/cornerstonejs/cornerstone3D/issues/1516 
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1428

MouseEventHandlers: Remove unused cursor initialization in mouseMove

---

packages/adapters/examples/segmentationVolume/index.ts
packages/core/examples/webLoader/registerWebImageLoader.ts
packages/tools/examples/dynamicallyAddAnnotations/index.ts

[OHI-1305] [OHI-1298] [OHI-1326] fix(examples): fix dynamicallyaddannotations, webloader, segmentationVolume examples

---

packages/docs/docs/migration-guides/2x/5-tools.md

I have found that my own synchronizer for stack didn't work. The problem was a wrong import of jumpToSlice. I added it to the migration guide.
Added text that the jumpToSlice has migrated to the core.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …

Update 5-tools.md, jumpToSlice migrated to core

---

packages/core/examples/multiVolumeAPI/index.ts
packages/core/examples/multiVolumeCanvasToWorld/index.ts
tsconfig.json

-  Added a slider to the toolbar for opacity control, allowing users to adjust the opacity of the volume rendering.
-  Updated the toggle PET button functionality to consistently add PET volumes with the appropriate color map transfer function.
-  Changed volume loading to use async/await for better handling of asynchronous operations.
-  Improved code readability and maintainability by removing unnecessary comments and simplifying logic.
-  Updated `tsconfig.json` to adjust the paths for `@cornerstonejs/core` to only include the source directory.
etc.)
- [] I have run the `yarn build:update-api` to …

MultiVolumeAPI: Enhance volume loading and toolbar functionality

---

packages/tools/src/stateManagement/segmentation/events/triggerSegmentationRepresentationModified.ts

Calling the `triggerSegmentationRepresentationModified` function should emit `SEGMENTATION_REPRESENTATION_MODIFIED` instead of `SEGMENTATION_REPRESENTATION_ADDED` event. Latter should be reserved for adding new segment representations only.
Replaced emitted event type with `SEGMENTATION_REPRESENTATION_MODIFIED`.
etc.)
additions or …

Fix triggered event type when segment representation modified

---

packages/tools/examples/resetCamera/index.ts

delete unused import code of resetCamera 50ef30b02f434ae1ddc57d38ce818bac99c29067
etc.)
- [] "OS: 
- [] "Browser:

fix: delete unused import code of resetCamera

---

packages/tools/src/tools/annotation/LengthTool.ts

Removes unused variables within the Length tool.
etc.)
- X] The documentation page has been updated as necessary for any public API
- [] "OS: 
- [] "Browser:

chore: remove unused variables on Length tool

---

packages/docs/docs/getting-started/installation.md
packages/docs/docs/getting-started/vue-angular-react-etc.md

- **docs: update webpack config**
- **update**
etc.)
- [] "OS: 
- [] "Browser:

docs: update webpack config

---

packages/docs/docs/concepts/cornerstone-tools/annotation/config.md

Fixes annotation-level style example within the documentation. Looks like it was leftover from 1.x
etc.)

docs(tools): fix annotation style example

---

packages/docs/docs/getting-started/vue-angular-react-etc.md
packages/docs/docs/migration-guides/2x/1-general.md

etc.)
- [] "OS: 
- [] "Browser:

docs: update framework migration doc

---

packages/tools/src/tools/annotation/SplineROITool.ts

Prevent destructive property access when enabledElement is undefined
fixes #1634
etc.)
- [] "OS: 
- [] "Browser:

fix(SplineROI): prevent destructive property access

---

packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLViewNodeFactory.js

fixes #1677
This PR allow the usage of `ImageCPRMapper` in cornerstone3D
etc.)

fix: register ImageCPRMapper

---

common/reviews/api/tools.api.md
packages/tools/src/index.ts
packages/tools/src/tools/annotation/splines/index.ts

This PR exposes the spline classes underlying the SplineROITool so that library users may create their own spline tools. 
Add new namespace, `splines`, which exports spline classes. 
Import a spline class! :) 
etc.)
- [] "OS: 
- [] "Browser:

chore(export): spline classes for custom spline tool creation

---

packages/core/src/RenderingEngine/helpers/setDefaultVolumeVOI.ts

make sure its defined before accessing

fix(voi): check if voiLutFunction is defined before accessing

---

packages/tools/src/utilities/contours/updateContourPolyline.ts

Fixes #1738
Safely access the handle when not present on the contour annotation.
Added check to handles and use empty list in case not present.
etc.)
- [] "OS: 
- [] "Browser:

fix(tools): safely access handle points

---

common/reviews/api/tools.api.md
packages/tools/src/tools/annotation/ProbeTool.ts

Currently the probe tool has a fixed handle size/radius.
Allow for the configuration to specify the probe tool handle radius.
etc.)

feat(tools): Allow for the handle size for the probe tool to be specified in the configuration

---

packages/tools/src/store/removeEnabledElement.ts

Simple fix, functions _removeViewportFromSynchronizers() & _removeViewportFromToolGroup should not continue if enabledElement is undefined
```
if (!enabledElement) {
return;
}
```
etc.)
- [] "OS: 
- [] "Browser:

fix(removeEnabledElement): return if !enabledElement

---

packages/ai/examples/SAMClientSide/index.ts
packages/tools/examples/labelmapEditWithContour/index.ts
packages/tools/examples/labelmapStatistics/index.ts
packages/tools/examples/toolHistory/index.ts
packages/tools/examples/volumeAnnotationTools/index.ts
packages/tools/examples/wholeBodySegment/index.ts

etc.)
- [] "OS: 
- [] "Browser:

chore(examples): fix server url

---

packages/tools/src/tools/segmentation/strategies/utils/getItkImage.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: bundling issue with vite

---

packages/tools/src/utilities/cine/playClip.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(cine): Adjust dimension group index calculation for volume playback

---

packages/dicomImageLoader/src/imageLoader/wadouri/loadImage.ts

etc.)
- [] "OS: 
- [] "Browser:

fix: set full resolution fllag for wado uri image

---

utils/demo/helpers/initDemo.js

etc.)
- [] "OS: 
- [] "Browser:

fix(examples): fix labelmap interpolation example

---

packages/tools/examples/labelmapStatistics/index.ts
packages/tools/src/tools/segmentation/BrushTool.ts
packages/tools/src/tools/segmentation/strategies/compositions/labelmapStatistics.ts
packages/tools/src/tools/segmentation/strategies/compositions/preview.ts
utils/ExampleRunner/template-config.js
utils/demo/helpers/initDemo.js

- Clean up labelmapStatistic example
- Fix issue for statistic grab if non suv
- fix rspack source map to generate better debugging experience
- FIx issue where labelmap preview showed different color for other viewports in the scene, see image below

fix(labelmap): Resolve color inconsistency and statistic grab issues

---

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts

Before:
After:
etc.)
- [] "OS: 
- [] "Browser:

fix: planar freehand roi undefined unit

---

packages/tools/examples/annotationSelectionAndLocking/index.ts

Fixes #1838 
https://github.com/cornerstonejs/cornerstone3D/issues/1838#issuecomment-2672252533
etc.)
- [] "OS: 
- [] "Browser:

fix annotation lock example

---

packages/tools/src/utilities/segmentation/getSVGStyleForSegment.ts

reverts #1833 
etc.)
- [] "OS: 
- [] "Browser:

revert #1833

---

packages/ai/package.json
packages/docs/docs/getting-started/vue-angular-react-vite.md
packages/docs/docs/migration-guides/2x/1-general.md
packages/labelmap-interpolation/package.json
packages/polymorphic-segmentation/package.json

This commit includes:
- Added new scripts to AI, labelmap-interpolation, and polymorphic-segmentation packages
- New scripts include clean:deep, format-check, api-check, and prepublishOnly
- Created new documentation for framework integration with Vite, React, Vue, Angular, and Webpack
- Updated references to framework integration documentation in migration guide
etc.)
- [] The documentation page has been updated …

chore: Update package scripts and add framework integration documentation

---

packages/dicomImageLoader/src/imageLoader/createImage.ts
packages/dicomImageLoader/src/imageLoader/index.ts
packages/dicomImageLoader/src/imageLoader/isModalityLutForDisplay.ts
packages/dicomImageLoader/src/imageLoader/removeAFromRGBA.ts
packages/dicomImageLoader/src/imageLoader/setPixelDataType.ts

just adding more exports to dicom image loader

feat(exports): adding more exports to dicomImageLoader to make it easy to make your own custom image loader 

---

packages/core/src/RenderingEngine/BaseVolumeViewport.ts

The fix is related to OHIF issue [[Bug] Infinite loop in TMTV mode #4636
](https://github.com/OHIF/Viewers/issues/4636)
A recursive call of setViewReference was causing OHIF to stall. 
The fix was finally located in CS3D and the way we had to resetCamera  in BaseVolumeViewport->applyViewOrientation
etc.) …

fix(TVMT HP) - Fixes issue #4636 of OHIF related with infinite loop of setViewReference

---

packages/tools/src/tools/segmentation/strategies/BrushStrategy.ts

fix: try to pass the fake version number

---

packages/tools/examples/rectangleROIThreshold/index.ts
packages/tools/src/utilities/segmentation/rectangleROIThresholdVolumeByRange.ts
packages/tools/src/utilities/segmentation/thresholdSegmentationByRange.ts
packages/tools/src/utilities/segmentation/thresholdVolumeByRange.ts

etc.)
- [] "OS: 
- [] "Browser:

fix(segmentation): Add segmentation ID requirement for threshold operations

---

utils/ExampleRunner/example-info.json

Just added a link so the cursor 3D example will show in the example page of Cornerstone3D
etc.)
- [] "OS: 
- [] "Browser:

add a link for the cursor3D example

---

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/tools/examples/cursor3D/index.ts

Follow the same naming case as getVtkActiveCamera
etc.)

fix: switch from getVTKDisplayCoords to getVtkDisplayCoords

---

packages/tools/src/cursors/SVGCursorDescriptor.ts
packages/tools/src/tools/annotation/LabelTool.ts

fixes the icon name of LabelTool
fixes #1863
fixes #1858
etc.)

fix: trigger LabelChange for LabelTool

---

packages/adapters/examples/segmentationVolume/utils.ts
packages/adapters/src/adapters/Cornerstone3D/Segmentation/labelmapImagesFromBuffer.ts
packages/tools/test/stackSegmentation_test.js

Reintroducing events and chunks so that to maintain the performance and not to lose the ability of measuring progress while loading SEGs.
Also since at it, removing some unused variables from related parts of the code.
etc.)
- [] "OS: 
- [] "Browser:

fix(overlapping segs): reintroduce events and chunks

---

packages/tools/examples/ultrasoundEnhancedRegion/index.ts
packages/tools/src/tools/annotation/UltrasoundDirectionalTool.ts

Allow for Ultrasound annotations to be removed wit the eraser tool.
Added missing functionality to the `isPointNearTool` function from the `LengthTool` to allow it to be removed with the AnnotationEraserTool.
You can test the functionality by building the examples and using Ctrl + Left Click on an annotation on the `ultrasoundEnhancedRegion` example.
etc.)

Added unimplemented "isPointNearTool" function

---

.github/.dependabot.yaml
packages/docs/package.json
packages/docs/yarn.lock

etc.)
- [] "OS: 
- [] "Browser:

chore: try to add depandabot for bun

---

packages/core/src/RenderingEngine/Viewport.ts

Removed debug console logs from viewport
1. Removed unnecessary logs 
refactor(Viewport): Remove debug console logs from pan update logic
etc.)

refactor(Viewport): Remove debug console logs from pan update logic

---

packages/core/examples/meshLoader/index.ts
packages/core/src/cache/classes/Mesh.ts
packages/core/src/cache/index.ts
packages/core/src/enums/Events.ts
packages/core/src/enums/GeometryType.ts
packages/core/src/enums/MeshType.ts
packages/core/src/enums/index.ts
packages/core/src/index.ts
packages/core/src/loaders/cornerstoneMeshLoader.ts
packages/core/src/loaders/geometryLoader.ts
packages/core/src/loaders/index.ts
packages/core/src/loaders/utils/mesh/createMesh.ts
packages/core/src/loaders/utils/mesh/validateMesh.ts
packages/core/src/types/GeometryLoaderFn.ts
packages/core/src/types/IGeometry.ts
packages/core/src/types/IMesh.ts
packages/core/src/types/MeshData.ts
packages/core/src/types/index.ts
packages/docs/docs/concepts/cornerstone-core/geometryLoader.md
packages/polymorphic-segmentation/src/Surface/updateSurfaceData.ts
packages/tools/src/stateManagement/segmentation/helpers/normalizeSegmentationInput.ts
packages/tools/src/tools/displayTools/Surface/surfaceDisplay.ts
utils/ExampleRunner/example-info.json

Allow to load and cache meshes
fixes #1970 
This commit introduces a new geometry loader for loading and caching meshes in Cornerstone. The new loader supports various mesh formats including PLY, OBJ, STL, and VTP. It also supports loading materials in MTL format along with image formats like JPG, PNG, and JPEG.
etc.)

feat(geometryLoader): add support for loading and caching meshes

---

packages/core/src/RenderingEngine/RenderingEngine.ts
packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/utilities/getClosestImageId.ts
packages/tools/src/tools/segmentation/RectangleROIStartEndThresholdTool.ts
packages/tools/src/types/CalculatorTypes.ts
packages/tools/src/utilities/math/basic/BasicStatsCalculator.ts

This pull request includes several changes focused on improving the handling of image IDs based on view plane normals, adding new statistical calculations, and refactoring some existing methods for better readability and functionality.
* [`packages/core/src/RenderingEngine/StackViewport.ts`](diffhunk://#diff-68d9d8eea6b516148b349d78d67774d70ef1a0a0896f34f003fb3aab336802bfL2754-R2757): Added an option to ignore spacing when finding the closest image ID, improving the flexibility of the `getClosestImageId` function.
* [`packages/core/src/utilities/getClosestImageId.ts`](diffhunk://#diff-ab751156dac58056e164ddc3d3ee5cd3b4e14756dd9286d75897647c9ee7023aL10-R105): Refactored the `getClosestImageId` function to include an `ignoreSpacing` option, added better handling of metadata, and improved …

fix(jump): Add Center Statistic, and Refactor Code and choose closest imageId for stack to jump

---

packages/core/src/RenderingEngine/Viewport.ts

This pull request includes an update to the `Viewport` class in the `RenderingEngine` module to improve the handling of horizontal and vertical flips. The most important change ensures that the flip actions are only performed when there is a change in the flip state, which helps to prevent unnecessary rendering and potential flickering.
Improvements to flip handling:
* [`packages/core/src/RenderingEngine/Viewport.ts`](diffhunk://#diff-820bdf434bace4e9e622da846acb70b98bf9fd157b6392bc2b3a78d03bdcea76L1876-R1882): Modified the conditions to check if `flipHorizontal` and `flipVertical` values have changed before calling the `flip` method. This prevents redundant flip actions and reduces flickering.

fix: flip flickering

---

packages/core/src/RenderingEngine/StackViewport.ts
packages/core/src/enums/CalibrationTypes.ts
packages/core/src/utilities/getPixelSpacingInformation.ts
packages/core/src/utilities/index.ts
packages/tools/src/utilities/getCalibratedUnits.ts
utils/demo/helpers/createImageIdsAndCacheMetaData.js
utils/demo/helpers/getPixelSpacingInformation.js

Fixes: https://github.com/OHIF/Viewers/issues/4921 on the cornerstone side.
Run the Annotation Tools Stack example with the image with 
StudyInstanceUID: 1.3.46.670589.30.1.3.1.1625260923.1632320482484.1
SeriesInstanceUID: 1.3.46.670589.30.1.3.1.1625260923.1632320560703.1
Trace a length measurement.
The measurement should have mm units but has pixel units instead.
Before:
After:
etc.)
- [] "OS: 
- [] "Browser:
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-for …

fix: x-ray pixel spacing calibration

---

packages/tools/src/tools/segmentation/RectangleROIStartEndThresholdTool.ts

Better performances after removing duplicated code
- Remove duplicated code
etc.)
- [] "OS: 
- [] "Browser:

feat: Remove duplicated code in RectangleROIStartEndThresholdTool

---

packages/core/examples/meshLoader/index.ts
packages/tools/src/tools/ZoomTool.ts

This commit allows the usage of the mouseWheel for zoom in/out.
fix #1130
etc.)

fix(ZoomTool): add support for mouseWheel

---

.github/workflows/build-docs.yml
.github/workflows/codeql.yml

This pull request includes changes to the GitHub workflows to improve the deployment and code analysis processes. The most important changes include modifying the deployment script in the `build-docs.yml` workflow and updating the triggers for the `codeql.yml` workflow.
Improvements to deployment process:
* [`.github/workflows/build-docs.yml`](diffhunk://#diff-4fdc48ab490b670c90974725b8e3d399b24c03d6d09563acf8ea87d4113930fbL106-R108): Changed the `run` command to navigate to the `packages/docs` directory before deploying with Netlify. This ensures the correct directory structure is used during deployment.
Updates to code analysis workflow:
* [`.github/workflows/codeql.yml`](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27L15-L16): Removed the `push` …

fix: artifact for test finally

---

.github/workflows/build-docs.yml
package.json

etc.)
- [] "OS: 
- [] "Browser:

fix: artifact for test with debug

---

packages/tools/src/tools/segmentation/BrushTool.ts

There's currently a bug with the BrushTool. You can reproduce the bug by doing the following:
1- visit a study in segmentation mode such as https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2
2- draw a segment with the brush
3- click the app arrow to go back to the worklist (do not go back with the browser api)
4- go back to the same study in segmentation mode
After following the steps you will see that the app crashes. This PR will fix it.
etc.)
additions or …

fix: brush tool crashing

---

.github/workflows/playwright.yml

etc.)
- [] "OS: 
- [] "Browser:

fix: keep artifacts longer

---

.github/workflows/build-docs.yml

etc.)
- [] "OS: 
- [] "Browser:

fix: test coverage deploy

---

packages/docs/package.json
packages/docs/scripts/generate-redirects.js

etc.)
- [] "OS: 
- [] "Browser:

fix: redirect coverage

---

package.json
packages/adapters/package.json
packages/adapters/src/version.ts
packages/ai/package.json
packages/ai/src/version.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/version.ts
packages/labelmap-interpolation/package.json
packages/labelmap-interpolation/src/version.ts
packages/nifti-volume-loader/package.json
packages/nifti-volume-loader/src/version.ts
packages/polymorphic-segmentation/package.json
packages/polymorphic-segmentation/src/version.ts
packages/tools/package.json
packages/tools/src/index.ts
packages/tools/src/version.ts
scripts/generate-version.js

Add the ability to check the current package version dynamically.
You can do
```ts
import { version } from '@cornerstonejs/core'
console.debug(version)
```
or
```ts
import * as cornerstoneTools from '@cornerstonejs/tools'
console.debug(cornerstoneTools.version)
```
closes: https://github.com/cornerstonejs/cornerstone3D/issues/2066

feat(version): add version property 

---

.circleci/config.yml
publish-version.mjs

Bumps version.ts so it's not 1 version behind

feat(version): bump version.ts during publish

---

packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts
packages/dicomImageLoader/src/imageLoader/wadouri/metaData/metaDataProvider.ts

Would be useful to extract the series description information from a dicom if available.
Add SeriesDescription to the WADO URI and WADO RS metadata providers
etc.)
Chrome 133.0.6943.142

Add SeriesDescription to the WADO URI and WADO RS metadata providers

---

packages/tools/src/tools/annotation/BidirectionalTool.ts

fix(hydrate): bidirectional was not hydrating properly

---

packages/docs/docs/tutorials/examples.md

Fixes #2091 
Issue: 
Fix: 
- Before: https://player.vimeo.com/video/694244249 does not exit . 
- After: https://player.vimeo.com/video/843234360
- Before: https://player.vimeo.com/video/694244249 does not exit . 
- After: https://player.vimeo.com/video/843234360
Describe how we can test your changes.
- open a URL: https://player.vimeo.com/video/843234360?h=06d45e5a5f&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;dnt=1
- Code review: 
https://github.com/cornerstonejs/cornerstone3D/edit/main/packages/docs/docs/tutorials/examples.md
etc.)

update cornerstone3d live examples debug vimeo video hyperlink

---

packages/tools/src/tools/SculptorTool.ts
packages/tools/src/tools/SculptorTool/CircleSculptCursor.ts

This pull request introduces enhancements to the sculpting functionality in the `SculptorTool` and its associated `CircleSculptCursor` class. The changes focus on improving the precision and responsiveness of sculpting operations, adding dynamic tool size adjustments, and maintaining the natural structure of contours during modifications.
* Added `deltaWorld` to the `SculptData` type for capturing changes in world coordinates during sculpting operations. This enables more precise manipulation of points. [[1]](diffhunk://#diff-b2124bc77c34fee7af51a15b7b36c2cf47f62af37d72cc5f0787a85ee0eae8e6R34-R38) [[2]](diffhunk://#diff-b2124bc77c34fee7af51a15b7b36c2cf47f62af37d72cc5f0787a85ee0eae8e6R146-L149)
* Introduced a new configuration option, `updateCursorSize`, set to `'dynamic'`, allowing the …

fix: sculptor tool bug fixes 

---

packages/tools/src/tools/annotation/CircleROITool.ts
packages/tools/src/tools/annotation/EllipticalROITool.ts
packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
packages/tools/src/tools/annotation/RectangleROITool.ts

Internally, for closed shapes, application computes the min & max value.
But actual implementation of method _calculateCachedStats in individual tool does not retain the min value.
etc.)

feat(tools): add min statistics to circle, ellipse, freehand(closed), rectangle

---

packages/tools/src/tools/segmentation/LabelmapEditWithContour.ts

Minor refactor:
Using the LabelMapEditWithContourTool, when you already have a segmentation with contour representation or when you disable and enable or activate the tool, it keeps checking for contour representations.
etc.)
- [] "OS: 
- [] "Browser:

Fix repetitive checks in segmentation with contours

---

packages/dicomImageLoader/src/imageLoader/wadors/metaDataManager.ts

current test for multiframe relies of "NumberOfFrames" tag to exists and contains a number greater ( strictly ) than one.
This explicitly excludes multiframe dicom container containing a single frame ( NumberOfFrames = 1 )
This MR uses IOD to enforce Multiframe. ( with fallback on legacy logic for non multiframe IODs )
etc.)

fix(metaDataManager): add logic to enforce multi-frame semantic based on DICOM IOD

---

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts

See #2121 
The title says it all.
#2121 should be fixed
etc.)

fix(PlanarFreehandROITool): Include the mm spacing/delta for canvas coordinates in the perimeter calculation.

---

packages/ai/src/ONNXSegmentationController.ts
packages/ai/src/enums/Events.ts
packages/ai/src/enums/index.ts
packages/ai/src/index.ts

Export AI events for AI models download status notifications
This PR exports AI events to enable UI notifications for AI models download status in OHIF ([OHIF/Viewers#5129](https://github.com/OHIF/Viewers/issues/5129)).
* Confirmed that AI events is accessible via `@cornerstonejs/ai`
etc.)

Export ONNX events

---

packages/tools/examples/stackViewportsWithSegmentationSync/index.ts
packages/tools/src/eventListeners/segmentation/imageChangeEventListener.ts
utils/ExampleRunner/example-info.json

Fixes: https://github.com/cornerstonejs/cornerstone3D/issues/2150
Fixes: https://github.com/OHIF/Viewers/issues/5142

fix(segmentation): stack viewport flicker when there's a segmentation added

---

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/core/src/RenderingEngine/VolumeViewport.ts
packages/core/src/RenderingEngine/helpers/createVolumeActor.ts
packages/core/src/cache/classes/ImageVolume.ts

Prevent cannot read properties of undefined (reading 'volumeId')
also fixes #2041
etc.)

fix(BaseVolumeViewport): avoid undefined volumeId reference in error message

---

packages/core/src/cache/classes/BaseStreamingImageVolume.ts
packages/tools/src/utilities/stackPrefetch/stackContextPrefetch.ts
packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts

Address runtime issues introduced by #2163
etc.)
- [] "OS: 
- [] "Browser:

fix: prefetch issues with retrieve options

---

packages/tools/examples/referenceCursors/index.ts

Fix the typo in cursor crosshair example description.
Fix the typo.
etc.)
- [] "OS: 
- [] "Browser:

fix: typo in cursor crosshair example description

---

packages/tools/src/stateManagement/segmentation/helpers/normalizeSegmentationInput.ts

The current CS3D lacks the function normalizeContourSegments, needed for normalizing contours segments from geometry data
etc.)
- [] "OS: 
- [] "Browser:

fix missing normalizeContourSegments

---

packages/tools/src/store/addEnabledElement.ts
packages/tools/src/tools/segmentation/SegmentLabelTool.ts

First step to address issues of https://github.com/OHIF/Viewers/issues/4600
1. Slightly improves SVG shadows so that they are more visible. The visual change is barely noticeable, but it really makes a difference in making the SVG stand out on the viewport.
2. Adds more configuration options to the SegmentLabelTool.
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

feat: improve tool styles

---

packages/core/src/RenderingEngine/ContextPoolRenderingEngine.ts

Disable widget renderers after render

fix(widgets): disable widget renderers after render

---

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
packages/core/src/types/OrientationVectors.ts

When navigating to an unknown view, resets the view plane normal to the first found of:
1. Current view
2. acquisition
3. axial, sagittal, coronal
4. A generated view plane normal.
It then navigates the position/focal point so that the new view is in view.
etc.)
- [] "OS: 
- [] "Browser:

fix: Reset view plane to axial/sag/cor by default if possible

---

packages/tools/src/tools/segmentation/CircleROIStartEndThresholdTool.ts

It was fixed in this https://github.com/cornerstonejs/cornerstone3D/pull/2128 but with some side changes for the new handles (https://github.com/cornerstonejs/cornerstone3D/pull/2122) it was broken again.
Fixed the projectionPoints so it's not broken when the end is above the start point.
Can be tested with the circleROIStartEndThresholdWithSegmentation
etc.)
- [] "OS: 
- [] "Browser:
[script]: …

fix(CircleROIStartEndThresholdTools) : fix (again) projection points calculation when the end point is above start point

---

addOns/externals/dicom-microscopy-viewer/package.json
package.json
packages/docs/docs/migration-guides/4x/5-node-20-upgrade.md

etc.)
- [] "OS: 
- [] "Browser:

chore: update Node.js version requirement to 20 in package.json files and add migration guide

---

packages/tools/src/store/SynchronizerManager/getSynchronizer.ts

- No functional change or breaking API changes are introduced.
- All existing tests pass.
- The build process completes successfully.

refactor: Clarify getSynchronizer return type)

---

packages/docs/docs/tutorials/examples.md
packages/docs/docs/tutorials/intro.md

Help minimize supply chain attacks for devs.
Description says it all.
etc.)

fix(docs): add frozen lockfile to yarn install instructions

---

packages/tools/examples/contourApi/index.ts

Title says it all.
Title says it all.
Run the contour api example. Convert holes should be present there.
etc.)

chore(examples): Added convert contour holes example to the contour api example

---

packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts

In developer console, for stack viewport with stackPrefetch enabled, we get 'prefetch done: undefined' because image object (instead of imageId) is being passed to 'doneCallback' (this expects 'imageId' according to the code) function.
Passing 'imageId' string instead 'image' object.
etc.)
- [] "OS: 
- [] "Browser:

fix: imageId instead of image

---

packages/tools/src/tools/annotation/EllipticalROITool.ts

Fixed EllipticalROITool stats missing bug
Before
After

fix ellipse ROI stats

---

packages/tools/src/utilities/contourSegmentation/logicalOperators.ts

When contour logical operators update/create a segment, the segment's label and color are always overwritten - even when they are not defined.
Only update label and color for logical operations when they are defined.
etc.)

fix(segmentation): For contour segmentation logical operators, avoid updating segment color and label when they are not defined/specified.

---

packages/tools/examples/stackManipulationTools/index.ts
packages/tools/src/tools/PanTool.ts

Added `limitToViewport` configuration to Pan tool so that we can limit panning off viewport.

feat: limit pan off viewport
