cornerstonejs/cornerstone3D

utils/demo/helpers/initCornerstoneWADOImageLoader.js
Limit the webworkers to the minimum of 7 or hardware concurrency, so we don't spin up too many workers (this is an empircally stable number derived during Cornerstone Legacy development).
=> limit number of workers used in examples

packages/core/package.json
The 'module' field in package.json should probably use a '.js' extension instead of '.ts'. The generated output files located in `packages/core/dist/esm` don't actually include any .ts files. Changing the extension resolves build issues experienced in Vite when importing the ESM build of @cornerstonejs/core.
Discussion here: #64
=> fix: change package.json 'module' field to use '.js' extension from '.ts'

packages/streaming-image-volume-loader/package.json, packages/tools/package.json
Addresses https://github.com/cornerstonejs/cornerstone3D-beta/issues/64
Fixes the other two packages with the same change that @ty-ler made here https://github.com/cornerstonejs/cornerstone3D-beta/pull/65
=> fix: Correct module property for ESM builds in package.json

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/getDefaultViewport.ts, packages/core/src/enums/Events.ts, packages/core/src/requestPool/imageLoadPoolManager.ts, packages/core/src/requestPool/imageRetrievalPoolManager.ts, packages/core/src/requestPool/requestPoolManager.ts, packages/core/src/types/EventTypes.ts, packages/core/src/types/IImage.ts, packages/core/src/utilities/loadImageToCanvas.ts, packages/core/src/utilities/prefetchStack.ts, packages/docs/docs/concepts/cornerstone-tools/annotation/selection.md, packages/tools/examples/annotationSelectionAndLocking/index.ts, packages/tools/examples/rectangleROIThreshold/index.ts, packages/tools/src/eventDispatchers/mouseEventHandlers/mouseDown.ts, packages/tools/src/eventDispatchers/mouseEventHandlers/mouseDownActivate.ts, packages/tools/src/stateManagement/annotation/annotationSelection.ts, packages/tools/src/stateManagement/annotation/config/getState.ts, packages/tools/src/types/EventTypes.ts, packages/tools/src/utilities/index.ts, packages/tools/src/utilities/orientation/getOrientationString.ts, packages/tools/src/utilities/orientation/getOrientationStringLPS.ts, packages/tools/src/utilities/orientation/index.ts, packages/tools/src/utilities/orientation/invertOrientationString.ts, packages/tools/src/utilities/orientation/invertOrientationStringLPS.ts
- change the selection api to not rely on the annotation object (UID is enough)
- add PRE_NEW_STACK_IMAGE event for consumers
- add a check for if the loaded image is prescaled (if it was loaded with the scaling parameters), if so it handles the PT non scaled images
- Fix the CPU rendering for PT images 
- Add id to the pool managers
- Fix a bug in the requestPoolManager when a new image is added (interaction priority), it was waiting for a request to be finished before sending the high priority image request
- Fix a bug in requestPool to set the maximum number of requests based on the requestType, previously it was summing all up and comparing them with the current number of requests, it should be per requestType
- Fix prefetching imageIds requests to properly set the prefetch …
=> fix: selection API, requestPoolManager and VOI and Scaling

common/reviews/api/tools.api.md, packages/tools/src/enums/Events.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/types/EventTypes.ts
Add annotation completed event
=> feat: Add annotation completed event 

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/utilities/imageToWorldCoords.ts, packages/core/src/utilities/index.ts, packages/core/src/utilities/worldToImageCoords.ts
add worldToImage and imageToWorld utilities
=> feat: Add worldToImage and imageToWorld utilities

common/reviews/api/tools.api.md, packages/tools/src/index.ts, packages/tools/src/tools/annotation/ArrowAnnotateTool.ts, packages/tools/src/tools/index.ts
To be consistent with cornerstone tools legacy
=> fix: rename ArrowTool to ArrowAnnotate

packages/core/package.json, packages/streaming-image-volume-loader/package.json, packages/tools/package.json
Attempts to address https://github.com/cornerstonejs/cornerstone3D-beta/issues/80
Basically Lerna won't update our peerDeps for us (see closed issue https://github.com/lerna/lerna/issues/1575) so I'm just moving everything to dependencies instead. I don't see a major downside of this.
=> fix: Attempt to resolve incompatible peerDeps situation

common/reviews/api/tools.api.md, packages/tools/src/tools/annotation/planarFreehandROITool/drawLoop.ts, utils/ExampleRunner/example-info.json
- This PR prevents very small annotations that may even be too small to render from being created.
- These annotations are removed on mouse up, and no annotation completed event is fired.
=> Freehand: Prevent very small annotations from being drawn

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/planarFreehandROITool/renderMethods.ts
Add optional configuration for the planar freehand roi tool:
- allowsRenderOpenContourHandles: boolean (default false)
- When true, always render end points when you have an open contour, rather than just rendering a line.
- alwaysRenderOpenContourHandlesRadius: number (default 2)
- When `allowsRenderOpenContourHandles` is true, use this radius to draw the endpoints when not hovering.
=> Add the option to always render handles on open contours

packages/core/src/RenderingEngine/RenderingEngine.ts
Fixed resizing after the devicePixelRatio changes here (https://github.com/cornerstonejs/cornerstone3D-beta/pull/127) broke it.
=> fix: Fix resize behaviour after devicePixelRatio changes

packages/core/src/RenderingEngine/StackViewport.ts
Might fix https://github.com/cornerstonejs/cornerstone3D-beta/issues/106, not sure
=> fix: Pixel data array was the wrong length for color images

common/reviews/api/tools.api.md, packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/DragProbeTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/utilities/getModalityUnit.ts, packages/tools/src/utilities/viewport/isViewportPreScaled.ts
This pull request addresses two points:
1) Unify handling of annotation units.
So far, each annotation (elliptical, rectangle, probe) was handling units on its own (and in a slightly different way). This is unified and the actual function is taken from https://github.com/OHIF/Viewers/blob/ae897c47e08611014ad1918b567df36444764329/extensions/cornerstone/src/utils/measurementServiceMappings/utils/getModalityUnit.js
2) By taking the function linked above, `MO` is not shown anymore. 
Before, for every modality that is not PT and not CT, `MO` was shown as unit for the annotations. I find this confusing, as `MO` doesn't have a physical meaning. I only recently learned that it stands for "modality unit" (as opposed to stored pixel value). See …
=> fix: unify handling of annotation units and remove 'MO'

packages/core/src/RenderingEngine/StackViewport.ts
=> fix: revert the stack viewport setting of targetImageIndex

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/types/IStackViewport.ts, packages/core/src/types/IVolumeViewport.ts, packages/core/src/utilities/getViewportsWithImageURI.ts, packages/core/src/utilities/getViewportsWithVolumeId.ts, packages/core/src/utilities/index.ts, packages/core/test/volumeViewport_gpu_render_test.js, packages/streaming-image-volume-loader/src/helpers/autoLoad.ts, packages/tools/examples/stackToVolumeWithAnnotations/_setViewports.ts, packages/tools/examples/stackToVolumeWithAnnotations/index.ts, packages/tools/src/tools/WindowLevelTool.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/base/BaseTool.ts, utils/ExampleRunner/example-info.json
This fixes the problem where stack viewport is converted to a volume viewport, but annotations cannot render and throws error. 
- New Demo https://deploy-preview-195--cornerstone-3d-docs.netlify.app/live-examples/stacktovolumewithannotations
=> fix: annotations throwing error when stack and volume viewports are converted

packages/tools/src/tools/annotation/planarFreehandROITool/renderMethods.ts
- It includes
It just prevent doing calculation using camera when there is no camera/data full set yet
closes #198
=> fix: wrong ushape calculation when loading SR/freehand from server

packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/helpers/isRgbaSourceRgbDest.ts
This is a work around for the rgba flag not being set correctly and when we have rgba data but need rgb.
=> fix(rgba): Handle rgba to rgb conversion based on length

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/StackViewport.ts
While reading the API documentation on [`StackViewport.setZoom`](https://www.cornerstonejs.org/api/core/class/StackViewport#setZoom) I wanted to try out the `storeAsInitialCamera` parameter, but I noticed it wasn't working. Upon further inspection I realized it was due to the fact that, even though `Viewport.setCamera` has said parameter, `StackViewport` doesn't, so the the value is never passed down to the super class.
Please note that I purposely omitted the parameter from the call to `this.setCameraCPU` given that I believe it is not used anywhere. Not sure if this is the correct take though, so let me know if this requires further work.
=> fix: Add storeAsInitialCamera parameter to StackViewport setCamera

package.json, packages/tools/src/drawingSvg/drawTextBox.ts, packages/tools/src/tools/annotation/LengthTool.ts
On loading a DICOM SR, the length can be null, which causes a render issue.
There is still another issue on loading, which seems to render the image partially, and then doesn't complete, but this fix at least allows loading.
=> fix(Length):Throws NPE because length is set to null (race condition)

packages/tools/src/utilities/cine/playClip.ts
This line in the code causes CINE to be in an infinite loop and render the same frame over and over. It happens when you activate the CINE tool and you are on the last image of a series.
```
if (newImageIdIndex >= imageCount) {
newImageIdIndex = 0;
}
```
and since delta is ``` const delta = newImageIdIndex - stackData.targetImageIdIndex; ``` It causes it to go in the negative when it should always be 1 from my understanding.
```
if (newImageIdIndex !== stackData.targetImageIdIndex) {
const delta = newImageIdIndex - stackData.targetImageIdIndex;
viewport.scroll(delta, debounced, loop);
}
};
```
If you would like to replicate the issue, visit this study
https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170126083429.2
load any series and go to the last …
=> Issue : Cine infinite rendering loop

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/RenderingEngine.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/vtkClasses/vtkOffscreenMultiRenderWindow.js, packages/core/src/RenderingEngine/vtkClasses/vtkSharedVolumeMapper.js, packages/core/src/cache/cache.ts, packages/core/src/cache/classes/ImageVolume.ts, packages/core/src/types/IImageVolume.ts, packages/core/src/volumeLoader.ts, packages/streaming-image-volume-loader/src/StreamingImageVolume.ts, packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts
This fixes some of the memory issues in which vtk's render window interactor was not unsubscribing from one of its events. 
Right now memory profiling in Chrome does not show any noticeable objects left for decaching but still the demos keep some GPU process. 
We might want to investigate more on this
=> fix: fixes the memory leak for volumes

packages/tools/src/utilities/getAnnotationNearPoint.ts
When the frame of reference UID is common between series, and two markups happen to coincide on different images, the first one found will be select for nearby tool data, thus updating and setting values for the wrong annotation.
=> fix(annotation):The wrong annotation was being selected for common frameUID

packages/core/src/RenderingEngine/VolumeViewport.ts
When using this method while being on the first image, the index returns 0, and this method would return `undefined`. This is unwanted since the first image obviously has a 0 index which is usable. My fix simply consists of ensuring the returned value is a number (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN).
=> Fix issue when getting an index that equals 0.

common/reviews/api/tools.api.md, packages/tools/src/drawingSvg/drawLine.ts, packages/tools/src/drawingSvg/drawRect.ts, packages/tools/src/stateManagement/annotation/FrameOfReferenceSpecificAnnotationManager.ts, packages/tools/src/stateManagement/annotation/annotationState.ts, packages/tools/src/stateManagement/index.js, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts
adding data-id attribute to svg elements for e2e frameworks to be able to select and tests annotations
=> feat: add data-id to some svg elements for e2e tests - need to add more

packages/core/examples/stackEvents/index.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/tools/src/utilities/math/polyline/getSubPixelSpacingAndXYDirections.ts, packages/tools/src/utilities/planar/getWorldWidthAndHeightFromCorners.ts, packages/tools/src/utilities/planar/getWorldWidthAndHeightFromTwoPoints.ts, packages/tools/src/utilities/pointInSurroundingSphereCallback.ts, utils/demo/helpers/camera/getRandomlyTranslatedAndZoomedCameraProperties.js
=> fix: viewRight was calculated wrong for tools

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/types/ICamera.ts, packages/core/src/types/IVolumeViewport.ts, packages/core/src/utilities/hasNaNValues.ts, packages/core/src/utilities/index.ts, packages/tools/examples/resetCamera/index.ts, packages/tools/test/segmentationState_test.js, utils/ExampleRunner/example-info.json
- Refactored reset camera to use the setCamera (previous bug where resetting volumes where not updating camera because of clipping planes)
- Added resetToCenter parameter to enable optional keeping the slice and just reseting the slice for volumes in any planes
Try example: https://deploy-preview-269--cornerstone-3d-docs.netlify.app/live-examples/resetcamera
=> feat: reset to center option for reset camera

packages/core/src/RenderingEngine/Viewport.ts, packages/core/test/stackViewport_gpu_render_test.js
This PR fixes the flipping of the volumes by implementing it through camera api instead of actor
Try it out, it works on oblique too 🎉  https://deploy-preview-271--cornerstone-3d-docs.netlify.app/live-examples/volumeapi
=> feat: flip viewports via camera api instead of actor

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/constants/epsilon.ts, packages/core/src/constants/index.ts, packages/tools/examples/crossHairs/index.ts, packages/tools/src/utilities/planar/filterAnnotationsWithinSlice.ts, packages/tools/src/utilities/viewportFilters/filterViewportsWithParallelNormals.ts, packages/tools/src/utilities/viewportFilters/getViewportIdsWithToolToRender.ts, packages/tools/src/utilities/viewportFilters/index.ts, packages/tools/test/segmentationState_test.js
- resetViewport was broken after the new flip implementation
- tool rendering were broken since we were filtering based on the orientation which is not logical with the new flip via camera API
=> fix: resetCamera and annotations for flipped viewports

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/RenderingEngine.ts
resize api has changed from 
`reneringEngine.resize(immediate, resetPan, resetZoom)`
to 
`reneringEngine.resize(immediate, keepCamera)` with keep Camera default to true
=> fix: rendering engine should not reset camera on resize

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/index.ts, packages/core/src/metaData.ts, packages/core/src/utilities/calculateViewportsSpatialRegistration.ts, packages/core/src/utilities/index.ts, packages/core/src/utilities/spatialRegistrationMetadataProvider.ts, packages/tools/src/store/SynchronizerManager/Synchronizer.ts, packages/tools/src/synchronizers/callbacks/stackImageSyncCallback.ts, packages/tools/src/synchronizers/index.ts, packages/tools/src/synchronizers/synchronizers/createStackImageSynchronizer.ts, packages/tools/src/synchronizers/synchronizers/index.ts, packages/tools/test/synchronizerManager_test.js
Add stack synchronization for stack viewports. This works for viewports in the same frame of reference and viewports that are not in the same frame of reference 
Make the synchronizer callbacks async
=> feat: add stack synchronization within or across studies

packages/tools/src/store/SynchronizerManager/Synchronizer.ts
This was mistakenly changed to async
=> fix: revert synchronizer event firing being unnecessary async

packages/core/src/utilities/worldToImageCoords.ts
There are lots of cases where world to image should allow producing coordinates outside the image.  Make the exception optional.
=> fix(conversion):World to image throws an exception on outside image

packages/core/src/RenderingEngine/StackViewport.ts
handle the case when image has no pixel spacing and  image data use default spacing.
=> don't reset display pipeline when spacing is missing

packages/tools/src/tools/ZoomTool.ts
- Added spacing parameter presets of [1, 1, 1] for cases where the viewport does not have imageData, such as for loading PolyData where actors are added directly to viewport
- Fixed issue with polyData actor rescaling while zooming, min/max zoom scale only applies when there is imageData
=> fix: ZoomTool fix for polyData actors with no imageData

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
Closes #307: if planar annotation is not visible, filter it.
=> Hide PlanarFreehandROITool annotations

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
=> Filter PlanarFreeHandROI annotations based on parallel normals instead of equal normals.

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, package.json, packages/core/src/utilities/index.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, utils/ExampleRunner/example-info.json
Fix the following weird behaviours for bidirectional tool when short and long axis change (try https://deploy-preview-309--cornerstone-3d-docs.netlify.app/live-examples/stackannotationtools)
[5fc67b84-79c0-415b-aede-7cd724a73a33.webm](https://user-images.githubusercontent.com/7490180/203677775-f960f388-8d8e-41b8-928d-60b0248ad99c.webm)
[e304e93d-6386-40ae-88d3-8503e4dd362f.webm](https://user-images.githubusercontent.com/7490180/203677778-ae956de5-ec21-46f0-b22c-eedf940f9bc3.webm)
=> fix: bidirectional tool when short and long axis changes

packages/core/src/RenderingEngine/VolumeViewport.ts
While trying to get the volume from the cache, it can be undefined so getting the scaling attribute would throw an error in that case. This is a quick fix
=> fix(volumeViewport): Add optional scaling as the volume can be undefined

packages/tools/src/drawingSvg/getSvgDrawingHelper.ts
Related issue : https://github.com/cornerstonejs/cornerstone3D-beta/issues/252#issue-1416549311
if getSvgDrawingHelper is not a generic and will not be used for any other purpose, this code will solve the problem.
=> fix: Use queryselector instead of firstChild to get svg-layer

common/reviews/api/tools.api.md, packages/tools/examples/basicSegmentationTools/index.ts, packages/tools/src/index.ts, packages/tools/src/store/ToolGroupManager/ToolGroup.ts, packages/tools/src/store/state.ts, packages/tools/src/tools/base/BaseTool.ts, packages/tools/src/tools/index.ts, packages/tools/src/tools/segmentation/BrushTool.ts, packages/tools/src/tools/segmentation/PaintFillTool.ts, packages/tools/src/tools/segmentation/strategies/eraseCircle.ts, packages/tools/src/tools/segmentation/strategies/eraseSphere.ts, packages/tools/src/tools/segmentation/strategies/fillCircle.ts, packages/tools/src/types/FloodFillTypes.ts, packages/tools/src/types/IToolClassReference.ts, packages/tools/src/types/IToolGroup.ts, packages/tools/src/types/index.ts, packages/tools/src/utilities/segmentation/brushSizeForToolGroup.ts, packages/tools/src/utilities/segmentation/brushThresholdForToolGroup.ts, packages/tools/src/utilities/segmentation/floodFill.ts, packages/tools/src/utilities/segmentation/index.ts, packages/tools/src/utilities/segmentation/utilities.ts, utils/ExampleRunner/template-config.js, utils/ExampleRunner/template-multiexample-config.js
https://deploy-preview-327--cornerstone-3d-docs.netlify.app/live-examples/basicsegmentationtools
There are various scenarios that we want to use the same tool but with different strategy (segmentation brush can be threshold brush, eraser, simple brush, sphere brush etc.). 
```
public addToolInstance(
toolName: string,
parentClassName: string,
configuration = {}
): void {
```
- Erase Circle 
- Erase Sphere
- PaintFill Tool
PS: Kudos to @JamesAPetts for this awesome piece of work
=> feat: enable having multiple instances of the same tool and add more seg tools

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/examples/volumeViewport3D/index.ts, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/RenderingEngine.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport3D.ts, packages/core/src/RenderingEngine/helpers/addVolumesToViewports.ts, packages/core/src/RenderingEngine/helpers/setVolumesForViewports.ts, packages/core/src/RenderingEngine/helpers/viewportTypeToViewportClass.ts, packages/core/src/RenderingEngine/helpers/volumeNewImageEventDispatcher.ts, packages/core/src/RenderingEngine/index.ts, packages/core/src/constants/index.ts, packages/core/src/constants/viewportPresets.ts, packages/core/src/enums/ViewportType.ts, packages/core/src/index.ts, packages/core/src/types/ViewportPreset.ts, packages/core/src/types/index.ts, packages/core/src/utilities/applyPreset.ts, packages/core/src/utilities/index.ts, packages/tools/examples/volumeViewport3D/index.ts, packages/tools/src/utilities/segmentation/createLabelmapVolumeForViewport.ts, packages/tools/src/utilities/viewport/isViewportPreScaled.ts, utils/ExampleRunner/example-info.json
This pull request was originated from [this issue](https://github.com/cornerstonejs/cornerstone3D-beta/issues/267).
The existing `VolumeViewport` class was refactored and all common functionality was extracted to an abstract base class called `BaseVolumeViewport`. Then both the existing `VolumeViewport` class and the new `VolumeViewport3D` extend it.
Besides that, a new utility function was added to allow easily applying a preset to a viewport.
You can try it here https://deploy-preview-281--cornerstone-3d-docs.netlify.app/live-examples/volumeviewport3d
=> Add new 3D volume viewport

packages/tools/src/synchronizers/callbacks/areViewportsCoplanar .ts, packages/tools/src/synchronizers/callbacks/coPlanarViewports.ts, packages/tools/src/synchronizers/callbacks/stackImageSyncCallback.ts
In order to protect the stackImageSyncCallback from image sync problems, I suggest add an extra test that checks if the two viewports being considered has the same orientation. 
I add an extra function coPlanarViewports that checks if the viewPlaneNormal from the two viewports are parallel, by checking if the dot product is greater than 0.9
=> Add coplanar check in stackImageSync callback

packages/tools/src/tools/CrosshairsTool.ts
Hi,
Working on using cornerstone3d in a [Vite](https://vitejs.dev/) project, ran into an issue when running the project.
I think I have narrowed it down to a possibly circular dependency in [packages/tools/src/tools/CrosshairsTool.ts](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/tools/src/tools/CrosshairsTool.ts) when importing `liangBarksyClip`
Happy to provide an example minimal repository with the error to verify.
Console error
```
cornerstonejs.bd843ac7.js:18089 Uncaught ReferenceError: Cannot access 'index' before initialization
at cornerstonejs.bd843ac7.js:18089:29
```
with `index` being 
```
...
const { RENDERING_DEFAULTS } = CONSTANTS;
const { liangBarksyClip } = index;
function defaultReferenceLineColor() {
return "rgb(0, 200, 0)";
}
...
```
=> fix: could not access 'index' before initialization

packages/tools/src/tools/annotation/AngleTool.ts
AngleTool will be broken after annotation cancellation, because it tries to get the `annotationId` of a non-existing annotation.
Fixed this issue by setting `angleStartedNotYetCompleted` to false upon cancellation.
=> fix: AngleTool not working after cancellation

packages/core/src/RenderingEngine/StackViewport.ts
flip the useRGBA in StackViewport to true in the CPU path as discussed here: https://github.com/cornerstonejs/cornerstone3D-beta/issues/338
=> fix: colored images using rgba in CPU rendering #338

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, packages/core/src/enums/SharedArrayBufferModes.ts, packages/core/src/enums/index.ts, packages/core/src/index.ts, packages/core/src/init.ts, packages/core/src/utilities/createFloat32SharedArray.ts, packages/core/src/utilities/createUint8SharedArray.ts, packages/streaming-image-volume-loader/src/StreamingImageVolume.ts, packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts, packages/streaming-image-volume-loader/test/StreamingImageVolume_test.js, utils/ExampleRunner/example-runner-cli.js
This feature allows for volumes to be loaded even if the page is not cross origin isolated.
For some use cases such as running cornerstone3D in cordova or mobile webview this is required.
=> feat: option to use Arraybuffer for volume loader instead of sharedArrayBuffer

packages/tools/src/store/ToolGroupManager/ToolGroup.ts
It was not possible to add bindings on a tool with same mouseBinging but different modifier keys. You can now create the follwing tool configuration:
```js
toolGroup.setToolActive(toolName, {
bindings: [
{
mouseButton: MouseBindings.Primary, // Left Click
},
{
mouseButton: MouseBindings.Primary,
modifierKey: KeyboardBindings.Shift,
},
],
});
```
=> fix: tool bindings with different modifier keys

packages/core/src/RenderingEngine/StackViewport.ts
For a GPU reset, start by resetting the flips and rotation (via viewUp) because the ordering of the various flips and rotations that have been applied is not known.
=> fix(StackViewport): Reset camera bug when rotation happens on StackViewport

packages/tools/src/eventListeners/mouse/mouseDownListener.ts
moved the mouse click/down timeout detection into _doMouseDown where the actual mouse down event is fired.
=> fix(doubleClick): click events are not being propagated at all

packages/tools/src/store/removeEnabledElement.ts
We use nativeElement for rendering an element (enabledElement) that contains overlayboxes as well as some other components. While querying for the svg-layer during the remove element, we are having problems using these properties because it searches under the wrong element. I investigated our repository issues and found it looks like #252.
=> fix(svg): find and reset svg-layer within the correct element

common/reviews/api/tools.api.md, packages/tools/examples/scaleOverlayTool/index.ts, packages/tools/src/index.ts, packages/tools/src/tools/ScaleOverlayTool.ts, packages/tools/src/tools/index.ts, packages/tools/src/types/ToolSpecificAnnotationTypes.ts, utils/ExampleRunner/example-info.json
Displays a scale overlay on images to show the real world size. Scale can be positioned at the bottom, top, left or right side of the canvas. Scale size has been verified by using the length tool.
=> feat(ScaleOverlayTool): Add scale overlay tool

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/examples/stackAPI/index.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport3D.ts, packages/core/src/types/IViewport.ts
fix(StackViewport): #372 Removed both the Viewport.rotation and StackViewport.rotationCache properties.
Introduced an IViewport.getRotation for those viewports supporting rotation.
StackViewport.getRotation calculates the rotation from the camera properties.
Changed the StackAPI example to add buttons for constant absolute and delta rotations.
The StackAPI example now reports the current rotation and flips.
Various scenarios to test - also try permutations of each:
- rotation + flip + next image
- rotation + flip + reset
- rotation + flip + next image + absolute rotation
- rotation + flip + next image + delta rotation
- rotation + flip + delta rotation
=> feat(StackViewport): rework rotation for stack viewport

packages/adapters/package.json, packages/adapters/rollup.config.mjs, packages/adapters/src/adapters/Cornerstone/Angle.js, packages/adapters/src/adapters/Cornerstone3D/Angle.ts, packages/adapters/src/adapters/Cornerstone3D/Bidirectional.ts, packages/adapters/src/adapters/Cornerstone3D/CobbAngle.ts, packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts, packages/adapters/src/adapters/Cornerstone3D/PlanarFreehandROI.ts, packages/adapters/src/adapters/Cornerstone3D/RectangleROI.ts, packages/adapters/src/adapters/Cornerstone3D/index.ts, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts
Add additional adapters for Rectangle, Angle, PlanarFreehand
Fix the generated DICOM so it included all the patient/study attributes so it doesn't fail to send against a validating PACS.  This is a critical bug in that the generated DICOM was missing the Patient ID attribute, and thus would fail to store on any DICOM compliant PACS back end.
=> feat(adapters): Add adapters for Rectangle, Angle and fix generate DICOM

packages/tools/src/tools/TrackballRotateTool.ts
Fixed issue with TrackballRotateTool on 3D viewports where the image was being rotated about the incorrect axis when dragging the cursor along the x-axis of the canvas.
**Old TrackballRotateTool**
**Fixed TrackballRotateTool**
=> fix(trackball): rotate was wrong on mouse drag

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/examples/stackVoiSigmoid/index.ts, packages/core/examples/volumeVoiSigmoid/index.ts, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/enums/VOILUTFunctionType.ts, packages/core/src/enums/index.ts, packages/core/src/types/EventTypes.ts, packages/core/src/types/IImage.ts, packages/core/src/types/IVolumeViewport.ts, packages/core/src/types/Metadata.ts, packages/core/src/types/StackViewportProperties.ts, packages/core/src/types/VolumeViewportProperties.ts, packages/core/src/utilities/createLinearRGBTransferFunction.ts, packages/core/src/utilities/createSigmoidRGBTransferFunction.ts, packages/core/src/utilities/getVoiFromSigmoidRGBTransferFunction.ts, packages/core/src/utilities/index.ts, packages/streaming-image-volume-loader/src/StreamingImageVolume.ts, packages/streaming-image-volume-loader/src/helpers/makeVolumeMetadata.ts, packages/tools/src/tools/StackRotateTool.ts, packages/tools/src/tools/WindowLevelTool.ts, utils/ExampleRunner/example-info.json
- CPU fallback is unimplemented
=> feat(voi): added support for sigmoid voiLUTFunction for StackViewport and VolumeViewport

packages/tools/examples/doubleClickWithStackAnnotationTools/index.ts, packages/tools/src/eventListeners/mouse/index.ts, packages/tools/src/eventListeners/mouse/mouseDownListener.ts, packages/tools/src/init.ts
CS3D issue #375
Testing notes...
1. Run the `doubleclickwithstackannotationtools` example.
2. Open the browser dev tools.
3. In the Sources' tab of the browser dev tool, Ctrl+P to open the mouseDownListener.ts file.
4. Place a break point in the `mouseDoubleClickIgnoreListener` function inside the `if (doubleClickState.ignoreDoubleClick) {` block (see below).
```
export function mouseDoubleClickIgnoreListener(evt: MouseEvent) {
if (doubleClickState.ignoreDoubleClick) {
// breakpoint/debugger here
doubleClickState.ignoreDoubleClick = false;
...
```
5. Single click on the viewport element image (i.e. to start a markup).
6. Now move the mouse to the right, outside of the viewport element and double click.
7. The breakpoint added should NOT be hit.
The same test should be tried with the …
=> fix(doubleClick): mouseDoubleClickIgnoreListener is now added to each viewport element instead of the document element

packages/adapters/package.json, packages/adapters/src/adapters/Cornerstone3D/EllipticalROI.ts, packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts, packages/adapters/src/adapters/Cornerstone3D/isValidCornerstoneTrackingIdentifier.ts
This changes the release module just a tiny bit, with the impact that with yarn link, the typescript files are directly debugged, while with regular yarn install, the es module is used.
=> fix(adapters): Update the build a little to allow debugging into typescript

packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts
Simple fix to allow loading measurements even if it throws an exception on one measurement.
=> fix(adapters): Measurement reports can throw exceptions that prevent loading

common/reviews/api/tools.api.md, packages/tools/src/utilities/dynamicVolume/getDataInTime.ts, packages/tools/src/utilities/dynamicVolume/index.ts, packages/tools/src/utilities/index.ts
**Feature**
- using either a coordinate or segmentation Id, gets the scalar data for each voxel requested for a provided series of time points, or if left blank, for all time points
- scalar data is returned as an array for a coordinate, and an array of arrays for a segmentation
=> feat(4d utility): getDataInTime from 4D data

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/core/src/utilities/getTargetVolumeAndSpacingInNormalDir.ts, packages/tools/src/types/JumpToSliceOptions.ts, packages/tools/src/utilities/cine/playClip.ts, packages/tools/src/utilities/scroll.ts, packages/tools/src/utilities/viewport/jumpToSlice.ts
On attempting to scroll a second frame of reference series against the original series, the scrolling failed to display.
Also fix a NPE on turning off CINE related to segmentation.
=> fix(scroll): Scrolling failed to find the volume with segmentation

common/reviews/api/tools.api.md, packages/tools/src/stateManagement/segmentation/config/segmentationVisibility.ts, packages/tools/src/tools/displayTools/Contour/contourDisplay.ts, packages/tools/src/tools/displayTools/Labelmap/labelmapDisplay.ts, packages/tools/src/tools/displayTools/SegmentationDisplayTool.ts, packages/tools/src/types/SegmentationStateTypes.ts, packages/tools/test/segmentationState_test.js, packages/tools/test/segmentationVisibilityController_test.js
Previously when segmentation was set as hidden the actor was set as hidden and as a result you could not do use cases such as hide all, then unhide one. 
The problem was as a result of having two states (visibility and segmentsHidden), this PR will make them as one (only segmentsHidden) and visibility becomes a getter only
=> fix(segmentation): segmentation could not render segment while invisible

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/types/StackViewportProperties.ts
The voiUpdatedWithSetProperties value was getting lost if you did a get/set properties, causing some series to display weirdly afterwards.  This change preserves the value in the get/set properties.
=> fix: Preserve the voi lut set attribute in properties

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/helpers/createVolumeActor.ts, packages/core/src/RenderingEngine/helpers/setDefaultVolumeVOI.ts, packages/core/src/loaders/volumeLoader.ts, packages/core/src/utilities/loadImageToCanvas.ts, packages/docs/package.json, packages/streaming-image-volume-loader/package.json, packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts, packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts, yarn.lock
We introduced optional 16 bit texture support in the previous pr [here](https://github.com/cornerstonejs/cornerstone3D-beta/pull/420), but because of scaling issues in PT, the images were casted to int/uint 16 while they should still be Float. 
These changes will get reverted back once we merge the dicomImageLoader which properly handles scaling
FYI @Ouwen
=> fix(rendering): should still use Float32 when not 16 bit for scaling issues

common/reviews/api/core.api.md, packages/core/src/loaders/volumeLoader.ts, packages/core/src/utilities/getSliceRange.ts, packages/core/src/utilities/getTargetVolumeAndSpacingInNormalDir.ts
If a segmentation is created with a much larger range than one of the display sets it applies to, then that display set is shown with large swathes of black, and the scrolling can be wrong because it uses the finer of the two scrolls, which can end up duplicating base images.
This change uses primary volumes, which it determines by those having a volume image loader prefix, for slice range, and only uses secondary volumes when there are no primaries.
=> fix: Segmentation slice range is wrong when nearly orthonormal as well as for segmentation volumes

packages/core/src/utilities/getSliceRange.ts
The actual EPSILON value didnt resolve the problem. We are using a much lower value so the fix already implemented in this current file could execute
=> Changing the value of the EPSILON in getSliceRange.ts file

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/types/IStreamingVolumeProperties.ts, packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts, packages/streaming-image-volume-loader/src/cornerstoneStreamingDynamicImageVolumeLoader.ts, packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts
we shouldn't hold texture update from happening in load, just in cancel
=> fix(volumeLoad): should still update texture when loading

packages/tools/src/utilities/cine/playClip.ts, packages/tools/src/utilities/planar/filterAnnotationsWithinSlice.ts
Added a computation for the image normal when an annotation is missing the normal vector.
=> fix(tools): Some older annotations were missing normal

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/cache/classes/ContourSet.ts, packages/core/src/types/IContourSet.ts, packages/tools/examples/contourRenderingConfiguration/index.ts, packages/tools/src/stateManagement/segmentation/removeSegmentationsFromToolGroup.ts, packages/tools/src/tools/displayTools/Contour/addContourSetsToElement.ts, packages/tools/src/tools/displayTools/Contour/contourConfig.ts, packages/tools/src/tools/displayTools/Contour/contourDisplay.ts, packages/tools/src/tools/displayTools/Contour/updateContourSets.ts, packages/tools/src/tools/displayTools/Contour/utils.ts, packages/tools/src/types/ContourTypes.ts
Improved performance for updating contours and centroid calculations
To test: run https://deploy-preview-543--cornerstone-3d-docs.netlify.app/live-examples/contourrenderingconfiguration
- refactor: Update contour rendering default configuration & remove console.debug call
- perf: Optimize getting and setting vtk polydata for contour sets
- refactor(displayTools): optimize contour sets rendering with segment specific configs
- refactor: Remove redundant code for Contour display tools
- feat: add computation for centroid of the contour set
- refactor: simplify centroid calculation for better contour rendering
=> feat(contour): improved performance and better configuration

packages/core/src/init.ts
Simplify condition to check if the context object is an instance of a WebGLRenderingContext or WebGL2RenderingContext in "init.ts"
=> fix(init): should only check gl context and not extensions

common/reviews/api/tools.api.md, packages/dicomImageLoader/src/shared/scaling/scaleArray.ts, packages/streaming-image-volume-loader/src/helpers/scaleArray.ts, packages/tools/src/tools/annotation/CircleROITool.ts, packages/tools/src/tools/annotation/DragProbeTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/base/AnnotationTool.ts, packages/tools/src/utilities/getModalityUnit.ts, utils/test/testUtilsImageLoader.js
Currently PT images that are **not** in SUV are not rescaled at all. This is problematic because PT images can be in units of e.g. counts or Bq/ml, so it's important that the rescaling is applied in those cases.
=> fix(suv display): fix scaling of non-SUV PT images

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/examples/programaticPanZoom/index.ts, packages/core/src/RenderingEngine/RenderingEngine.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/enums/Events.ts, packages/core/src/types/EventTypes.ts, packages/core/src/types/IViewport.ts, packages/core/src/types/ViewportInputOptions.ts, packages/core/src/types/displayArea.ts, packages/core/src/types/index.ts, packages/docs/docs/concepts/cornerstone-core/viewports.md
Adds initial display area to viewport.
`imageArea` takes a `imageX` and `imageY` which should be a number (0,1]  which determines the % of image to display.
`imageFocalPoint` takes a `focalX` and `focalY` which determines the camera focal point. `focalX=1` and `focalY=1` means the image is in the bottom right corner offscreen.  `focalX=0` and `focalY=0` refers to the upper left corner offscreen and `focalX=0.5` and `focalY=0.5` is the default center image. These numbers represent the XY translation amount as a % of the image width/height
The displayArea will save the stored camera and functions properly for stack viewport. The display area can also be programmatically set with or without saving the stored camera. One use case for programmatic display area setting is to automatically zoom …
=> feat: added display area to viewport

packages/tools/src/tools/CrosshairsTool.ts
Currently, the reference lines of the Crosshairs Tool may be wrongly clipped when the other viewports have a smaller size.
This PR aims to fix this issue by using the canvasBox of the current viewport instead of the other viewport for clipping lines.
=> fix(crosshairs): Reference lines are wrongly clipped

packages/tools/src/tools/CrosshairsTool.ts
Currently, `autopan` option of the CrosshairsTool is only working when using predefined orientations (Axial, Sagittal, Coronal). As soon as you rotate the axis, autopan may cause an infinite loop. This PR aims to fix that, changing the implementation to use the canvas context.
In case you want to reproduce the issue, you can:
1. Add ZoomTool or PanTool to the crosshairs example
2. Enable autopan to the example
3. On the example, apply pan or zoom to one of the non main views
4. Rotate the axis 
5. Select a point in the main view that's out of the viewpoint in one of the other views.
=> fix(crosshairs): Autopan causing infinite loop

packages/tools/src/eventListeners/mouse/mouseDownListener.ts
The double click check was occurring for right click, delaying context menus appearing.
=> fix(mouse): Avoid the delay on double click checking for right click

packages/tools/src/tools/CrosshairsTool.ts
Currently, the gap between the reference lines depends on the size of the canvas, causing it to be variable. This means that when working on large viewports, the gap could be too large. Moreover, there's no consistency if all viewports don't have the same size.
This PR proposes to have a fixed and configurable gap size. Moreover, it aims to improve position of the controls to prevent them from being out of view depending on the proportion of the canvas. As you can see, depending on the size of the canvas, the controls may be out of view. 
Current:
Proposal:
You can check the proposal on the `crosshairs` example. Let me know your feedback.
=> feat(crosshairs): Make the reference lines gap configurable

common/reviews/api/streaming-image-volume-loader.api.md, packages/streaming-image-volume-loader/src/helpers/getDynamicVolumeInfo.ts, packages/streaming-image-volume-loader/src/helpers/index.ts, packages/streaming-image-volume-loader/src/index.ts, packages/tools/examples/stackManipulationTools/index.ts, packages/tools/src/utilities/cine/playClip.ts
- cine is checking if there are any 4D volume loaded on a viewport instead of checking only if the default actor is a 4D series because when there are PT (4D) + CT (3D) it has to play as 4D series otherwise it can get into a state where some PT viewports plays as 4D and PT/CT viewports plays as 3D moving the 4D series in time and space at the same time.
- added getDynamicVolumeInfo that is being used by the Viewer to check if a series is a 4D series. That is the same method used when a 4D series is loaded by Cornerstone.
=> feat(4D): fixed cine play issue and added getDynamicVolumeInfo method

packages/tools/examples/modifierKeys/index.ts, packages/tools/src/eventDispatchers/shared/getActiveToolForMouseEvent.ts, packages/tools/src/eventDispatchers/shared/getActiveToolForTouchEvent.ts, packages/tools/src/eventDispatchers/shared/getMouseModifier.ts, packages/tools/src/eventListeners/mouse/mouseDownListener.ts
Changed the double click handling to correctly handle the button click for double click selection as well as for context menu click selection.
Made the wheel scrolling go through the existing event handling by adding a new
namedEvent property to allow binding on the wheel specifically in the normal way rather than needing custom handling to control the binding.
Test by running the modifierKey example, and the doubleClickWithStackAnnotationTools examples.
`yarn example doubleClickWithStackAnnotationTools`
http://localhost:3000
=> fix: Double click and multi-key bindings

packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts, packages/tools/examples/stackToVolumeWithAnnotations/_setViewports.ts, packages/tools/examples/stackToVolumeWithAnnotations/index.ts
This commit adds functionality to cache image load object when it
has not already been loaded into the cache. This optimizes the
process of loading images.
fixes the viewport type change example.
=> feat(streaming-image-volume): add caching for image load object

packages/docs/package.json, utils/ExampleRunner/example-runner-cli.js, utils/ExampleRunner/template-config.js
This commit updates the docs package.json to use the latest version of cornerstonejs/tools (v0.66.0) that provides an improved feature set. In addition, changes have been made to the example-runner-cli.js and template-config.js files so that the dicomImageLoader webpack build process runs without unexpected behavior while building the example runner.
=> feat(docs): update cornerstonejs/tools to v0.66.0 & change dicomImageLoader webpack build process

packages/core/src/RenderingEngine/RenderingEngine.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/tools/src/tools/CrosshairsTool.ts, packages/tools/src/tools/StackScrollToolMouseWheelTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/utilities/scroll.ts
- feat(stackViewport): better error handling for disabled viewports
- some fix in crosshair
Run stackManipulationTools example locally
after setStack
re-enable the element 
and setStack again
- You have lost the scroll, but with these changes it will throw since that is what has happened
=> fix(stackViewport): better error handling for disabled viewports

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/types/IStackViewport.ts, packages/core/src/utilities/getImageLegacy.ts, packages/core/src/utilities/index.ts
See issue #390
Testing:
Test A: 
1. Run the basic stack viewport example.
2. Open the browser's dev tools.
3. In the browser console get the viewport element for the image displayed and assign it to a variable - say `viewportElement`.
4. In the browser console issue the command `cornerstone.utilities.getImageLegacy(viewportElement)`
5. The corresponding `IImage` object should be returned.
Test B: 
1. Run the basic volume viewport example.
2. Open the browser's dev tools.
3. In the browser console get the viewport element for the image displayed and assign it to a variable - say `viewportElement`.
4. In the browser console issue the command `cornerstone.utilities.getImageLegacy(viewportElement)`
5. An exception to the following should be output...
```
getImageLegacy.ts:21 Uncaught Error: …
```
=> fix(utilities): added getImageLegacy for migrations of cornerstone legacy's getImage

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/types/CPUFallbackEnabledElement.ts, packages/core/src/types/CPUIImageData.ts, packages/core/src/types/IImage.ts, packages/core/src/types/ImagePixelModule.ts, packages/core/src/types/ImagePlaneModule.ts, packages/core/src/types/PixelDataTypedArray.ts, packages/core/src/types/index.ts, packages/dicomImageLoader/src/imageLoader/colorSpaceConverters/convertPALETTECOLOR.ts, packages/dicomImageLoader/src/imageLoader/getImageFrame.ts, packages/dicomImageLoader/src/types/ImageFrame.ts, packages/tools/src/utilities/cine/playClip.ts, utils/ExampleRunner/example-info.json
CPU rendering if it is switched after the initial setup would fail to use renderToCanvas.
- Fixed the CPU rendering to use the correct rendering function
- refactor some types
- make pallet color to use metadata to fetch if needed
1. go to https://v3-demo.ohif.org/localbasic
2. open console and say `cornerstone.setUseCPURendering(true)` 
3. drag and drop a dicom
4. thumbnail would not load
etc.)
- [] The …
=> fix(cpu): could not render if switched to cpu in the middle

packages/dicomImageLoader/.webpack/webpack-dynamic-import-debug.js, packages/dicomImageLoader/src/imageLoader/createImage.ts
We were double scaling for getting the window level and center when the voiLutModule does not contain it
Use the AfterScale min and max (which is the same as before scale if scaling doesn't happen)
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix(windowLevel): should not double scale for window level

packages/core/examples/volumeViewport3D/index.ts, packages/core/examples/volumeViewport3D/tf_ui/TF_panel.ts, utils/ExampleRunner/template.html
Fixed the position of the toolitp to the top-left and added transparency to its background.
Clamped the anchor point such that no portion of it goes beyond the canvas bounds.
Prevent deletion of control points when only two remain.
Control endpoint tooltips added. They are shown on anchor hover and drag.
Added a control point tooltip when hovering and movig a control point.
Update the TF_widget anchor whenever a control point gets deleted.
Updated histogram colours.
Moved context menus to document.body so that they are not clipped by the TF_panel.
Added a div (with css class name 'control-point-tooltip-parent') containing the control point tooltips for each separate TF_widget. This simplifies showing/hiding the tooltips on a per TF_widget basis.
=> feat(transfer function editor): various improvements and fixes

packages/dicomImageLoader/src/imageLoader/createImage.ts, packages/dicomImageLoader/src/shared/decodeImageFrame.ts, packages/dicomImageLoader/src/types/DICOMLoaderImageOptions.ts, packages/docs/docusaurus.config.js, packages/docs/package.json
SAB requires a secure context, and stack viewport can work without it (although MPR still needs a secure context https and CORS headers to work), but this will solve making the viewer actually work in the stack viewport at least.
https://community.ohif.org/t/dicom-images-infinite-loading/831/2?u=jbocce
Check for SAB before using it 
Run viewer against an unsecure context (localhost is secure by design), run it against an ip
etc.) …
=> fix(sab): check for sab before using it

package.json, packages/core/package.json, packages/tools/package.json, packages/tools/src/tools/MIPJumpToClickTool.ts
The MIP jump to image on click tool directly used viewportId's, but these aren't stable in CS3D because they get updated when the viewport gets a new display set or changes size in certain ways.  Instead, this tool is switched to use a new concept pt axial
Added viewport categories to the viewport options and a getViewportsInCategory to allow getting all the categorized viewports.  That allows getting a set of viewports by some common condition.
Run the updated OHIF build containing the settings for the viewport categories or run the mipJumpToClick example
On mipJumpToClick, use the right panel to click on to navigate
- [] My code has been well-documented (function documentation, …
=> fix: MIP jump to image click

packages/tools/src/tools/annotation/AngleTool.ts
In the angle tool the label for degrees is not linked to the vertex of the angle... this can be confusing as the line that links to the label is similar to the lines of the angle and it can appear that you've drawn some other shape rather than an angle.
Now by default, the textbox line is linked to the vertex, and it will stay that way unless the text box is specifically moved by the user so that they still have that option if they want it.
Before:-
After:-
- Go to the examples directory in the repo
- Use the double click with stack annotations tool example to test the angle tool
etc.)
=> link textbox to vertex unless moved by user

packages/dicomImageLoader/src/imageLoader/wadouri/getUncompressedImageFrame.ts
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/454
Seems like for multiframe in wadouri, there is a huge performance problem and sometimes a out of memory in windows. It is solved by copying only the portion of the data that is needed to the worker.
There might be an optimization using SharedArrayBuffer to get the view out of the original buffer without copy but we will take a look into that later
Try the `local` example with this data https://github.com/emelalkim/sampledata/releases/tag/large_multiframe
etc.)
- [] I have run the `yarn build:update-api` to update the API documentation, …
=> fix(multiframe): transfer only portion of data for multiframe to worker

packages/tools/src/tools/annotation/ArrowAnnotateTool.ts
Here is an example where the dashed line connecting the annotation Arrow Head extends over the ROI... it gives the impression this is part of the annotation line and can cause confusion and also could obstruct the ROI. In this case, the label also obstructs the ROI.
Workaround would be deleting and re-drawing the annotation with a different tail direction and HOPE that label and dashed line are positioned differently.
@sedghi
Now by default, the textbox line is linked to the opposite side of the arrowhead, and it will stay that way unless the text box is specifically moved by the user so that they still have that option if they want it.
Before:-
After:-
- Go to the examples directory in the repo
- Use the double click with stack annotations tool example to test the annotation tool …
=> Annotation Label - dashed label indicator position can obstruct ROI

packages/tools/src/tools/annotation/planarFreehandROITool/closedContourEditLoop.ts, packages/tools/src/tools/annotation/planarFreehandROITool/drawLoop.ts, packages/tools/src/tools/annotation/planarFreehandROITool/openContourEditLoop.ts
Fixed these bugs on PlanarFreehandROITool
- Cached stats are not re-calculated on modification.
- ANNOTATION_COMPLETED events are triggered when moving textbox.
=> fix PlanarFreehandROITool bugs

packages/core/src/RenderingEngine/StackViewport.ts, utils/test/testUtilsImageLoader.js
When the StackViewport's stack (series) has images that have different Photometric Interpretation, they would get rendered incorrectly. For example if there was 1 RGB image in a stack of Monochrome2 images, the RGB image would be rendered as if it is a Monochrome2 image.
Invalidate the stack if we find a mismatch between the PI of the previous and the new image. This will force recreation of the VTK imageData object.
Tested with various US studies that had few RGB images next to MONOCHROME2. 
etc.)
committed the changes …
=> fix invalidate stack if the next image is different PI 

packages/core/examples/stackBasic/index.ts, packages/core/src/RenderingEngine/StackViewport.ts
If the stack has multiple monochrome1 images, it cannot invert the images, and only the first image looks correct. Fixes https://github.com/cornerstonejs/cornerstone3D/issues/628
Also fixes https://github.com/cornerstonejs/cornerstone3D/issues/656 since web image loader does not have imageFrame
force recreate the transfer function if monochrome1 
etc.)
- [] The documentation page has been updated as necessary for …
=> fix(monochrome1): fix bug for monochrom1 inverted color

packages/dicomImageLoader/codecs/jpeg.js
There is an error in JPEG.js class when tring parsing JPEG image, the object prototype of this class is assigned using constructor.prototype but apparently this assign is not working in Javascript newer versions, the best way to use it is using Object.setPrototypeOf as mdn post [MDN Prototype Post](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain).
When I was implementing a wadouri image download, the following error was shown:
[Error Image](https://imgur.com/DnKJrk7)
[Line Error Image](https://imgur.com/uaY0z2V)
- Change the way of assign the prototype of the object.
What are the effects of this change?
- Before vs After
- Before: 
[Before](https://imgur.com/xsxXfCM)
- After:
[After](https://imgur.com/TmAEDG2)
- Using Wadouri Legacy test
- …
=> fix(dicomImageLoader): Error when loading Wadouri JPEG Image

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/types/EventTypes.ts, packages/tools/src/synchronizers/callbacks/voiSyncCallback.ts
- feat(invertSync): add invert sync to voi sync
- update api
add the invert to the voi sync since that should be also done 
edit the voiSyncCallback to add the invert
invert one of the viewports in an mpr and see all gets inverted
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> feat(invertSync): add invert sync to voi sync

packages/core/examples/webLoader/index.ts, packages/core/examples/webLoader/registerWebImageLoader.ts, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/helpers/createVolumeActor.ts, packages/core/src/loaders/volumeLoader.ts, packages/core/test/volumeViewport_gpu_render_test.js, packages/dicomImageLoader/src/shared/decodeImageFrame.ts, packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
Webloader was returning RGBA true which volume viewport could not handle. It is fixed now. Also the volume viewports color was not working either because of it is changed now to reflect `setIndependentComponents(false)` . In addition streaming into the volume for color was not working since we had a short circute
- Modify webloader to be volumetric 
- add setIndependentComponents for color volume actor
- !isColorImage(imageFrame.photometricInterpretation) is not necessary in decdeImageFrame
yarn run example webloader 
should work now
https://deploy-preview-683--cornerstone-3d-docs.netlify.app/live-examples/webloader
- [] My code has been well-documented (function documentation, …
=> fix(color volume viewport): fix incorrect property on volume actor

packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/680 
we were not taking into account the number of components for the 8 bit volume 
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix(color volume): take into account number of components for the volume length

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/RenderingEngine.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/enums/RenderedState.ts, packages/core/src/enums/ViewportStatus.ts, packages/core/src/enums/index.ts, packages/core/src/types/EventTypes.ts, packages/core/src/types/IViewport.ts
Sometimes it is important to know if an initial render has occurred yet, but because of timing, it isn't possible to listen to rendered events.  Also, the image rendered event should include whether this was a real render, or an early render that just shows the background colour.
Added a renderedState enum and use it in the viewports to record the rendering state.
Run the OHIF integration tests:
https://github.com/OHIF/Viewers/pull/3540
Note this value can be used independently of OHIF, just there didn't seem to be immediate uses of it in the CS3D integration tests.
etc.) …
=> Have renderedState to store the status of whether an image has been rendered yet

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/enums/Events.ts, packages/core/src/types/EventTypes.ts, packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
Added IMAGE_VOLUME_LOADING_COMPLETED to make it possible to know when a volume is done loading
=> feat(streamingVolumeLoader): added IMAGE_VOLUME_LOADING_COMPLETED event

packages/core/package.json, packages/streaming-image-volume-loader/package.json, packages/tools/package.json
etc.)
- [] "OS: 
- [] "Browser:
=> chore(script): add a dev script which should be used for linking

common/reviews/api/tools.api.md, packages/tools/src/cursors/SVGCursorDescriptor.ts
`CursorSVG` had a implicit type that did not reflect, that cursors for new tool names can be added.
`registerCursor` can add any string as toolname to `CursorSVG`.
`svgCursorNames` has a similar problem. It only returns the initial cursor names.
Maybe it should be a function instead of a variable to return the current keys of `CursorSVG`. 
I did not changed it because I did not want to risk changing the public API on my first PR here. :)
`CursorSVG` has a broader type.
Small refactoring in `getDefinedSVGCursorDescriptor`. Should not affect functionality.
Only typing change. No change in runtime behavior.
etc.) …
=> fix(SVGCursorDescriptor): improve CursorSVG typing

common/reviews/api/tools.api.md, packages/dicomImageLoader/.webpack/webpack-base.js, packages/tools/src/store/SynchronizerManager/Synchronizer.ts, packages/tools/src/store/SynchronizerManager/createSynchronizer.ts, packages/tools/src/synchronizers/callbacks/voiSyncCallback.ts, packages/tools/src/synchronizers/synchronizers/createVOISynchronizer.ts, packages/tools/src/types/ISynchronizerEventHandler.ts
VOISyncCallback syncs the invert by default but for some scenarios it should be modifiable (tmtv mode sync between inverted PT and non inverted fusion)
adds an option to be able to turn off invert sync
tmtv mode right now is broken if you double click anywhere and go back it shows an inverted fusion
etc.)
- [] "OS: …
=> feat(voiSync): add optoins to turn of invert sync for voisync

common/reviews/api/tools.api.md, packages/tools/src/enums/Events.ts, packages/tools/src/store/ToolGroupManager/ToolGroup.ts, packages/tools/src/types/EventTypes.ts
Added an event that is triggered when a tool is activated to make it possible to the viewer detect any change to the active tool and update the UI showing a proper UI component (config)
=> feat(toolEvent): added an event that is triggered when a tool is activated

packages/dicomImageLoader/src/imageLoader/colorSpaceConverters/convertRGBColorByPlane.ts, packages/dicomImageLoader/src/imageLoader/convertColorSpace.ts, packages/dicomImageLoader/src/imageLoader/createImage.ts, packages/dicomImageLoader/src/imageLoader/decodeImageFrame.ts
Fixes #3354
The convertColorSpace function wasn't being called consistently or correclty for all situations.
According to the DICOM standard, as best I understand it:
1. The Photometric Interpretation (PMI) is used for uncompressed + RLE encodings
2. For colour images encoded in compressed syntaxes (JPEG, JPEG-LS, JPEG-LOSSLESS, JP2000, HTJ2K), the PMI and Planar Configuration are assumed to be whatever the decompressor provides - which is typically RGB, as the colour space is (usually) encoded in the image.  
This does NOT get 100% of images correct because there can be mismatches between what is encoded and decoded, however, it gets the majority of them correct, and it is really obvious when they are wrong.
Consistently use the RGB colour space as the output from compressed images, …
=> fix(color): Convert color space for useRGBA false

packages/core/examples/webLoader/hardcodedMetaDataProvider.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/getVOILut.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/renderColorImage.ts, packages/core/src/utilities/windowLevel.ts, packages/dicomImageLoader/src/imageLoader/createImage.ts
The DICOM standard specifies that the window center is offset by 0.5 and the width to be the count of unique values to map, rather than being (upper+lower)/2 and upper-lower respectively.  This was done to allow for integer values for most
standard window levels for an even number of instances.
Change the values for the range.
This is hard to test because the change is very subtle - very few images will change at all.  Suggest examining the TG-18 dataset (which is incorporated into the test dataset) for the mapping values being consistent.
etc.)
- [] I have run the `yarn build:update-api` to update the …
=> Fix an off by 0.5/1 error in window level calculations

packages/core/src/requestPool/requestPoolManager.ts
There's a bug when negative numbers are used for priorities in RequestPoolManager.
Fixed the sort compareFn to resolve the issue.
=> fix sorting priority groups

common/reviews/api/core.api.md, common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport3D.ts, packages/core/src/types/IVolumeViewport.ts
This adds the `resetProperties` method to the `VolumeViewport`. It behaves similarly to the one in `StackViewport`. This will be useful for usage in OHIF or other viewers to reset the view in MPR mode.
Added  `resetProperties` to the `VolumeViewport` class, now you can reset the properties for volume views.
- clone OHIF locally
- go to `commandModule.js`, in the `resetViewport` method, line 482, add `viewport.resetProperties()` [L478](https://github.com/OHIF/Viewers/blob/fe0ee050ed4236a8a4d58a23410f99165331605c/extensions/cornerstone/src/commandsModule.ts#L478)
- load any study, go into MPR view, modify the window level, then click the reset view tool, it should restore the window to the default value.
etc.)
committed the changes to this PR. (Read …
=> feat(VolumeViewport): Add reset properties to volume viewport

packages/core/examples/volumeAPI/index.ts, packages/core/src/cache/classes/ImageVolume.ts
purge cache was not freeing up memory since the deactivate texture calls had an exception which caused the scalardata to hang around
re-order the destroy calls
after
Before 
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix(memory leak): array buffer was sticking around because of exception

packages/tools/src/utilities/dynamicVolume/getDataInTime.ts
Since `segmentationVolume` is an `Uint8Array` and the type returned by a `map` function is exaclty the same which made  `indexArray` array to be an `Uint8Array` but that type of array may not have values greater than 255 breaking all pixel indexes returned.
=> fix(4D utility): wrong array type returned by getDataInTime

packages/tools/src/tools/annotation/AngleTool.ts
In the angle tool, if a user draws an angle where point 1, 2 or point 2,3 have the same coordinates, the calculated angle value will be NaN because it is impossible to calculate the angle. This causes the textbox not to be visible. It would be helpful to at least have the textbox say "Incomplete Angle" letting them know to adjust their points.
A better fix could be to prevent the creation of such invalid measurements and to prevent adjusting an existing angle to end up in that invalid state.
Modified the  _calculateCachedStats method to set the angle value to be "Incomplete Angle" instead of NaN if the value is NaN.
- visit -> [OHIF](https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2)
- the link above will already open a study. …
=> fix (angle tool): No text box if angle is incomplete/ value is NaN

common/reviews/api/streaming-image-volume-loader.api.md, common/reviews/api/tools.api.md, packages/tools/src/tools/displayTools/Labelmap/labelmapDisplay.ts, packages/tools/src/tools/displayTools/SegmentationDisplayTool.ts, packages/tools/src/utilities/segmentation/brushSizeForToolGroup.ts, packages/tools/src/utilities/segmentation/utilities.ts
etc.)
- [] "OS: 
- [] "Browser:
=> feat(brush size): enable specifying brush size for specific tool

packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts
If the viewport Grid has a stack and a volume of the same displaySet then the volume would not load complete for the bug this PR fixes. I don't know why we set the clearRequests for the stack prefetch
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix(Stack prefetch): should not remove other requests 

packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts
When using the `use16BitTexture` it will force every volume to be 16bit regardless of the fact that some may end up in float territory because of the scaling
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix(16bit float): should not use 16bit int for float arrays

packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts
stackPrefetch.disable currently checks on stackPrefetchData.data.length but stackPrefetchData doesn't have 'data'.
The most logical replacement seem to be 'indicesToRequest'. This issue blocks the cleaning of the poolManager queue.
Another call to 'data' exists in getPromiseRemovedHandler but at least won't generate an error.
Replaced 'data' with 'indicesToRequest'
- fix(prefetch): fix prefetch disable function.
etc.)
- [] "OS: Windows 11
- [] "Node version: …
=> fix(stackPrefetch): disable function not working

packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/CircleROITool.ts, packages/tools/src/tools/annotation/CobbAngleTool.ts, packages/tools/src/tools/annotation/DragProbeTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/displayTools/Contour/contourDisplay.ts
Cached stats are not getting recalculated when not actually calculated and null values solely exist in the various fields.
Added various null checkes.
etc.)
=> fix(measurements): Cached stats are now considered non-existent for various null or undefined attributes.

packages/core/src/RenderingEngine/StackViewport.ts
Fixes: #819 
When setting the camera in StackViewport.setRotationGPU, do not fire a CAMERA_MODIFIED event because it is already being done so in setRotation.
See #819. However, here are some brief details here...
1. Launch the Stack API example.
2. Open the browser console and enter the following snippet of code that will log the event fired.
```
var viewport = cornerstone.getRenderingEngines()[0].getViewports()[0];
viewport.element.addEventListener(cornerstone.EVENTS.CAMERA_MODIFIED, (e) => console.log(e)); 
```
3. Click any of the rotate buttons in the example.
4. The console should log a single event for each rotation button click.
etc.) …
=> fix(rotation): Only one CAMERA_MODIFIED event per rotation

packages/tools/src/tools/MagnifyTool.ts
Magnify Tool was Not Reflecting changes to viewport properties like If the image was rotated or colours inverted
added all properties of viewport to magnify viewport
Image
Before
After
etc.)
- [] "OS: 
- [] "Browser: …
=> fix(MagnifyTool) should display rotated,inverted image correctly

common/reviews/api/streaming-image-volume-loader.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/streaming-image-volume-loader/src/StreamingDynamicImageVolume.ts, packages/streaming-image-volume-loader/src/enums/Events.ts, packages/streaming-image-volume-loader/src/enums/index.js, packages/streaming-image-volume-loader/src/index.ts
- fix bugs
- exports
- api
etc.)
- [] "OS: 
- [] "Browser:
=> fix(colormap invert): and dynamic volume new timePoint index event

common/reviews/api/tools.api.md, packages/tools/src/tools/OrientationMarkerTool.ts
Currently, the OrientationMarker tool drawings will remain on screen after the tool is disabled. These changes will remove the drawings after the tool is disabled.
Before:
https://github.com/cornerstonejs/cornerstone3D/assets/22822446/ca7dd5c8-206f-4913-a78d-99fa74172ad4
After:
https://github.com/cornerstonejs/cornerstone3D/assets/22822446/82acc4a1-6baf-4769-9b36-b7ae2f093874
=> feat(OrientationMarker): clean up orientation marker

packages/core/package.json, packages/nifti-volume-loader/package.json, packages/streaming-image-volume-loader/package.json, packages/tools/package.json
The current `main` field in package.json would cause app fail to import @cornerstone/xxx packages
Add `exports` field in package.json in these packages to distinguish cjs and mjs usage
* @cornerstonejs/core
* @cornerstonejs/tools package
* @cornerstonejs/nifti-volume-loader
* @cornerstonejs/streaming-image-volume-loader
None
etc.)
=> Fix: package exports

packages/dicomImageLoader/docs/TransferSyntaxes.md, packages/dicomImageLoader/src/imageLoader/decodeImageFrame.ts, packages/dicomImageLoader/src/imageLoader/wadors/loadImage.ts, packages/dicomImageLoader/src/shared/decodeImageFrame.ts, packages/streaming-image-volume-loader/src/BaseStreamingImageVolume.ts
The transfer syntax UID's for HTJ2K were finally released today, so this PR updates them to use the new ones.
Just add the new transfer syntaxes.
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix: final htj2k transfer syntaxes

packages/tools/src/tools/base/BaseTool.ts, packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts, yarn.lock
There was an import that ended up importing itself and trying to resolve all the imports along the way, introduced in the video code.
Use direct import instead of import via the group/namespace files.
Link core/tools into OHIF.  Start OHIF - if it starts, the fix worked.
etc.)
- [] "OS: 
- [] …
=> fix: Inclusion of this build in OHIF was causing an import loop

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/core/src/utilities/getTargetVolumeAndSpacingInNormalDir.ts, packages/core/src/utilities/getVolumeSliceRangeInfo.ts, packages/core/src/utilities/getVolumeViewportScrollInfo.ts, packages/tools/examples/volumeSlabScroll/index.ts, packages/tools/src/tools/StackScrollToolMouseWheelTool.ts, packages/tools/src/types/ScrollOptions.ts, packages/tools/src/utilities/scroll.ts
Seems like scrolling with slab thickness accommodated is not always a desired behavior, so I'm adding it as an option.
Should work like before, just adding an option. Try `volumeSlabScroll` example
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix(slabScroll): spacing calculation in getTargetVolumeAndSpacingInNormalDir function

packages/tools/src/tools/VolumeRotateMouseWheelTool.ts
RotateMouseWheel as a configuration unit in degree (which is fine)
The probleme is that the value in degree was passed to glmatrix which is using radian rotation unit
Convert degree to radian before application
N/A
No modification needed
=> fix: Add degree to rad conversion for rotate mouse wheel

packages/tools/src/tools/annotation/LivewireContourTool.ts
After making changes to support double clicks to close a path a new issue was introduced as shown in the video below where you can see a straight line after closing a path. The issue is because a new control point is added after closing the path.
https://github.com/cornerstonejs/cornerstone3D/assets/931820/fa83b8c1-f78f-421f-9905-287e462d6504
=> fix(livewire): issue when closing a path

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts
@Celian-abd FYI this was causing this issue
I'm fixing the viewUp to be decided after orientation change 
etc.)
- [] "OS: 
- [] "Browser:
=> fix(viewUp): Adjust behavior after orientation change

packages/docs/docs/getting-started/installation.md
The current installation page has these questions:
* NPM installation script is splited into three code blocks which is unnecessary
* Lack of YARN section title
* Lack of  [PNPM](https://pnpm.io) which is also a popular package manager
* Combine the splitted npm install code blocks into one
* Add YARN and PNPM section and their corresponding installation script
None
etc.)
=> docs:  installation page optimization

packages/dicomImageLoader/src/imageLoader/colorSpaceConverters/convertYBRFull422ByPixel.ts
Wrong error message. According to the code context, the message shoulde be "divisble by 2" instead of "divisble by 3"
```diff
- throw new Error('decodeRGB: ybrBuffer length must be divisble by 3');   
+ throw new Error('decodeRGB: ybrBuffer length must be divisble by 2');
```
None
etc.)
=> fix: wrong color convert error message

packages/tools/src/tools/annotation/AngleTool.ts
The Angle tool does not support for auto removing when outside image. 
Use the `transformWorldToIndex` and `indexWithinDimensions` in `utilities` module in @cornerstonejs/core package to decide whether all the handles are within image. If not, make the `isHandleOutsideImage` value become `true`
etc.)
=> fix: add auto remove when outside image for AngleTool

packages/tools/src/tools/annotation/SplineROITool.ts
Make `SplineROITool` auto removing when there's at least one of the  points is outside of image range.
In the `_endCallback`, determine whether to removing the annotation based on the points position is within image range or not.
etc.)
=> fix(splines): add auto removing when outside image for SplineROITool series

packages/tools/src/tools/annotation/SplineROITool.ts
Spline ROI/Segmentation examples are broken because it SplineROITool class expects to have `configuration.interpolation.enabled` configuration and it fails when it is undefined.
Changed `configuration.interpolation.enabled` to `configuration.interpolation?.enabled` to make sure it will not fail when `interpolation` configuration is not available.
Check Spline ROI Tools, Spline Segmentation Tools and Advanced Spline Segmentaion Tools examples.
=> fix(spline): spline ROI/Seg broken

packages/tools/src/tools/annotation/SplineROITool.ts
The current `SplineROI` has a closed status value for every annotaion. And it is stored in the `annotation.data.spline.instance.closed`. But the current code is getting it from `annotation.data.spline.closed` which is always `undefined`
As a result it would cause losing the spline from calling `getTextlines` function. So the text part is missing in the final rendered svg
```diff
- if (!data.spline.closed || !textboxStyle.visibility) {
+ if (!data.spline.instance.closed || !textboxStyle.visibility) {
```
* Before
* After
etc.)
=> fix: wrong closed status value in SplineROI tool

packages/tools/src/tools/WindowLevelTool.ts
When using mouse with `WindowLevelTool`. When the `voiRange.upper` is equal to or less than `voiRange.lower`, would cause `attempt to set zero width color range` in the console.
Add a condition to ensure `voiRange.upper` is larger than `voiRange.lower`
* Before
* After
etc.)
=> fix(WindowLevelTool): attempt to set zero width color range

packages/dicomImageLoader/src/imageLoader/createImage.ts
The canvas context API `createImageData ` would always return a `ImageData `. And its `data` field is always a rgba color mode `Uint8ClampedArray `, like this:
In the newest vtk package which has already been upragded in cornserstone repo would throw a error like this:
As a result, the image would not render.
This PR fix it.
Add a condition, if not using rgba, then replace the data with a new Uint8ClampedArray with  `imageFrame.samplesPerPixel * columns * rows`  length
I've tested on my private project. I'm sorry I can't share it with others because the image 
belongs to company.
Sorr for the inconvenience.
etc.)
=> fix(dicom-image-loader): add rgba condition interception for canvas createImageData API

packages/tools/src/tools/MagnifyTool.ts
The current Magnify tool would cause an error when just single clicked on the canvas.
The reason is `setStack` is an async function. In the `then` callback, the magnify element has already been removed from the dom tree. So the `setProperties` function would cause this error.
This PR fix #866 
And a flag `_hasBeenRemoved` to determine whether the current magnify element has been removed from dom tree. Change its status to `true` in the `_dragEndCallback`. Restore to `false` in the `_activateDraw`.  Use it in the `setStack` callback, if `true`, then do nothing.
etc.)
=> fix(Magnify): add flag to jump error and unnecessary logic

packages/streaming-image-volume-loader/src/helpers/splitImageIdsBy4DTags.ts
Related to #1048 and OHIF PR [#3664](https://github.com/OHIF/Viewers/pull/3664). Both deal with the issue of adding support for 4D datasets to OHIF Viewer.
Refactor splitting datasets in `packages/streaming-image-volume-loader/helpers/splitImageIdsBy4dTags`.
- First group by imagePositionPatient. Allows checking whether the dataset is potentially a multi-stack (4D) dataset (i.e. equal and > 1 number of frames for each position)
- Check ability of predefined tags to split the dataset (i.e. unique values within 1 position, but corresponding instances for any one value in all positions).
- By checking tags on the position-grouped instances, early stopping is possible (e.g. when duplicate values are encountered, or when a set of values does not match the first such set).
- Add custom …
=> fix: Refactor image splitting logic for 4D datasets

common/reviews/api/tools.api.md, packages/tools/src/eventListeners/annotations/contourSegmentation/contourSegmentationCompleted.ts, packages/tools/src/tools/annotation/LivewireContourTool.ts, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/SplineROITool.ts, packages/tools/src/tools/annotation/planarFreehandROITool/drawLoop.ts, packages/tools/src/tools/base/ContourBaseTool.ts, packages/tools/src/utilities/contours/updateContourPolyline.ts, packages/tools/src/utilities/math/line/distanceToPointSquaredInfo.ts, packages/tools/src/utilities/math/polyline/decimate.ts, packages/tools/src/utilities/math/polyline/index.ts, packages/tools/src/utilities/math/polyline/simplify.ts
Adding contour annotations may result in polylines with thousands of points making the viewer much slower to render the annotations and also process them (append, remove, create holes, interpolate, etc.). 
Implemented the Ramer–Douglas–Peucker algorithm that simplifies polylines based on an a given distance `epsilon` reducing the amount of points in a polyline.
Two polylines with 6k (source) and 7k (target) points were used on the test below to measure the time it would take to merge them before and after simplifying the polylines.
A good way to generate contours with +50k points is zooming all the way out before creating a freehand segmentation contour. Both polylines got simplified to new polylines with ~200 points or less each with no visual changes on the viewport. I know this is not …
=> feat(contourSeg): polyline performance improvements

common/reviews/api/tools.api.md, packages/tools/examples/planarFreehandContourSegmentationTool/index.ts, packages/tools/examples/segmentSelect/index.ts, packages/tools/src/eventListeners/annotations/annotationRemovedListener.ts, packages/tools/src/eventListeners/annotations/contourSegmentation/contourSegmentationCompleted.ts, packages/tools/src/eventListeners/annotations/contourSegmentation/contourSegmentationRemoved.ts, packages/tools/src/eventListeners/annotations/contourSegmentation/index.ts, packages/tools/src/eventListeners/annotations/index.ts, packages/tools/src/eventListeners/index.ts, packages/tools/src/init.ts, packages/tools/src/tools/annotation/PlanarFreehandContourSegmentationTool.ts, packages/tools/src/types/ContourSegmentationAnnotation.ts, packages/tools/src/utilities/getViewportForAnnotation.ts, packages/tools/src/utilities/getViewportsForAnnotation.ts
- `segmentSelect` example was not working as intended
- `SEGMENTATION_DATA_MODIFIED` was not being triggered for `PlanarFreehandContourSegmentationTool`
- changed how `contourSegmentationCompletedListener` finds a viewport with PlanarFreehandContourSegmentationTool tool enabled
- added an event listener to run when an annotation is deleted to update the annotationUIDsMap that contains contour UIDs in each segmentation
- added the contour UID of each annotation created after appending/removing annotations
=> fix: segmentSelect issue + segmentation modified event

packages/tools/examples/splineROITools/index.ts, packages/tools/src/tools/annotation/SplineROITool.ts
- Splines were not updating properly after changing the resolution and/or scale.
- The position of the lines were not updating after zooming in/out breaking all mouse events.
- Changed the code to make sure the splines will be updated not only when `annotation.invalidated` is true because that flag does not change after updating the config
- Fixed an issue with string/number conversion before comparing the value from  the configuration with the current spline resolution and scale values
- Open Spline ROI Tool example
- Draw a spline
- Change its resolution (it was broken before)
- Change its scale (it was broken before)
- Zoom in/out and try to click on the handle/spline to move it
=> fix(spline): spline update issue

packages/tools/src/utilities/triggerAnnotationRender.ts
In some cases the viewports are not re-rendered making it impossible to draw annotations.
Updated `triggerAnnotationRender` responsible for "scheduling" a render call using RAF to make sure that even when an event listener adds a viewport back to the `needsRender` list it can reschedule a new render call instead of getting blocked.
Just open some examples such as [Spline Contour Segmentation Advanced](https://www.cornerstonejs.org/live-examples/splinecontoursegmentationtoolsadvanced) or [Livewire Contour Segmentation](https://www.cornerstonejs.org/live-examples/livewirecontoursegmentation) and try to add annotations to coronal or sagittal viewpots.
=> fix(annotations): Ensure viewports re-render for annotation drawing

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/enums/Events.ts, packages/core/src/types/EventTypes.ts, packages/tools/src/utilities/voi/colorbar/ViewportColorbar.ts
This change makes so the Stack and Volume viewports trigger a colormap modified event, so that the colorbar can listen to the event and update it's colormap as needed.
- Added COLORMAP_MODIFIED Event
- Added new listener in ViewportColorbar.
=> feat(colorbar): react to changes to the colormap

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/types/EventTypes.ts, packages/tools/src/utilities/voi/colorbar/ViewportColorbar.ts
If there's two colorbars on the same viewport, and the colormap is modified, it's not enough to only check the viewport id, we need to make sure the volumeId also matches, otherwise both colorbars will change color.
pass volumeId in the event for volume viewport.
=> fix(colorbar): don't change colorbar color if volume id doesn't match

common/reviews/api/tools.api.md, packages/tools/src/tools/WindowLevelTool.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1088
WindowLevel tool was using a higher multiplier resulting in much faster changes to window width and window level making it harder to adjust.
Changed the function responsible for getting the range from the viewport which was returning an array instead of a single number breaking the calculation of the ratio (`NaN`).
- Open [videoColor](https://www.cornerstonejs.org/live-examples/videocolor) example
- Click on the viewport to change the ww/wc
=> fix: windowLevel dynamic range from video viewport (#1088)

packages/tools/src/eventListeners/annotations/contourSegmentation/contourSegmentationCompleted.ts
Remove contour segmentation annotations from `annotationUIDsMap` as soon as they are "converted" into a hole.
=> fix: remove contour segmentation holes from annotationUIDsMap (#1095)

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
We need to return the correct colormap information if there's more than 1 volume on the viewport
- Added getColormap function that attempts to identify the currently set colormap on the volume.
i’m not sure if we should say “attempts” as from my testing this seems to return the correct opacity and colormap 100% of the time. but I’m not a vtk expert, so I can’t say for certain that this is 100% accurate.
=> feat(volumeviewport): return volume specific colormap information

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
We were only comparing the currently set colormap to the predefined vtk presets, those presets do NOT include what has been registered in CS3D, we need to check there as well.
Imported all colormaps registered in CS3D
=> fix(volumeviewport): cs3D colormaps were not being compared in getColormap function

packages/tools/src/utilities/getCalibratedUnits.ts
The calibration type was not being returned so it was not being rendered.
Fixed above issue
=> fix(calibration tool): fix calibration type not being rendered on measurements

packages/tools/src/synchronizers/callbacks/voiSyncCallback.ts
This adds a configuration option that makes it optional to sync the colormaps
Added syncColormap option
=> fix(colormap): make syncing colormap optional

packages/tools/src/tools/annotation/AngleTool.ts
Fixes #1144 
The incomplete angle created with just one line has the verbiage NaN as the angle - this should not appear on the image
Before:
After:
1. Run `yarn example -- stackAnnotationTools`
2. Select 'Angle' annotation tool
3. Click, hold and drag the mouse to begin drawing the angle
4. When you reach the desired point of the vertex, click the mouse button twice
The measurements panel will display the verbiage 'Incomplete Angle' for any angle measurement that is incomplete (meaning the angle has only one line not, two lines)
etc.)
additions or removals. (This doesn't apply to this PR as no api changes were made)
- [macOS 14.3.1] "OS: 
- …
=> fix(AnnotationTool): fix NaN verbiage in angle tool on incomplete angle

packages/tools/src/utilities/cine/playClip.ts
Fixes #1162 
Cine playclip options is not being taken into account when determining whether to loop cine
replaced hardcoded true value with playclipdata, which defaults to true but accounts for configuration
using the CINETool example code, you can try passing through loop: false in playClipOptions on line 106
etc.)
[script]: …
=> Fix playclip to allow loop config

packages/nifti-volume-loader/src/helpers/convert.ts, packages/nifti-volume-loader/src/helpers/fetchAndAllocateNiftiVolume.ts
This should fix: https://github.com/cornerstonejs/cornerstone3D/issues/1156
@sedghi 
Using example: https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/nifti-volume-loader/examples/niftiWithTools/index.ts#L130-L133
```
async function setup() {
setUseSharedArrayBuffer(false);
await csInit();
await csTools3dInit();
...
}
```
Over Direct IP (non https)
Over Localhost (non https)
Https Mode
etc.)
- [] The documentation page has been updated as necessary for any public …
=> fix(nifti): support NON-SharedArrayBuffer mode for loading nifti volumes

packages/tools/examples/splineROITools/index.ts, packages/tools/src/tools/annotation/SplineROITool.ts
When a new added polygon is out of range and the `preventHandleOutsideImage` is true. The new added polygon would be auto removed. After that, all the future add polygons would not trigger the complete event, like this:
This PR fix it.
The cause is `this.fireChangeOnUpdate` would not be reassign after the new added out of range annotation is removed. 
As a result the annotation complete event would never be fired.
This PR add code to update `annotationUID` and `changeType` field in `this.fireChangeOnUpdate`
etc.)
=> fix(SplineROI): future added polygon woud not trigger complete event when a polygon is out of range and  got removed

packages/tools/src/tools/TrackballRotateTool.ts
Resize observer was throwing errors because element was not defined
return if not defined.
=> fix(trackball): return if element is not defined in resize observer

packages/core/src/utilities/colormap.ts
The `getProperties` function currently returns the colormap name, but it does not include the opacity.
- Added the opacity mapping to the `findMatchingColormap` function's return object.
- The function now returns an object that conforms to the `ColormapPublic` type, including the `name` and `opacity` properties.
- 
etc.)
=> fix(getColormap): add opacity mapping to findMatchingColormap return object

packages/tools/src/tools/ScaleOverlayTool.ts
scale overlay tool was broken because it wasn't taking the device pixel ratio into account.
Fixed the device pixel ratio
=> fix(scaleoverlay): account for device pixel ratio when drawing the scale annotation

packages/tools/src/tools/AnnotationEraserTool.ts
Related to #1218
Fixes the 'not iterable' error in the `AnnotationEraserTool` when using the Eraser Tool with both LengthTool and PlanarFreehandROITool loaded.
- Adds a conditional check to ensure `filterInteractableAnnotationsForElement` does not return `undefined` before attempting to iterate over its result. This prevents the 'not iterable' error by ensuring `interactableAnnotations` is always an array, even if it's empty.
- Modifies the `_deleteNearbyAnnotations` method to gracefully handle cases where `filterInteractableAnnotationsForElement` might return `undefined`, ensuring the Eraser Tool functions correctly regardless of the combination of tools loaded.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/cornerstonejs/cornerstone3D/ …
=> fix: Eraser Tool Error with LengthTool and PlanarFreehandROITool Loaded

packages/adapters/examples/segmentationVolume/demo.ts, packages/adapters/examples/segmentationVolume/index.ts, utils/demo/helpers/addBrushSizeSlider.ts, utils/demo/helpers/addButtonToToolbar.ts, utils/demo/helpers/addCheckboxToToolbar.ts, utils/demo/helpers/addDropdownToToolbar.ts, utils/demo/helpers/addLabelToToolbar.ts, utils/demo/helpers/addSliderToToolbar.ts, utils/demo/helpers/addUploadToToolbar.ts
Example Segmentation Volume
https://deploy-preview-1201--cornerstone-3d-docs.netlify.app/live-examples/segmentationVolume.html
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> docs(Example): Update Segmentation Volume

packages/tools/src/tools/AnnotationEraserTool.ts
- Fixes issue number [1218](https://github.com/cornerstonejs/cornerstone3D/issues/1218). 
- Annotations being checked for every added Tool were continuing based on annotations truthiness, an empty array is always returned at a minimum. 
- PR changes the check to the length of the annotations array returned (which is 0 when there are no annotations for a tool). This terminates the iteration in question and removes the the error in issue [1218], of looping through an empty array of annotation objects.
- .length added to annotation if statement in ` packages/tools/src/tools/AnnotationEraserTool.ts ` on Line 58
- Eraser tool removes annotation selected on without the `Uncaught TypeError: interactableAnnotations is not iterable` error
- run `yarn run example stackAnnotationTools`
- create an …
=> fix(AnnotationEraserTool): check length of annotation on eraser _deleteNearbyAnnotations

packages/core/examples/volumeLarge/index.ts, packages/core/src/cache/cache.ts, packages/core/src/loaders/volumeLoader.ts, packages/core/src/utilities/createFloat32SharedArray.ts, yarn.lock
Browsers don't allow allocation of more than 2gb memory using the standard buffer allocators.  This PR adds the ability to allocate using the WebAssembly.Memory allocator, which seems to work fine up to 4 gb, although the GPU does complain about memory texture size limits.
Added a test example, using local data for now (and so not in the shared examples), plus changed the  createFloat32SharedArray to use WebAssembly.Memory
Deploy the test data to localhost:5000/dicomweb
Run
yarn example volumeLarge
View the page, should display (may still be browser dependent).
etc.) …
=> fix(rendering): Allow memory sizes between 2gb and 4gb by using wasm allocation

packages/dicomImageLoader/src/imageLoader/wadouri/metaData/metaDataProvider.ts
will try to fix the https://github.com/OHIF/Viewers/issues/4081
etc.)
- [] "OS: 
- [] "Browser:
=> fix(metaData): transfer syntax retrieval in metaDataProvider

packages/core/src/utilities/sortImageIdsAndGetSpacing.ts, packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts
When loading a multiframes dicom, the MIP is upside-down on OHIF.
- Added the spacingBetweenSlices property to correctly know the orientation of the image.
We tryied to make an example on cornerstone3D but we can't load multiframes dicom on cornerstone3D as we believe the multiframes logic is on OHIF. Maybe someone knows how to fix that.
etc.)
- [] The documentation page has been updated as necessary for any …
=> fix(multiframes) add spacingBetweenSlices property for multiframes dicom

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/VideoViewport.ts, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/types/IViewport.ts, packages/tools/examples/interpolationContourSegmentation/index.ts
- **fix(imageIndex vs sliceIndex): imageIndex should be ijk based and slice index view based**
- **api**
etc.)
- [] "OS: 
- [] "Browser:
=> fix(imageIndex vs sliceIndex): imageIndex should be ijk based and slice index view based

packages/core/examples/stackCanvasToWorld/index.ts
Related to #391
Updates the `stackCanvasToWorld` example to include `image (ijk)` coordinates alongside `canvas` and `world` coordinates.
- Imports the `worldToImageCoords` utility from `@cornerstonejs/core` to facilitate the conversion of world coordinates to image (ijk) coordinates.
- Adds a new UI element to display the `image (ijk)` coordinates, enhancing the example's output with additional information.
- Implements the conversion of world coordinates to `image (ijk)` coordinates using the `worldToImageCoords` utility and displays these coordinates in the newly added UI element.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/cornerstonejs/cornerstone3D/issues/391?shareId=c7f14136-fcce-4331-8fca-59221798ab8d).
=> examples: Add image (ijk) coordinates to stackCanvasToWorld example

packages/tools/src/utilities/stackPrefetch/stackContextPrefetch.ts, packages/tools/test/utilities/stackPrefetch/stackContextPrefetch_test.js
This PR fixes the stackContextPrefetch.disable function that was always failing.
Additionally it makes sure that cached images are not fetched again.
stackContextPrefetch.disable: remove check of data that will never exist
stackContextPrefetch.prefetch: it is already checked, if images are already cached. Now it does not request cached images again, as it was intended
I added a test for the disable function.
I tried to add a test for the duplicated fetching but found it difficult to test this asynchronous and open-ended behavior.
etc.)
- [] "Browser:
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untruste …
=> fix(stackContextPrefetch): fix disable function, reduce duplicated fetching of images

packages/tools/src/tools/StackScrollTool.ts
Related to this fix, stackscrolltool still uses getTargetId
https://github.com/cornerstonejs/cornerstone3D/commit/9f9a9a020cfbb9d7d4e185471bb4665b31f809dd
* Also the same problem applies to "CircleROIStartEndThresholdTool" and "RectangleROIStartEndThresholdTool", i didn't edit them for now because i couldn't test them.
etc.)
additions or …
=> fix:Update StackScrollTool to improve volume ID extraction

packages/tools/examples/dynamicPetCt/index.ts, packages/tools/examples/petCt/index.ts, packages/tools/examples/volumeViewportSynchronization/index.ts
https://www.cornerstonejs.org/live-examples/petct
https://www.cornerstonejs.org/live-examples/dynamicpetct
https://www.cornerstonejs.org/live-examples/volumeViewportSynchronization
I found that the synchronizer effect of dynamicPetCt 、petCt、 volumeViewportSynchronization examples is wrong, corrected it, and StudyInstanceUID is invalid
fix: examples: dynamicPetCt and petCt for Voi synchronizer
etc.)
- [] The …
=> chore(example)：dynamicPetCt petCt volumeViewportSynchronization Voi synchronizer

common/reviews/api/core.api.md, package.json, packages/core/src/RenderingEngine/VideoViewport.ts, packages/core/src/RenderingEngine/WSIViewport.ts, packages/core/src/enums/MetadataModules.ts, packages/core/src/utilities/genericMetadataProvider.ts, packages/tools/src/tools/ZoomTool.ts, utils/demo/helpers/addManipulationBindings.ts
There was a request to change the generic metadata provider as to how to stores metadata for object based metadata.  Also, changed some navigation setup so that WSI and Video viewports navigate correctly.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix: Navigation issues and naming issues for video/wsi

packages/tools/src/tools/OrientationMarkerTool.ts
In OHIF viewer TMTV mode, a cube is shown indicating the orientation. However, left and right are switched on this cube, causing confusion.
Switched L and R in OrientationMarkerTool.
Load the tmtv mode in OHIF viewer.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix(OrientationMarkerTool): R and L are swapped

packages/dicomImageLoader/src/imageLoader/createImage.ts
Palette color displays resulted in a buffer size mismatch, resulting in not being able to display palette color images.
In load image, use a fixed 3 for the number of samples for the output of the color conversion instead of the (wrong) 1 samples per pixel that palette color uses.
Display a palette color image in OHIF.  
etc.)
additions …
=> fix: Palette color display

packages/dicomImageLoader/src/types/DICOMLoaderIImage.ts
The import logic for ImageFrame type in the `DICOMLoaderIImage` interface seems to have been deleted.
A type error occurs in that file.
Added ImageFrame type import logic. bd5dfebd91f28e644c96b6ee8ab15510bce567e4
No type errors are thrown.
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix: add missing import ImageFrame type logic

packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport3D.ts
VolumeViewport3D had not implemented the `resetProperties` function making it unable to be reset when needed. Not only that but the BaseVolumeViewport did not reset the `preset` property when you executed `resetToDefaultProperties` function, neglecting a portion of the main features of its class.
Implemented `resetProperties` on VolumeViewport3D (very similar to VolumeViewport implementation maybe we could move this up in the hierarchy) and updated the `resetToDefaultProperties` function to consider the `preset` property.
Run `https://www.[cornerstonejs.org/live-examples/volumeviewport3d](https://www.cornerstonejs.org/live-examples/volumeviewport3d)` and then call `viewport.resetProperties()` and `viewport.resetToDefaultProperties()` to see the rotation and the preset being reset
=> fix: VolumeViewport3D reset Properties

common/reviews/api/tools.api.md, packages/tools/examples/planarFreehandROITool/index.ts, packages/tools/src/utilities/planarFreehandROITool/smoothAnnotation.ts
If smooth annotations got called on an annotation not currently in view, it would destroy the annotation.
Also, smoothing a closed annotation would result in a sharp point due to not smoothing the start/end overlap.
Finally, smoothing functions were accessing the old contour polyline data to test whether to smooth, so smoothing was broken unless setting extra values.
Use mat4.lookAt to generate a rotation matrix instead of the viewport rotation matrix instead of using canvas coordinates, as the canvas coordinates aren't always available.
Rotate the closed contours randomly to fix the sharp point being generated (you could actually cause it to interpolate to a square like container, with 4 sharp points)
Fix the prevent smoothing test so it works on the newer contour polyline lengths.
Run …
=> fix: Smooth annotations for off viewport destroyed coords

packages/dicomImageLoader/src/imageLoader/isColorConversionRequired.ts
Color conversion was inadvertently turned off for color by plane.  This PR just turns it back on again.
Added an or condition with planar configuration 1 for the isColorConversionRequired method.  This turns on conversion for color by plane.
See linked issues for test dicom to test this with.
#4359 and #4231
Linked into OHIF for testing.  This displays the right image.
etc.)
- [] The documentation page has been …
=> fix: Color conversion is required for RGB and planar configuration 1

packages/dicomImageLoader/src/imageLoader/internal/streamRequest.ts, packages/tools/src/utilities/planarFreehandROITool/smoothAnnotation.ts
The streaming image loading didn't call the before send method, so the headers weren't getting set correctly.
Just call the before send configured to generate appropriate headers.
etc.)
- [] "OS: 
- [] "Browser: …
=> fix: Add HTTP headers from configuration for streaming image loading

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/enums/Events.ts, packages/core/src/types/EventTypes.ts, packages/tools/examples/stackManipulationTools/index.ts, packages/tools/src/utilities/scroll.ts
Triggered `STACK_SCROLL_OUT_OF_BOUNDS` event in the `scroll` function of the stack viewport. Updated `stackManipulationTools` example to demonstrate the events trigger. 
https://github.com/OHIF/OHIF-Office-Hours/blob/main/notes/2024-08-08.md - followed the guides in the answer here.
=> feat: stack scroll out of bounds event

packages/core/src/utilities/VoxelManager.ts, packages/tools/examples/labelmapSegmentationDynamicThreshold/index.ts, packages/tools/src/tools/segmentation/BrushTool.ts, packages/tools/src/tools/segmentation/strategies/BrushStrategy.ts
The preview wasn't showing at all for the dynamic threshold.
The preview mode wasn't working, nor was the bidirectional auto-calculation for segmentations.
The changes are:
* Don't reset changed slices array for preview mode
* Record changed data when set data returns undefined as well as when it returns true
* Enable the preview mode for the example
Run yarn example for
```
yarn example labelmapSegmentationDynamicThreshold
yarn example segmentBidirectionalTool
```
etc.) …
=> fix: Dynamic threshold wasn't working in the beta branch

packages/docs/docs/concepts/cornerstone-core/metadataProvider.md, packages/docs/docs/how-to-guides/custom-imageLoader.md, packages/docs/docs/how-to-guides/custom-metadata-provider.md
**NOTE: This PR is currently set to merge into the `beta` branch. We may want to await the merge of `beta` into `main` first and then merge this PR into main afterwards?**
This PR improves some Custom Image Loader / Metadata Provider related documentation.
The topic of writing a Custom Image Loader based on the existing DICOM Image Loader goes back years, and I've recently taken the time to research and understand the topic a lot better. (See also #1509 for the resulting PR.) These updates to the documentation are a result of that: they represent links between documentation pages that would have made this a lot clear to begin with.
I'd like to describe the following better in documentation as well, either in this PR or in follow-up.
- Can Cornerstone display images without ANY metadata …
=> docs(image loader/metadata provider): Clarify concept + how-to documentation.

packages/tools/examples/referenceLines/index.ts, packages/tools/src/tools/ReferenceLinesTool.ts
In the ReferenceLinesTool, reference lines are incorrectly displayed across assets with different Frame of References (FoR) UIDs. This behavior can confuse users as reference lines are intended to be shown only on assets that share the same FoR UID. When reference lines appear on unrelated assets, it creates a misleading impression and affects the accuracy of cross-referencing between different images or data.
More details: https://github.com/cornerstonejs/cornerstone3D/issues/1512, https://github.com/cornerstonejs/cornerstone3D/issues/1501
`enforceSameFrameOfReference` configuration flag has been added to ReferenceLinesTool. Now developers can toggle this flag to avoid such situation if needed.
Example of  `enforceSameFrameOfReference` flag toggled on in action: …
=> fix(ReferenceLinesTool) Issue 1512 - Reference lines displayed on assets with different Frame of References (UIDs), causing user confusion

common/reviews/api/tools.api.md, packages/tools/src/tools/OrientationMarkerTool.ts
Fix orientation marker tool bugs: 1. When you changed the orientation marker type, it would dissapear. 2. When you selected the custom type and then changed to another type, the two types would appear at the same time.
All the changes were made in the orientation marker tool type script file. First change was a reliable check in the widget object calling the .isDeleted() method to make sure if the widget was not previously deleted. The second change was to make sure the function addAxisActorInViewport() call was atomic and execute the end for a viewport id.
etc.) …
=> fix: orientation marker

packages/adapters/src/adapters/Cornerstone3D/ArrowAnnotate.js
Fortunately, TID300 at dcmjs, supports 2nd point in Point class. 
https://github.com/dcmjs-org/dcmjs/blob/master/src/utilities/TID300/Point.js
To support ArrowAnnotate at OHiF, OHIF code should be also modified (`extensions/cornerstone-dicom-sr/src/tools/DICOMSRDIsplayTool.ts`)
=> save 2nd point for arrow annotation

packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/cache/cache.ts
Addressing https://github.com/cornerstonejs/cornerstone3D/issues/1548 https://github.com/cornerstonejs/cornerstone3D/issues/1547
https://github.com/cornerstonejs/cornerstone3D/issues/1550
This pull request includes changes to the `Viewport` and `Cache` classes in the `packages/core/src/RenderingEngine/Viewport.ts` and `packages/core/src/cache/cache.ts` files, respectively. The most important changes involve adding rotation handling to the `Viewport` class and enhancing the `Cache` class to handle forced image decaching.
Enhancements to `Viewport` class:
* Added `rotation` to the `cameraInterface` properties.
* Implemented rotation handling in the `setViewPresentation` method if `rotation` is defined.
Enhancements to `Cache` class:
* Modified `_decacheImage` method to accept a `force` …
=> fix(viewport): Add rotation support in camera interface

packages/core/src/RenderingEngine/StackViewport.ts
Fixes issue described here: https://github.com/cornerstonejs/cornerstone3D/issues/1455
Modified the image URI check in the `isReferenceViewable` function in `StackViewport` from an `endsWith` match to an exact match. This stops annotations on images with IDs like `dicom:126` (which is the format used by the wadoURI filemanager) from displaying on the images `dicom:26` and `dicom:6` as well.
The repro provided in the linked issue demonstrates the bug, replacing the UMD build of `@cornerstonejs/core` with one containing this change will fix the bug.
etc.)
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untru …
=> fix: Annotations showing up on incorrect images

.circleci/config.yml, packages/core/src/init.ts, playwright.config.ts, utils/ExampleRunner/build-all-examples-cli.js
-  Use optional chaining for accessing preferSizeOverAccuracy in iOS configuration
-  Change example batching from 10 to 4 in the build-all-examples-cli script
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix: Improve configuration handling and adjust example batch size

packages/dicomImageLoader/.webpack/webpack-base.js, packages/docs/docs/getting-started/vue-angular-react-etc.md, packages/docs/docs/migration-guides/2x/1-general.md, packages/tools/src/utilities/cine/playClip.ts
This pull request includes several changes to the `dicomImageLoader` package and updates to the documentation for better integration with various frameworks. The most important changes include the removal of codec-related configurations in the Webpack setup, updates to the Vite and Webpack configuration instructions in the documentation, and the addition of a new section in the migration guide.
Codebase simplification:
* [`packages/dicomImageLoader/.webpack/webpack-base.js`](diffhunk://#diff-f5d5875990769c4c835c8412dd5d7c647ddcc3b6b6e3c864e26d29069ec9adcfL51-L74): Removed `noParse` and `exports-loader` configurations related to codecs as they are now included as ES modules.
Documentation updates:
* [`packages/docs/docs/getting-started/vue-angular-react-etc.md`](diffhunk://#diff-d15f97c5fa5 …
=> fix: jpeg codec build

packages/core/src/RenderingEngine/VolumeViewport.ts, packages/tools/src/eventListeners/segmentation/imageChangeEventListener.ts
fixes #1563 
This pull request includes significant improvements to the `VolumeViewport` and `imageChangeEventListener` functionalities. The most important changes involve modifying the camera clipping range logic and updating the way pixel data is handled in derived images.
* Modified the `setCameraClippingRange` method to use `RENDERING_DEFAULTS.MAXIMUM_RAY_DISTANCE` for setting the clipping range, improving the handling of oblique camera angles. (`packages/core/src/RenderingEngine/VolumeViewport.ts`)
* Updated the `_imageChangeEventListener` function to use the constructor of the voxel manager for creating new pixel data, ensuring proper handling of derived images. (`packages/tools/src/eventListeners/segmentation/imageChangeEventListener.ts`)
=> fix(camera): Update camera clipping range logic in VolumeViewport

packages/tools/src/utilities/cine/playClip.ts
-  Refactor `_stopDynamicVolumeCine` to ensure type checking for `VolumeViewport` before accessing volume
-  Move the check for dynamic volume playback inside the type check for `VolumeViewport`
-  Add type safety in `_getVolumeFromViewport` by returning `undefined` if the viewport is not an instance of `VolumeViewport`
etc.)
additions or …
=> Cine: Improve dynamic volume cine stopping logic

packages/tools/examples/dynamicPetCt/index.ts, packages/tools/examples/orientationMarker/index.ts, packages/tools/examples/petCt/index.ts
Fixed examples where VolumeRotateTool was not added to Cornerstone3D
Fixed an issue in examples where mip images cannot be rotated because VolumeRotateTool is not added to Cornerstone3D
etc.)
- [] "OS: 
- [] "Browser:
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks …
=> fix: Fixed examples where VolumeRotateTool was not added to Cornerstone3D

packages/nifti-volume-loader/src/cornerstoneNiftiImageLoader.ts
When loading a volume from a NIfTI file, there was a bug where retrieving the volume’s VoxelManager and executing `getRange` did not return the correct range. It always returned `[-Infinity, Infinity]`. This issue has been fixed.
The createImage function in cornerstoneNiftiImageLoader.ts should include minPixel and maxPixel in its return value, but it currently doesn’t. I added code to calculate minPixel and maxPixel and included them in the return value.
In `examples/niftiWithTools/index.ts`, you can verify that `getRange` works correctly by passing a callback function as follows to the part where `volume.load` is executed.
```
await volume.load(() => {
console.log(volume.voxelManager?.getRange());
});
```
etc.)
committed the changes to this PR. …
=> fix(cornerstoneNiftiImageLoader): Resolve getRange issue for NIfTI volumes

common/reviews/api/tools.api.md, packages/core/examples/volumeBasicWadoUri/index.ts, packages/core/examples/wadouri/index.ts, packages/tools/examples/crossHairs/index.ts, packages/tools/examples/labelmapSegmentColorChange/index.ts, packages/tools/src/stateManagement/segmentation/internalAddSegmentationRepresentation.ts, packages/tools/src/tools/CrosshairsTool.ts, packages/tools/src/types/SegmentationStateTypes.ts, utils/demo/helpers/WADOURICreateImageIds.js, utils/demo/helpers/index.js
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1584
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1604
This pull request includes several changes across multiple files to improve the handling of image IDs, segmentation representations, and viewport rendering checks. The most important changes include modifying the `_checkIfViewportsRenderingSameScene` method, updating the `colorLUTOrIndex` configuration, and refactoring the image ID creation process.
* [`packages/tools/src/tools/CrosshairsTool.ts`](diffhunk://#diff-2aecc4dd196e6f973c0ce4be3f0ffe15570adbc3cdcd81c45eeffaf928a07c37L1891-R1897): Modified the `_checkIfViewportsRenderingSameScene` method to compare volume IDs instead of actors, ensuring a more accurate scene comparison.
* …
=> fix(tools): segmentation colorLUT initial config and crosshairs jump to click

packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/tools/src/store/SynchronizerManager/Synchronizer.ts
Fixes https://github.com/OHIF/Viewers/issues/4539
Fixes https://github.com/OHIF/Viewers/issues/4535
This pull request includes changes to improve error handling and code readability in the `BaseVolumeViewport` and `Synchronizer` classes. The most important changes include modifying the return value for missing `RenderingEngine` and `viewport` instances, and improving the `volumeId` query string construction.
Error handling improvements:
* [`packages/tools/src/store/SynchronizerManager/Synchronizer.ts`](diffhunk://#diff-87a71761bf4c3cb80f734f572a35cf9e1f733fab14ad8602c0abef241da8df01L383-R394): Modified the `getEventSource` method to return `null` instead of throwing an error when the `RenderingEngine` or `viewport` is not found.
* …
=> RenderingEngine & Synchronizer: Improve error handling and code robustness

packages/core/src/utilities/VoxelManager.ts
etc.)
- [] "OS: 
- [] "Browser:
=> fix: voxelmanager getCompleteScalarData

packages/tools/src/utilities/segmentation/growCut/runGrowCut.ts, utils/ExampleRunner/example-info.json
This pull request includes changes to the `runGrowCut` function in the `packages/tools/src/utilities/segmentation/growCut/runGrowCut.ts` file and updates to the `example-info.json` file to add a new segmentation tool. The most important changes include adjusting the WebGPU memory limit, making the request adapter call optional, and adding a new AI assistance tool for segmentation.
Changes to WebGPU memory limit and request adapter:
* [`packages/tools/src/utilities/segmentation/growCut/runGrowCut.ts`](diffhunk://#diff-c7480b0fbfe6cd40f34bbab3407c1d9fa3691d3bcd13ad0958a45d147d88acd1L7-R7): Reduced the `WEBGPU_MEMORY_LIMIT` from 2 GB to 1.99 GB to ensure compatibility with certain systems.
* [`packages/tools/src/utilities/segmentation/growCut/runGrowCut.ts`](diffhunk://#diff-c7480b0fbfe6cd40f …
=> fix(growcut): memory limit issue

common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/ai/examples/SAMClientSide/index.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/utilities/historyMemo/index.ts, packages/tools/src/tools/annotation/SplineROITool.ts, packages/tools/src/tools/annotation/WholeBodySegmentTool.ts, packages/tools/src/tools/segmentation/strategies/compositions/islandRemoval.ts, packages/tools/src/tools/segmentation/strategies/compositions/labelmapStatistics.ts, packages/tools/src/utilities/segmentation/growCut/runGrowCutForBoundingBox.ts
This pull request includes various improvements and fixes across multiple files. The most important changes include adding a setter for the `size` property in `HistoryMemo`, making certain pixel range properties optional in `GrowCutBoundingBoxOptions`, and adding a slider to the toolbar in the `SAMClientSide` example.
* Added a setter for the `size` property, which clears all history elements when the size is set. (`packages/core/src/utilities/historyMemo/index.ts`)
* Updated the `size` property to have a type of `number` instead of `any`. (`common/reviews/api/core.api.md`)
* Made `negativePixelRange` and `positivePixelRange` properties optional. (`common/reviews/api/tools.api.md`, `packages/tools/src/utilities/segmentation/growCut/runGrowCutForBoundingBox.ts`) …
=> chore: clean up some code for new prs

packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts
=> fix(getVtkActiveCamera): don't try to access renderer if it's undefined

packages/adapters/examples/segmentationStack/index.ts, packages/adapters/examples/segmentationVolume/index.ts, packages/adapters/examples/segmentationVolume/utils.ts, packages/adapters/src/adapters/Cornerstone/Segmentation_4X.js, packages/tools/src/eventListeners/mouse/mouseMoveListener.ts, packages/tools/src/eventListeners/segmentation/imageChangeEventListener.ts, packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1679
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1661
fixes https://github.com/cornerstonejs/cornerstone3D/issues/664
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1188
This pull request introduces several new functions and refactors existing ones to improve the handling of DICOM files and segmentation in the Cornerstone library. The changes include adding new utility functions for reading, loading, and exporting DICOM and segmentation files, as well as refactoring the `generateToolState` function to use more descriptive parameter names.
* [`packages/adapters/examples/segmentationVolume/utils.ts`](diffhunk://#diff-6e9363c3cc33c3dc0d3f9afa987c12e856040aa14d40791a0ee6c959edc05d75R1-R249): Added …
=> fix(examples): fix the stack and volume segmentation adapters example

packages/nifti-volume-loader/src/createNiftiImageIdsAndCacheMetadata.ts
The logic which decides if remote nifti file is compressed or not has a flaw. It checks the end of the URL string for `.gz` extension. When url includes parameters/headers, `.gz` extension appears in the middle of the string. 
For example, current logic will work for a URL like: `https://<some_address>/<filename>.nii.gz` but fail for a url like `https://<some_address>/<filename>.nii.gz?<some_param>=<some_value>`. 
This PR updates the logic to check for inclusion of the `.gz` extension anywhere in the string.
Tested in a limited local environment and works as expected.
etc.) …
=> Fix logic that determines if nifti file is compressed

common/reviews/api/dicom-image-loader.api.md, packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLTexture.js, packages/core/src/utilities/VoxelManager.ts, packages/dicomImageLoader/src/decodeImageFrameWorker.js, packages/dicomImageLoader/src/index.ts, packages/tools/src/tools/TrackballRotateTool.ts
fixes https://github.com/OHIF/Viewers/issues/4567
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1631
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1647
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1650
This pull request includes several updates across different modules to enhance functionality and improve code robustness. Key changes involve adding new functions, modifying existing methods, and ensuring proper handling of uninitialized data.
* Added `decodeImageFrame` function to `cornerstoneDICOMImageLoader` and exported it for public use. (`common/reviews/api/dicom-image-loader.api.md`, `packages/dicomImageLoader/src/decodeImageFrameWorker.js`, `packages/dicomImageLoader/src/index.ts`) …
=> fix: average blend mode and trackball rotate reset camera

common/reviews/api/nifti-volume-loader.api.md, packages/nifti-volume-loader/README.md, packages/nifti-volume-loader/examples/niftiWithTools/index.ts, packages/nifti-volume-loader/src/cornerstoneNiftiImageLoader.ts, packages/nifti-volume-loader/src/createNiftiImageIdsAndCacheMetadata.ts, packages/nifti-volume-loader/src/index.ts, packages/nifti-volume-loader/src/init.ts, packages/nifti-volume-loader/src/internal/index.ts, packages/nifti-volume-loader/src/internal/options.ts, packages/nifti-volume-loader/src/types/LoaderOptions.ts, packages/nifti-volume-loader/src/types/index.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1688
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1403
Adds custom header support to nifti image loader, this will allow people to use auth headers or any headers of their choosing, works for fetches and xhrs.
Closes OHI-1443
=> [OHI-1443] feat(nifti-loader): Add custom header support to nifti loader to support auth headers or any custom headers

packages/tools/src/tools/segmentation/CircleROIStartEndThresholdTool.ts, packages/tools/src/tools/segmentation/RectangleROIStartEndThresholdTool.ts
In nuclear medicine, some quantifications may have different normalization such as SUV lean body mass or glycaemia corrected SUV.
To implement specific quantification we previously add callback definition to override statistics computation or result rendering (stat calculator and getTextLines parameters)
Our current problem is that we want to change the rendered value SUV => SUL, to do this we need to get PatientWeight, PatientSize and PatientSex in the Metadata store.
The probleme we are facing is that the getTextLines callaback is not giving enough context about the measurement especially to retrieve the volumeId/displaySet/SeriesInstanceUID that are needed to link the measurement rendering from the Metadata Store.
So in this PR i add the metadata in the getTextLines of Circle and …
=> fix: passing metadata to getTextLines callback in annotation tools

common/reviews/api/core.api.md, common/reviews/api/dicom-image-loader.api.md, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/computeAutoVoi.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/createViewport.ts, packages/core/src/RenderingEngine/helpers/setDefaultVolumeVOI.ts, packages/core/src/enums/VOILUTFunctionType.ts, packages/core/src/types/CPUFallbackViewport.ts, packages/core/src/types/IImage.ts, packages/core/src/utilities/createSigmoidRGBTransferFunction.ts, packages/core/src/utilities/logit.ts, packages/core/src/utilities/windowLevel.ts, packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts, packages/dicomImageLoader/src/imageLoader/wadouri/metaData/metaDataProvider.ts, packages/dicomImageLoader/src/types/DICOMLoaderIImage.ts, packages/tools/src/tools/WindowLevelRegionTool.ts, packages/tools/src/tools/WindowLevelTool.ts
related https://github.com/OHIF/Viewers/issues/4298
related https://github.com/OHIF/Viewers/issues/4538
This pull request includes an important update to the `toLowHighRange` function in the `packages/core/src/utilities/windowLevel.ts` file. The change adds a conditional check to handle cases where `windowWidth` or `windowCenter` are less than 1, providing a fallback calculation for the `lower` and `upper` values.
Key change:
* [`packages/core/src/utilities/windowLevel.ts`](diffhunk://#diff-6f4cb97bb6e19327efc7d92bc58b84bc28cef3d473fe4547e83ca6dd46bdcb04L44-R55): Added a conditional check in the `toLowHighRange` function to handle cases where `windowWidth` or `windowCenter` are less than 1, and provided a fallback calculation for `lower` and `upper` values.
=> feat(voi): add linear exact voi lut function

packages/core/src/utilities/windowLevel.ts, packages/docs/docs/concepts/cornerstone-core/imageLoader.md, packages/docs/docs/concepts/cornerstone-core/images.md, packages/docs/docs/concepts/cornerstone-core/metadataProvider.md, packages/docs/docs/concepts/cornerstone-core/volumeLoader.md, packages/docs/docs/concepts/cornerstone-tools/annotation/locking.md, packages/docs/docs/concepts/cornerstone-tools/annotation/selection.md, packages/docs/docs/concepts/cornerstone-tools/annotation/visibility.md, packages/docs/docs/concepts/cornerstone-tools/synchronizers.md, packages/docs/docs/concepts/cornerstone-tools/toolGroups.md, packages/docs/docs/getting-started/overview.md, packages/docs/docusaurus.config.js, packages/docs/sidebars.js
Some of the links in the docs are broken, particularly those pointing to API documentation because paths changed.
- Updated links in markdown to point to new API location
- Fixing OHIF community link in header
- Removed links to missing test coverage report
- Small change in jsdoc of toLowHighRange because <= causes errors in Docusaurus
I ran the docs locally while making these changes to verify the new links work.
etc.)
=> docs(web): updating links to API from markdown documentation

common/reviews/api/tools.api.md, packages/tools/src/utilities/voi/colorbar/ViewportColorbar.ts
When `ViewportColorbar` is instantiated, several event listeners are registered. However, there is no method to unregister them.
- Add destroy method to `ViewportColorbar` class
etc.)
Chrome 130.0.6723.117
=> fix(ViewportColorbar): Add destroy method

packages/core/src/RenderingEngine/VideoViewport.ts
When applying a key image to a video range, the playback/selection was broken and the key image only applied to a single image.
Calculate the correct slice range if it isn't provided directly.
Run example videoRange, apply a key image to a range of images and ensure it displays on all the images in that range.
etc.) …
=> fix: Slice range was broken for key image setting on video

packages/tools/examples/annotationVisibility/index.ts, packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/ArrowAnnotateTool.ts, packages/tools/src/tools/annotation/CobbAngleTool.ts
A few tools were missing the implementation for visibility checking before rendering, so when they were set to hidden they were still being rendered anyway.
This has been fixed, and I added most of the measurement tools in the annotation visibility example for easier testing in the future.
Fixes OHIF-1544
Fixes #1741
=> [OHI-1544] fix(annotations): make ArrowAnnotate, CobbAngle and Angle check for visibilty status before rendering

packages/core/src/utilities/sortImageIdsAndGetSpacing.ts
Not sure why the logic was like this, it didn't makes sense
zSpacing also should not be negative
=> fix(sortImageIdsAndGetSpacing): sliceThickness and spacingBetweenSlices in case of nonstrict spacing

packages/core/src/loaders/cornerstoneStreamingImageVolumeLoader.ts
When using wadouri: scheme with streaming image volume loader, the first, middle and possibly last images must be cached so that the volume can be constructed from metadata. Even when the needed images are cached, it seems that re-requesting them via the loadpoolmanager takes pretty long.
This change first checks if the required images are already in the cache before getting the loadPoolManager involved, and skips it if so. This will only noticeably speed up volume creation when all the needed images are already cached, for instance when converting a stack to a volume.
etc.) …
=> Check cache when prefetching wadouri images for volume

packages/core/examples/webLoader/hardcodedMetaDataProvider.ts
Users that base a web image metadata provider off the `hardcodedMetaDataProvider` in the examples will find measurements are always displayed in mm, even if `pixelSpacing` is removed. `usingDefaultValues` must also be set.
Added `usingDefaultValues` to `hardcodedMetaDataProvider` and brief explanation
Run ` yarn run example webLoader` to run the webLoader example that uses the `hardcodedMetaDataProvider`
etc.)
=> docs(webLoader): Adding usingDefaultValues to hardcodedMetaDataProvider

common/reviews/api/tools.api.md, packages/tools/examples/stackAnnotationTools/index.ts, packages/tools/src/drawingSvg/drawArrow.ts, packages/tools/src/drawingSvg/drawHeight.ts, packages/tools/src/drawingSvg/drawLine.ts, packages/tools/src/drawingSvg/drawPolyline.ts, packages/tools/src/stateManagement/annotation/config/ToolStyle.ts, packages/tools/src/store/addEnabledElement.ts, packages/tools/src/tools/annotation/ArrowAnnotateTool.ts, packages/tools/src/tools/base/AnnotationTool.ts, packages/tools/src/types/AnnotationStyle.ts
fix #1671
Using `marker` html def instead of two separate arrows for better control over arrow
| size 1 |  size 2 |  size 3 |  size 4 |
|---|---|---|---|
|![1](https://github.com/user-attachments/assets/189c7828-7275-479a-b57e-4a828581c8ea)|![2](https://github.com/user-attachments/assets/d26afa7d-78cc-40f7-be35-8612dd2105ca)|![3](https://github.com/user-attachments/assets/7b1557f0-1465-4321-a033-2060bc747021)|![4](https://github.com/user-attachments/assets/76d894f2-7598-4222-babd-a56808d64b04)|
By default, ArrowAnnotateTool uses the previous version, but you can opt for the new one by using the following code: 
```js
toolGroup.addTool(ArrowAnnotateTool.toolName, {
arrowHeadStyle: 'standard',
});
```
To change the marker head size, you can use the ToolStyle API. For example, you can do …
=> fix(ArrowAnnotate): use svg marker to draw the arrow

common/reviews/api/core.api.md, packages/core/src/RenderingEngine/Viewport.ts, packages/core/src/types/IViewport.ts, packages/core/src/utilities/actorCheck.ts
Flip property was being lost on new image renders, now it's returned as part of the view presentation so it's always maintained.
Fixes: https://github.com/OHIF/Viewers/issues/4729
=> [OHI-1588] fix(flip): return flip as part of view presentation

packages/core/src/loaders/imageLoader.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1747
This pull request includes a small but important change to the `cancelLoadAll` function in the `imageLoader.ts` file. The change adds a check to ensure that `requestDetails` is not null before proceeding with further operations.
* [`packages/core/src/loaders/imageLoader.ts`](diffhunk://#diff-39af41f333474ee0ab1e58aebc1c81f24defca55daaa984c625b2fc0489e348cR610-R613): Added a null check for `requestDetails` in the `cancelLoadAll` function to prevent potential runtime errors.
=> fix(imageLoader): Resolve TypeError when canceling image load requests

packages/core/src/RenderingEngine/StackViewport.ts
Window level was getting reset after being modified by the user, specifically on MR series. This fixes the issue
Before:
After:
Fixes #1770
Fixes OHI-1579
=> [OHI-1579] fix(window-level): prevent window level from being reset after modified by user

common/reviews/api/ai.api.md, common/reviews/api/core.api.md, common/reviews/api/tools.api.md, packages/core/src/init.ts, packages/core/src/types/Cornerstone3DConfig.ts, packages/tools/examples/labelmapInterpolation/index.ts, packages/tools/src/tools/segmentation/strategies/compositions/labelmapInterpolation.ts, packages/tools/src/workers/polySegConverters.js
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1792
This pull request includes several changes to improve the handling of dynamic imports and update the interpolation functionality. The most important changes include converting `peerImport` to return a `Promise`, updating the interpolation buttons and functionality, and handling dynamic imports for specific modules.
* [`packages/tools/src/tools/segmentation/strategies/compositions/labelmapInterpolation.ts`](diffhunk://#diff-2a2fe4d662ad7d9ee559423704f2f3fb05bf0d04827eac86e2c98e6e0b8ae273L1-R22): Replaced static imports with `peerImport` for the `morphological-contour-interpolation` module. [[1]](diffhunk://#diff-2a2fe4d662ad7d9ee559423704f2f3fb05bf0d04827eac86e2c98e6e0b8ae273L1-R22) …
=> fix(package): use itk morphology filter and polyseg dynamically

packages/tools/src/tools/segmentation/strategies/compositions/labelmapInterpolation.ts, packages/tools/src/tools/segmentation/strategies/utils/getItkImage.ts, packages/tools/src/utilities/cine/playClip.ts
This pull request includes several changes to improve the segmentation and cine play functionalities in the project. The most important changes include updating the `getItkImage` function to be asynchronous, modifying the usage of `numTimePoints` and `timePointIndex` in the cine play context, and adding detailed documentation for the `getItkImage` function.
Improvements to segmentation functionality:
* [`packages/tools/src/tools/segmentation/strategies/compositions/labelmapInterpolation.ts`](diffhunk://#diff-2a2fe4d662ad7d9ee559423704f2f3fb05bf0d04827eac86e2c98e6e0b8ae273L42-R45): Updated the `getItkImage` function call to be asynchronous.
* [`packages/tools/src/tools/segmentation/strategies/utils/getItkImage.ts`](diffhunk://#diff-21cd09eefc1e48abb77b8b89998bd671b4328df847ef73c21dde05cfb43 …
=> fix: the rest of packaging issue and move from timePointIndex to dimensionGroup

bun.lock, package.json, packages/tools/src/tools/CrosshairsTool.ts, packages/tools/src/tools/displayTools/Labelmap/addLabelmapToElement.ts, yarn.lock
This pull request includes updates to dependencies, improvements to error handling, and enhancements to the logic for handling labelmaps in the `CrosshairsTool` and `Labelmap` tools. The most important changes are outlined below:
* Updated the `@microsoft/api-extractor` package from version 7.48.0 to 7.49.2 in `package.json`.
* Added a check to return early if `enabledElement` is not found in the `CrosshairsTool` class, improving robustness.
* Added a dimension check to decide whether to use independent components for blending in the `addLabelmapToElement` function. This ensures that if dimensions don't match, the code falls back to regular volume addition.
=> fix(labelmap): only show labelmap as independent component on mip if same size

packages/core/src/RenderingEngine/Viewport.ts
fyi @IbrahimCSAE 
The change addresses the handling of flip operations to reduce flickering during rendering.
Rendering improvements:
* [`packages/core/src/RenderingEngine/Viewport.ts`](diffhunk://#diff-820bdf434bace4e9e622da846acb70b98bf9fd157b6392bc2b3a78d03bdcea76R1880-R1887): Added a check for `flipHorizontal` or `flipVertical` to ensure the view presentation requires a flip, which triggers another re-render to take effect. This aims to reduce flickering by waiting for the camera and flip operations to complete together before rendering.
=> fix(viewport): Prevent flickering during viewport flip operations

packages/dicomImageLoader/src/decodeImageFrameWorker.js
Github Issue - https://github.com/cornerstonejs/cornerstone3D/issues/1796
The progressive loading is failing with the error
The actual issue is in the dicomImageLoader package in the decodeImageFrameWorker.js where the `type` is being sent as `String` to the `validatePixelDataType` function where it expects to be `PixelDataTypedArray`.
etc.)
- [] The documentation page has been updated as necessary for any public …
=> fix: incorrect check for validating pixel data array type

packages/tools/src/stateManagement/segmentation/SegmentationStyle.ts
The `copyActiveToInactiveIfNotProvided` method ensures that inactive segmentation styles inherit values from their active counterparts when not explicitly set. However, the previous implementation always assigned values, even when an inactive style property was already defined. This led to unintentional overwriting of user-defined inactive styles.
- Replaced direct assignments with nullish coalescing assignment (`??=`) to only assign values when the inactive properties are null or undefined.
etc.)
130.0.6723.117
[script]: …
=> Fix: Inactive styles being unintentionally overwritten in copyActiveToInactiveIfNotProvided

packages/tools/src/utilities/segmentation/getSVGStyleForSegment.ts
Fixes #1832 
While rendering, segment styles such as opacity, fill etc do not consider active segment based on its index.
Active segmentationId along with the segmentIndex should determine whether a segment is active or not.
https://github.com/user-attachments/assets/5c0491e6-0d0b-4d94-8b7e-8882d0d348f8
etc.)
- [] "OS: 
- [] "Browser:
[blog]: …
=> fix for changing opacity based on segment index

packages/tools/src/tools/CrosshairsTool.ts
fix #1822
Support HDPI screens in CrosshairsTool
| Before | After |
| -------- | ------- |
| ![before](https://github.com/user-attachments/assets/017f1fa3-43c8-4517-b99e-1c0638d85ee2) | ![aftre](https://github.com/user-attachments/assets/a804c1e4-fca6-4a66-9389-065c807b9d64) |
etc.)
=> fix(CrosshairsTool): support HPDI screens in CrosshairsTool 

.circleci/config.yml, packages/tools/src/tools/segmentation/strategies/compositions/ensureImageVolume.ts, packages/tools/src/tools/segmentation/strategies/utils/getStrategyData.ts
* Fixed variable redeclaration in `ensureImageVolume.ts`
* Updated null checks in `getStrategyData.ts` to use more robust comparison
etc.)
- [] "OS: 
- [] "Browser:
=> fix(segmentation): resolve variable declaration and null check issues

packages/core/src/webWorkerManager/webWorkerManager.js, packages/tools/examples/labelmapStatistics/index.ts
This pull request includes several changes to improve the efficiency and performance of the `CentralizedWorkerManager` class and to clean up the `displayStat` function. The most important changes include removing unused options and redundant code.
Improvements to `CentralizedWorkerManager`:
* Removed the `options` property from the worker initialization as it was not being used. (`packages/core/src/webWorkerManager/webWorkerManager.js`)
* Removed the augmentation of `args` with `workerProperties.options` in the worker method call, as this was unnecessary. (`packages/core/src/webWorkerManager/webWorkerManager.js`)
Code cleanup in `displayStat` function:
* Removed the unused `viewport` variable from the `calculateStatistics` function. (`packages/tools/examples/labelmapStatistics/index.ts`)
=> fix(worker): should not change type of input

packages/tools/src/enums/ChangeTypes.ts, packages/tools/src/tools/SculptorTool.ts, packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/ArrowAnnotateTool.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/CircleROITool.ts, packages/tools/src/tools/annotation/CobbAngleTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/annotation/planarFreehandROITool/drawLoop.ts, packages/tools/src/types/AnnotationTypes.ts, packages/tools/src/types/ToolSpecificAnnotationTypes.ts, packages/tools/src/utilities/index.ts, packages/tools/src/utilities/setAnnotationLabel.ts
Updated ChangeType parameter value in AnnotationModifiedEventDetail for LengthTool
The ```ChangeType```parameter in ```AnnotationModifiedEventDetail``` now returns ```StatsUpdated``` following the execution of the ```_calculateCachedStats``` function, it returns ```HandlesUpdated``` when the handle position is modified.
The ```initialSetup``` change type can be fired from addNewAnnotation(), we currently left it out. Please let us know if you think it should be there as cs3d already has a annotation created event for it. Should we remove the change type InitialSetup ?
etc.) …
=> Updating proper values for ChangeType parameter in AnnotationModifiedEventDetail.

packages/core/src/utilities/logger.ts
Logger accesses `window` object which can be `undefined` if used in wasm worker. For example, check the [Volume Labelmap to Surface](https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptosurface) example - segment some part and try to convert the labelmap to surface segmentation, you'll get the error below:
`Uncaught (in promise) ReferenceError: window is not defined`
Added check for undefined window. If window is undefined, then skip setting the log level.
Tested by running the example mentioned above and making sure it runs correctly.
etc.)
- [] The documentation page has been updated …
=> Fix undefined window error in logger

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
calling scroll on a volume viewport does not actually scroll the viewport. it sets camera properties (focal point and position) but it needs a render to get those committed to viewport.
call render method inside the scroll method of baseVolumeViewport
etc.)
- [] "OS: 
- [] "Browser:
=> (volume-viewport): call render for the scroll to take effect

packages/nifti-volume-loader/src/cornerstoneNiftiImageLoader.ts
Fixes #1911
Add `decache` function to returned `ImageLoadObject` in `cornerstoneNiftiImageLoader` to remove nifti file from `nifti-volume-loader` internal cache on `purgeCache` call.
Now `purgeCache` cleans up the internal cache of `nifti-volume-loader`.
Memory usage before:
Memory usage after:
Steps to reproduce:
1. Add file with next content to nifti-volume-loader examples at packages/nifti-volume-loader/examples/niftiMemoryLeak/index.ts
```javascript
import {
RenderingEngine,
Enums,
imageLoader,
cache,
resetInitialization,
} from '@cornerstonejs/core';
import {
cornerstoneNiftiImageLoader,
createNiftiImageIdsAndCacheMetadata,
} from '@cornerstonejs/nifti-volume-loader';
import { initDemo } from '../../../../utils/demo/helpers';
// This is for debugging purposes
console.warn(
'Click on …
```
=> fix(nifti-volume-loader): add decache function to cornerstoneNiftiImageLoader

packages/core/src/utilities/calculateSpacingBetweenImageIds.ts
The code that calculates Z spacing:
```typescript
spacing =
Math.abs(
distanceImagePairs[numImages - 1].distance -
distanceImagePairs[0].distance
) /
(numImages - 1);
```
causes a division by 0 when `numImages === 1`.
The NaN ends up in some vtk shader and throws a syntax error.
Reuse existing fallback for spacing === 0
=> fix: avoid NaN Z spacing if possible

packages/tools/examples/labelmapMIP/index.ts, packages/tools/src/eventListeners/segmentation/labelmap/onLabelmapSegmentationDataModified.ts, packages/tools/src/eventListeners/segmentation/labelmap/performStackLabelmapUpdate.ts, packages/tools/src/eventListeners/segmentation/labelmap/performVolumeLabelmapUpdate.ts, packages/tools/src/tools/displayTools/Labelmap/addVolumesAsIndependentComponents.ts
This pull request includes several changes to the `labelmapMIP` example and the segmentation event listeners in the `cornerstonejs` tools package. The main focus is on refactoring the code to improve modularity and efficiency.
* [`packages/tools/src/eventListeners/segmentation/labelmap/onLabelmapSegmentationDataModified.ts`](diffhunk://#diff-2237a6c93d913434002f366c92e8ba5d31aed0cbdf52427037c650063673c9a2L2-R12): Refactored to use new helper functions `performVolumeLabelmapUpdate` and `performStackLabelmapUpdate` for updating labelmap data. Removed inlined code for these updates. [[1]](diffhunk://#diff-2237a6c93d913434002f366c92e8ba5d31aed0cbdf52427037c650063673c9a2L2-R12) [[2]](diffhunk://#diff-2237a6c93d913434002f366c92e8ba5d31aed0cbdf52427037c650063673c9a2L23-R24) …
=> perf(segmentation): Enhance labelmapmip performance

packages/core/src/RenderingEngine/StackViewport.ts
Scrolling before the viewport is ready or on a blank viewport can cause NPEs when trying to fetch undefined imageIds.  Also, scrolling backwards should be able to loop, but can't.
etc.)
- [] "OS: 
- [] "Browser:
=> fix: Scrolling sometimes set NaN and won't loop backwards

packages/tools/src/tools/MagnifyTool.ts
Addresses: https://github.com/cornerstonejs/cornerstone3D/issues/1926
Before:
Magnify viewport wouldn't match original viewport's rotation
After:
Magnify viewport matches original viewport's rotation
etc.)
- [] "OS: 
- [] "Browser:
=> fix: magnify tool rotation

packages/tools/src/tools/segmentation/SegmentBidirectionalTool.ts, packages/tools/src/types/ToolSpecificAnnotationTypes.ts
Fixes type errors occurring on the class SegmentBidirectionalTool.
Updated the `BidirectionalAnnotation` to make label optional since its used in `SegmentBidirectionalTool` where and the label doesn't exits in the `SegmentBidirectionalAnnotation` type.
Making the label optional fixes type errors when building and running using cornerstone:
Full error
```
Error: node_modules/@cornerstonejs/tools/dist/esm/tools/segmentation/SegmentBidirectionalTool.d.ts:5:15 - error TS2417: Class static side 'typeof SegmentBidirectionalTool' incorrectly extends base class static side 'typeof BidirectionalTool'.
The types of 'hydrate(...).data' are incompatible between these types.
Property 'label' is missing in type '{ cachedStats: { [targetId: string]: { length: number; width: number; unit: string; }; }; …
```
=> fix: SegmentBidirectionalTool hydration type error

packages/core/src/RenderingEngine/StackViewport.ts, packages/tools/examples/localCPU/index.ts
In our infra we are using the `2.x` branch (latest release, currently 2.19.16), recently updated from `1.x`. We rely on the CPU fallback renderer as in our use case GPU rendering is not possible. Shortly after the 2.0 upgrade, we started receiving feedback about certain DICOMs not rendering correctly, the issue is captured in #1916.
Initial investigation pointed to the CPU fallback renderer being broken, as the [local viewer](https://www.cornerstonejs.org/live-examples/local.html) did not have any trouble displaying the image. While further investigating, I have discovered that the example that uses forced CPU rendering doesn't work, this is captured in #1907 and the PR also addresses this issue.
After fixing the CPU fallback example I have managed to trace the source of the breakage to …
=> fix(cpu): broken CPU fallback renderer & example fix

packages/tools/src/tools/annotation/LabelTool.ts
Fixes #1937
The label tool was incorrectly rendering annotations even when visibility was disabled.
This PR ensures that annotations are only displayed when their visibility flag is set to true.
Added a visibility check in the label tool's rendering logic.
Modified the annotation rendering function to respect the visible flag.
Before: Labels were visible even when visibility is set to false.
After: Labels now respect visibility settings.
fix(label-tool): add visibility check for annotations in rendering
etc.)
=> fix(label-tool): add visibility check for annotations in rendering

packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/CircleROITool.ts, packages/tools/src/tools/annotation/CobbAngleTool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/HeightTool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/LivewireContourTool.ts, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/annotation/SplineROITool.ts, packages/tools/src/tools/annotation/UltrasoundDirectionalTool.ts, packages/tools/src/tools/annotation/VideoRedactionTool.ts
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1489
fixes https://github.com/cornerstonejs/cornerstone3D/issues/1491
fixes https://github.com/cornerstonejs/cornerstone3D/issues/939
This pull request includes several changes to various annotation tools to ensure that the `triggerAnnotationModified` function is only called if the annotation was invalidated. Additionally, there are some minor import updates and a typo correction.
Changes to ensure `triggerAnnotationModified` is called only if invalidated:
* [`packages/tools/src/tools/annotation/AngleTool.ts`](diffhunk://#diff-cc523708d731a68e025c3aa9101382e1df131d7f2b214c501e7937caa138b340R878-R884): Added a check to call `triggerAnnotationModified` only if the annotation was invalidated.
* …
=> fix(annotation-tools): trigger annotation modified only if invalidated across multiple tools

packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/renderColorImage.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/renderPseudoColorImage.ts, packages/core/src/RenderingEngine/helpers/cpuFallback/rendering/storedColorPixelDataToCanvasImageData.ts
Color CPU rendering in node or from an RGB array buffer is broken, as is palette color CPU rendering.
Use the new createCanvas to allow node rendering of color images
Fix the offsets for storing array to color image
etc.)
- [] "OS: 
- [] "Browser:
=> fix: Color rendering in node

packages/core/src/RenderingEngine/BaseVolumeViewport.ts, packages/core/src/RenderingEngine/StackViewport.ts, packages/core/src/RenderingEngine/VolumeViewport.ts, packages/core/src/RenderingEngine/VolumeViewport3D.ts, packages/tools/src/eventListeners/mouse/mouseDownListener.ts
This pull request introduces several changes to the `BaseVolumeViewport` class and related classes in the `RenderingEngine` package. The changes include new methods, imports, and logic to handle acquisition planes and referenced image IDs.
**Key Changes:**
* Added a new abstract method `isInAcquisitionPlane` to the `BaseVolumeViewport` class. This method is implemented in the `StackViewport`, `VolumeViewport`, and `VolumeViewport3D` subclasses to determine if the current viewport is in the acquisition plane. [[1]](diffhunk://#diff-d8f8b6f60e39bf30c7ddecc31bda70056c63091aad137431809e7cf16eadd3b9R698-R699) [[2]](diffhunk://#diff-68d9d8eea6b516148b349d78d67774d70ef1a0a0896f34f003fb3aab336802bfR3300-R3303) [[3]](diffhunk://#diff-b4f9e61259732a6dbcce1198b86f0b30fc3f14f8880f78a15c3230e0b676caeeR …
=> feat: implement setViewReference via referencedImageId in the volumeViewport

packages/tools/src/tools/segmentation/SegmentSelectTool.ts
This pull request includes changes to the `SegmentSelectTool` class in the `packages/tools/src/tools/segmentation` directory to improve its functionality and maintainability. The most important changes include importing a new enum and adding a condition to the `mouseMoveCallback` method.
Improvements to `SegmentSelectTool`:
* [`packages/tools/src/tools/segmentation/SegmentSelectTool.ts`](diffhunk://#diff-6c427f0f1049a9b52b680f86c71567a139b2f15176a15a961175bdf1ced55e1aR21): Added import for `ToolModes` enum from `../../enums` to utilize tool modes in the class.
* [`packages/tools/src/tools/segmentation/SegmentSelectTool.ts`](diffhunk://#diff-6c427f0f1049a9b52b680f86c71567a139b2f15176a15a961175bdf1ced55e1aR53-R56): Modified the `mouseMoveCallback` method to include a condition that checks …
=> feat: add mode check in mouseMoveCallback for SegmentSelectTool

.github/workflows/format-check.yml, .github/workflows/playwright.yml, packages/docs/netlify.toml, packages/docs/sidebars.js, playwright.config.ts
This pull request includes changes to the Playwright testing setup and documentation configuration. The most important changes involve updating the paths for the HTML report output and adding a redirect for the Playwright coverage report.
Updates to Playwright testing setup:
* [`.github/workflows/playwright.yml`](diffhunk://#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3L56-R61): Updated the `run` command for merging reports and the `path` for uploading the HTML report to use the new directory `packages/docs/static/playwright-report`.
* [`playwright.config.ts`](diffhunk://#diff-f679bf1e58e8dddfc6cff0fa37c8e755c8d2cfc9e6b5dc5520a5800beba59a92L16-R16): Changed the `outputFolder` for the HTML reporter to `./packages/docs/static/playwright-report`.
Documentation …
=> test: add coverage

packages/tools/src/tools/annotation/AngleTool.ts, packages/tools/src/tools/annotation/ArrowAnnotateTool.ts, packages/tools/src/tools/annotation/BidirectionalTool.ts, packages/tools/src/tools/annotation/CircleROITool.ts, packages/tools/src/tools/annotation/EllipticalROITool.ts, packages/tools/src/tools/annotation/LengthTool.ts, packages/tools/src/tools/annotation/ProbeTool.ts, packages/tools/src/tools/annotation/RectangleROITool.ts, packages/tools/src/tools/annotation/SplineROITool.ts, packages/tools/src/tools/segmentation/SegmentBidirectionalTool.ts
Tool hydrate methods now allow passing a tool instance in the options object, which is unnecessarily added to the annotation metadata. This then breaks serialization when trying to do structuredClone in the saveAnnotations() method.
Explicitly remove the `toolInstance` parameter from the options object, so that it is not included in metadata.
etc.)
- [] "OS: 
- [] "Browser:
[script]: …
=> fix(tools): Prevent tool instance from breaking annotation serialization

.github/workflows/build-docs.yml
This pull request includes changes to the `.github/workflows/build-docs.yml` file to update the way GitHub tokens are referenced in the workflow.
* Updated `GH_TOKEN` to use `${{ github.token }}` instead of `${{ secrets.GH_TOKEN }}` for the `find_pr_run` step.
* Updated `GH_TOKEN` to use `${{ github.token }}` instead of `${{ secrets.GH_TOKEN }}` for the `Download coverage artifact from PR run` step.
=> fix: artifact for test

.github/workflows/build-docs.yml
This pull request includes a small change to the `.github/workflows/build-docs.yml` file. The change removes the `--frozen-lockfile` option from the `bun install` command used to install documentation dependencies.
* [`.github/workflows/build-docs.yml`](diffhunk://#diff-4fdc48ab490b670c90974725b8e3d399b24c03d6d09563acf8ea87d4113930fbL80-R80): Removed the `--frozen-lockfile` option from the `bun install` command in the `Install docs dependencies` step.
=> fix: artifact for test finally

.github/workflows/build-docs.yml
This pull request includes a small change to the `.github/workflows/build-docs.yml` file. The change adds an environment variable to enable debug logging for GitHub Actions.
* [`.github/workflows/build-docs.yml`](diffhunk://#diff-4fdc48ab490b670c90974725b8e3d399b24c03d6d09563acf8ea87d4113930fbR8-R10): Added `ACTIONS_STEP_DEBUG: true` under the `env` section to enable debug logging.
=> fix: artifact for test with debug

packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts, packages/adapters/src/adapters/helpers/copySeriesTags.ts, packages/adapters/src/adapters/helpers/copyStudyTags.ts, packages/adapters/src/adapters/helpers/index.ts
https://github.com/cornerstonejs/cornerstone3D/pull/1887, recently merged, introduced a bug:
The `packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts` calls the `contentItem` method of the `TID1500MeasurementReport`:
This method, in turn, relies on the `SeriesInstanceUID` of the derivation source datasets, which is always undefined with the changes of the PR above:
This was causing an error when trying to save measurements to different Series in the same SR. See next section to see an example.
Before:
After:
etc.) …
=> fix(copyStudyTags): missing SeriesInstanceUID

packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/annotation/ProbeTool.ts
Working with Cornerstone tools I have found a few minor bugs and issues with `ProbeTool` and `PlanarFreehandRoiTool`, which this PR addresses:
* `PlanarFreehandRoiTool` - include the `annotationId` in the `styleSpecifier` so that annotation level styles are respected when drawing the textbox.
* `ProbeTool` - call `isAnnotationVisible` in order to respect the probe annotation's object's visibility.
* `ProbeTool` - put offset of text from the probe coordinates into to `configuration` so that the consumer can configure this offset if needed.
etc.)
- [] The documentation page has been updated as necessary …
=> fix(tools): tweaks to Probe and PlanarFreehandRoi tools

packages/tools/src/utilities/segmentation/getStatistics.ts, packages/tools/src/workers/computeWorker.js
addresses https://github.com/OHIF/Viewers/issues/4954
This pull request introduces a new `unit` parameter to improve flexibility in volume statistics calculations. The changes ensure that the `unit` can be dynamically specified instead of being hardcoded, enhancing the functionality of the segmentation utilities and compute worker.
* [`packages/tools/src/utilities/segmentation/getStatistics.ts`](diffhunk://#diff-6964b8509da89eeeae1cef8b3a2346e873273c05240486ccb93e4a06dae6a327R145): Added the `unit` parameter to the `calculateVolumeStatistics` function arguments, enabling dynamic specification of measurement units.
* [`packages/tools/src/workers/computeWorker.js`](diffhunk://#diff-abea066247d5fca6f24c869d18d686df8eb6a0c4bb33961d70a6689903096b43L149-R149): Updated the …
=> fix(statistics): include unit in volume statistics calculation

packages/core/src/RenderingEngine/WSIViewport.ts
Ticket number: 8925455119
Changed the center of canvas calculation to use centerIndex from the camera in getCamera.
Run the wsi example.
Click on the mouse wheel and drag to pan.
Panning is not moving correctly before the change and correctly after.
=> fix: panTool in wsi

packages/tools/src/tools/displayTools/Contour/contourHandler/handleContourSegmentation.ts
This pull request includes a minor change to the `handleContourSegmentation.ts` file. The change removes a call to `viewport.resetCamera()` in the `addContourSetsToElement` function.
Now that we've switched from VTK actors to only annotations in contours, we no longer need a reset camera.
=> fix(contourHandler): remove unnecessary camera reset in handleContourSegmentation function

packages/tools/src/config.ts
Fixes [#1880](https://github.com/cornerstonejs/cornerstone3D/issues/1880)
Fix the type of `updateSurfaceData` from `ComputeRepresentationFn<SurfaceSegmentationData>` to `ComputeRepresentationFn<void>`.
It will have a type error when we add `addons` in the cornerstone tools init function:
```typescript
await csToolsInit({
addons: {
polySeg, // type error occurs here
},
});
```
The detail of the type error:
```
Type 'typeof import("/Users/xxx/Desktop/repo/cornerstone3D/packages/polymorphic-segmentation/src/index")' is not assignable to type 'PolySegAddOn'.
The types returned by 'updateSurfaceData(...)' are incompatible between these types.
Type 'Promise<void>' is not assignable to type 'Promise<SurfaceSegmentationData>'.
Type 'void' is not assignable to type …
```
=> fix(polyseg): fix updateSurfaceData type error

packages/core/src/utilities/colormap.ts, packages/dicomImageLoader/src/decodeImageFrameWorker.js
This pull request introduces significant improvements to the handling of scaling and threshold logic in the `colormap` utility and the DICOM image loader. The changes focus on modularizing scaling calculations, improving error handling, and ensuring robust data validation.
* Introduced a new helper function `_calculateScaledMinMax` to centralize and simplify the calculation of scaled minimum and maximum values based on various scaling parameters, such as `rescaleSlope`, `rescaleIntercept`, `suvbw`, and `doseGridScaling`. This reduces code duplication and improves maintainability (`packages/dicomImageLoader/src/decodeImageFrameWorker.js`).
* Replaced inline scaling calculations with calls to `_calculateScaledMinMax` in multiple functions, such as `postProcessDecodedPixels` and …
=> fix: enhance opacity threshold handling and refactor scaling logic

packages/tools/src/utilities/segmentation/VolumetricCalculator.ts
Pixel spacing is in mm, so there is no need to multiply the volume scale by 1000 for cubic millimeter units.
Removed the multiplication of the cubic pixel spacing by 1000.
1. Open the following OHIF URL https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331
2. Navigate to roughly the middle image of the stack.
3. Add a new segmentation.
4. Segment using a 10mm sphere tool and draw/segment a precise as possible 10mm radius sphere. The volume for such a sphere should be about 4/3 * Pi * 10³ = 4188mm³
5. Hover over the segment added and note the volume it should be about 4188mm³. Previous to this change the volume reported in OHIF was about 1000 times this value (see the screen capture below)
semantic-release format and …
=> fix(segmentation): The volume value for a segmentation is 1000 times too large

bun.lock, packages/adapters/package.json, packages/adapters/src/adapters/Cornerstone3D/Angle.ts, packages/adapters/src/adapters/Cornerstone3D/ArrowAnnotate.ts, packages/adapters/src/adapters/Cornerstone3D/BaseAdapter3D.ts, packages/adapters/src/adapters/Cornerstone3D/Bidirectional.ts, packages/adapters/src/adapters/Cornerstone3D/CircleROI.ts, packages/adapters/src/adapters/Cornerstone3D/CobbAngle.ts, packages/adapters/src/adapters/Cornerstone3D/EllipticalROI.ts, packages/adapters/src/adapters/Cornerstone3D/Length.ts, packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts, packages/adapters/src/adapters/Cornerstone3D/PlanarFreehandROI.ts, packages/adapters/src/adapters/Cornerstone3D/Probe.ts, packages/adapters/src/adapters/Cornerstone3D/RectangleROI.ts, packages/ai/package.json, packages/docs/package.json, packages/tools/src/tools/annotation/PlanarFreehandROITool.ts, packages/tools/src/tools/segmentation/LabelmapBaseTool.ts, packages/tools/src/types/AnnotationTypes.ts, packages/tools/src/utilities/planar/filterAnnotationsWithinSlice.ts, yarn.lock
TID.300 measurements can now be defined using either 2D or 3D points with the [latest dcmjs changes](https://github.com/dcmjs-org/dcmjs/pull/432). This is controlled by the use of either `SCOORD` (2D) or `SCOORD3D` (3D) in the **Measurement Value Sequence**, as described in the TID.320 section of TID.300:  
🔗 [DICOM TID.320 Reference](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_320)
TID.1501 defines the reference information for the SCOORD3D points:
🔗 [DICOM TID.1501 Reference](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1501)
This pull request introduces support for selecting between `SCOORD` and `SCOORD3D` encodings in several TID.300 measurement types, including:
- Length  
- Bidirectional  
- …
=> feat: save scoord3d for tools

packages/core/src/RenderingEngine/BaseVolumeViewport.ts
This pull request includes a minor update to the `BaseVolumeViewport` class in the `RenderingEngine` module. The change ensures that `findMatchingColormap` returns an empty object (`{}`) as a fallback when no matching colormap is found.
* [`packages/core/src/RenderingEngine/BaseVolumeViewport.ts`](diffhunk://#diff-d8f8b6f60e39bf30c7ddecc31bda70056c63091aad137431809e7cf16eadd3b9L1145-R1145): Updated the `matchedColormap` assignment to include a fallback value of `{}` if `findMatchingColormap` returns `undefined` or `null`.
=> fix: fallback for colormap not known

packages/tools/src/tools/annotation/EllipticalROITool.ts
Motivated by OHIF bug https://github.com/OHIF/Viewers/issues/5002.
EllipticalROITool.isPointNearTool now mimics what drawEllipseByCoordinates for rotated ellipses.
1. Run the stackannotationtools
2. Add several ellipse tool markups.
3. Rotate the image by 90, 180 or 270 degrees.
4. Hover over the edge of ANY ellipse drawn. The ellipse should highlight.
5. Add one or more ellipses on the rotated image.
6. Hover over the edge of ANY ellipse drawn. The ellipse should highlight.
etc.)
=> fix(ellipse): EllipticalROITool.isPointNearTool now mimics what drawEllipseByCoordinates for rotated ellipses.

packages/tools/src/tools/TrackballRotateTool.ts, utils/demo/helpers/addManipulationBindings.ts
Ticket: 8968515758
Enable control of the resolution when 3D rotating for low end PCs.
Added configuration item to the tool.
Added example of how to use in AddManipulationBindings - example.
Change the value from default of 2 to 32.
etc.)
=> feat(trackballRotateTool):  rotate resolution configuration

packages/tools/src/enums/Events.ts, packages/tools/src/eventListeners/annotations/contourSegmentation/contourSegmentationCompleted.ts, packages/tools/src/tools/annotation/SplineContourSegmentationTool.ts, packages/tools/src/tools/annotation/SplineROITool.ts, packages/tools/src/utilities/contourSegmentation/convertContourSegmentation.ts, packages/tools/src/utilities/contourSegmentation/index.ts
This pull request introduces a new feature for handling spline annotations in the `SplineROITool` and adds a utility function to convert contour segmentation annotations to a standardized format. The key changes include adding event listeners for annotation completion, enabling a "simplified spline" mode, and implementing the `convertContourSegmentationAnnotation` utility.
* Added a "simplified spline" mode in the tool's configuration. When enabled, it converts spline annotations into freehand contour annotations upon completion. (`[packages/tools/src/tools/annotation/SplineROITool.tsR126](diffhunk://#diff-a6d3d8b5adc48bda00b5cc45ff28a1e19dc3488d87d40798b8b9b7500d93b22dR126)`)
* Introduced event listeners to handle annotation completion events, with methods to initialize and clean up …
=> Add simplified spline configuration

packages/core/src/RenderingEngine/VolumeViewport.ts
This PR fixes a regression introduced by the recent reformatting PR, which inadvertently broke support for the ACQUISITION orientation mode.
Issue:
The reformatting implementation does not support ACQUISITION orientation, but the reformatting PR had rearranged conditional branches in a way that overlooked the specific check for acquisition mode, resulting in unexpected behavior.
Fix:
The condition order has been updated to explicitly prioritize the ACQUISITION check. This ensures that if the user selects acquisition orientation, the system correctly routes and processes it before falling through to other conditions.
Impact:
Users can now reliably select and use the ACQUISITION orientation mode again.
semantic-release …
=> fix(acquisition): fix bug in acquisition mode

packages/tools/src/tools/segmentation/SegmentLabelTool.ts
Using the same segment color with the segmentLabel tool as requested here: https://github.com/OHIF/Viewers/pull/5164#issuecomment-3012979663
Related to https://github.com/OHIF/Viewers/issues/4600
etc.)
- [] "OS: 
- [] "Browser:
=> feat: add segmentLabel color

packages/core/src/utilities/asArray.ts, packages/core/src/utilities/historyMemo/index.ts, packages/core/src/utilities/index.ts, packages/tools/examples/toolHistoryGrouping/index.ts, packages/tools/src/tools/base/BaseTool.ts, utils/ExampleRunner/example-info.json
Currently, if you have a batch of actions, such as clearing multiple annotations at once, cornerstone is not capable of track that and undo/redo these batched actions.
This PR introduces an api of start/end recording, which will enable consumer apps to group actions that are related. 
Example of Before/After with OHIF
Before:
https://github.com/user-attachments/assets/a8bc2197-04bf-4199-8ef9-0cf46f7c1fd2
After:
https://github.com/user-attachments/assets/a0f44eec-ee75-405c-b060-a43f99daee0f
etc.)
- [] "OS: …
=> feat: enable historyMemo action grouping

packages/tools/src/tools/WindowLevelTool.ts
**Current behavior**
When trying to use the `WindowLevelTool` with NIFTI volumes, I noticed that the behavior is not as expected. Specifically, the window level is adapted very slowly (big mouse drag movements required) when we load 3D volumes with high resolution / dynamic range.
**Expected behavior**
`WindowLevelTool` can be used similarly for volumes with different dynamic ranges / resolutions. 
Window level can be adapted relatively easily, without needing multiple strokes to change it from min to max value and vice versa.
**How to reproduce** 
[axial.nii.gz](https://github.com/user-attachments/files/21162027/axial.nii.gz)
Load the above file in the `niftiWithTools` example, and change the windowLevel using the `WindowLevelTool` (selected by default).
-> it is really hard to change …
=> fix(WindowLevelTool): adapt voi multiplier based on dynamic range for volume viewports

packages/tools/src/tools/CrosshairsTool.ts
Add `referenceLinesCenterGapRatio` config option to allow the crosshairs center gap to scale proportionally with the canvas size. The gap now uses the ratio if provided, falling back to the default pixel value otherwise. Updated configuration and documentation comments accordingly.
fixes #54
| Before | After (ratio 0.05 -> 22.5px) | After(mobile/tablet ratio 0.05) |
| -------- | ------- | ------- |
| ![image](https://github.com/user-attachments/assets/760b71bf-eeb8-40b3-9bf9-b3891f79f232) | ![image](https://github.com/user-attachments/assets/b7976fe2-6002-4d3e-aee9-6fd494b62dea) | ![image](https://github.com/user-attachments/assets/c5291aed-4127-4dae-8d50-5142dd0c30a4)
etc.)
[blog]: …
=> feat(CrosshairsTool): add support for center gap ratio in reference lines

packages/tools/src/stateManagement/segmentation/internalAddSegmentationRepresentation.ts
This pull request updates the logic for setting the default active segment index in the `internalAddSegmentationRepresentation` function to ensure it dynamically selects the first segment based on the segmentation's data.
* [`packages/tools/src/stateManagement/segmentation/internalAddSegmentationRepresentation.ts`](diffhunk://#diff-0153ff619168e4074ab0f409b96ef7c6cf50c3adb1f838c51d54b688c3378273L32-R43): Updated the logic to dynamically determine the first segment index by retrieving and sorting segment keys, ensuring the default is set correctly even if segments are not numbered sequentially.
=> fix: first segment active 

packages/adapters/.gitignore, packages/adapters/src/adapters/Cornerstone/MeasurementReport.js, packages/adapters/src/adapters/Cornerstone3D/Length.ts, packages/adapters/src/adapters/Cornerstone3D/MeasurementReport.ts, packages/adapters/src/adapters/Cornerstone3D/RectangleROI.ts, packages/adapters/src/version.ts
Some of the annotation adapters weren't storing referenced frame of reference uid, nor were they creating cached stats.
Add both items automatically when appropriate.
Add Ref FOR for 3d measurements
Add cached stats always
Link into OHIF and save 3d annotations.
etc.)
- [] "OS: 
- [] "Browser:
=> fix: Ensure FOR is stored when required and cachedStats created

packages/tools/src/utilities/stackPrefetch/stackContextPrefetch.ts
Currently `0` is used for the image loader when prefetching for stack images. I added `priority` as a parameter to `enable` method. `0` will be used by default when omitting that parameter so it will not break others.
=> priority prefetch

packages/tools/test/CircleROIStartEnd_test.js, packages/tools/test/RectangleROIStartEnd_test.js
As discussed at office hour, I add a simple test to at least check those tools are not broken by changes,
Would need to make more extensive tests to tests manipulation of start and end slices (missing time to do it)
Thus PR https://github.com/cornerstonejs/cornerstone3D/pull/2254 and https://github.com/cornerstonejs/cornerstone3D/pull/2221 shall not break these tests
=> add tests for circle and rectangle start stop

packages/core/src/types/PixelDataTypedArray.ts, packages/core/src/utilities/generateVolumePropsFromImageIds.ts, packages/nifti-volume-loader/src/helpers/dataTypeCodeHelper.ts, packages/nifti-volume-loader/src/helpers/modalityScaleNifti.ts
Fixes #2314 
Adds support for NIFTI datatype 64 (float64/double precision) to cornerstone3D's NIFTI volume loader, fixing the error "NIFTI datatypeCode 64 is not yet supported".
*Core Package (packages/core/)*
- `src/types/PixelDataTypedArray.ts`: Added Float64Array to PixelDataTypedArray and PixelDataTypedArrayString type definitions
-  `src/utilities/generateVolumePropsFromImageIds.ts`: Added case for 64-bit allocation to return 'Float64Array' in the bits allocation switch statement
*NIFTI Volume Loader (packages/nifti-volume-loader/)*
- `src/helpers/dataTypeCodeHelper.ts`: Added support for NIFTI_TYPE_FLOAT64 constant to return Float64Array constructor
- `src/helpers/modalityScaleNifti.ts`:
- Added case for NIFTI_TYPE_FLOAT64 to create
Float64Array buffer and allocate scalar data
- …
=> fix(NiftiVolumeLoader): add float64 support to nifti volume loader

packages/core/src/enums/Events.ts, packages/tools/src/enums/Events.ts, packages/tools/src/types/EventTypes.ts, packages/tools/src/utilities/stackPrefetch/stackContextPrefetch.ts, packages/tools/src/utilities/stackPrefetch/stackPrefetch.ts
When using the prefetch mechanism for stack viewports, it is often desirable to give the user visual feedback regarding the prefetching progress, so that the user can see when a series has been completely loaded and scrolling across the stack is possible. Currently, it is possible to monitor the load progress via events triggered by the dicom-image-loader but the images still need to be decoded afterwards, which can take a moment for large series. The IMAGE_LOAD event on the eventTarget, on the other hand, triggers for also for scroll events. Thus, hooking into this event could have performance implications. Therefore, this PR adds a new event that is triggered from the DoneCallback function of the StackPrefetch mechanism when the prefetching list has been emptied. The last-loaded imageId …
=> feat(Stackprefetch): add event that is triggered when the stack prefetch for a viewport has completed
